// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: iota/grpc/v1/epoch.proto

package epoch

import (
	_ "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/options"
	bcs "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/bcs"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A member of a validator committee.
type ValidatorCommitteeMember struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The 96-byte Bls12381 public key for this validator.
	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3,oneof" json:"public_key,omitempty"`
	// voting weight this validator possesses.
	Weight        *uint64 `protobuf:"varint,2,opt,name=weight,proto3,oneof" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatorCommitteeMember) Reset() {
	*x = ValidatorCommitteeMember{}
	mi := &file_iota_grpc_v1_epoch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorCommitteeMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorCommitteeMember) ProtoMessage() {}

func (x *ValidatorCommitteeMember) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_epoch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorCommitteeMember.ProtoReflect.Descriptor instead.
func (*ValidatorCommitteeMember) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_epoch_proto_rawDescGZIP(), []int{0}
}

func (x *ValidatorCommitteeMember) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *ValidatorCommitteeMember) GetWeight() uint64 {
	if x != nil && x.Weight != nil {
		return *x.Weight
	}
	return 0
}

type ValidatorCommitteeMembers struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Members       []*ValidatorCommitteeMember `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatorCommitteeMembers) Reset() {
	*x = ValidatorCommitteeMembers{}
	mi := &file_iota_grpc_v1_epoch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorCommitteeMembers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorCommitteeMembers) ProtoMessage() {}

func (x *ValidatorCommitteeMembers) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_epoch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorCommitteeMembers.ProtoReflect.Descriptor instead.
func (*ValidatorCommitteeMembers) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_epoch_proto_rawDescGZIP(), []int{1}
}

func (x *ValidatorCommitteeMembers) GetMembers() []*ValidatorCommitteeMember {
	if x != nil {
		return x.Members
	}
	return nil
}

// The validator set for a particular epoch.
type ValidatorCommittee struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The epoch where this committee governs.
	Epoch *uint64 `protobuf:"varint,1,opt,name=epoch,proto3,oneof" json:"epoch,omitempty"`
	// The committee members.
	Members       *ValidatorCommitteeMembers `protobuf:"bytes,2,opt,name=members,proto3,oneof" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatorCommittee) Reset() {
	*x = ValidatorCommittee{}
	mi := &file_iota_grpc_v1_epoch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorCommittee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorCommittee) ProtoMessage() {}

func (x *ValidatorCommittee) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_epoch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorCommittee.ProtoReflect.Descriptor instead.
func (*ValidatorCommittee) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_epoch_proto_rawDescGZIP(), []int{2}
}

func (x *ValidatorCommittee) GetEpoch() uint64 {
	if x != nil && x.Epoch != nil {
		return *x.Epoch
	}
	return 0
}

func (x *ValidatorCommittee) GetMembers() *ValidatorCommitteeMembers {
	if x != nil {
		return x.Members
	}
	return nil
}

type ProtocolFeatureFlags struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flags         map[string]bool        `protobuf:"bytes,1,rep,name=flags,proto3" json:"flags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolFeatureFlags) Reset() {
	*x = ProtocolFeatureFlags{}
	mi := &file_iota_grpc_v1_epoch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolFeatureFlags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolFeatureFlags) ProtoMessage() {}

func (x *ProtocolFeatureFlags) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_epoch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolFeatureFlags.ProtoReflect.Descriptor instead.
func (*ProtocolFeatureFlags) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_epoch_proto_rawDescGZIP(), []int{3}
}

func (x *ProtocolFeatureFlags) GetFlags() map[string]bool {
	if x != nil {
		return x.Flags
	}
	return nil
}

type ProtocolAttributes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attributes    map[string]string      `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolAttributes) Reset() {
	*x = ProtocolAttributes{}
	mi := &file_iota_grpc_v1_epoch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolAttributes) ProtoMessage() {}

func (x *ProtocolAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_epoch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolAttributes.ProtoReflect.Descriptor instead.
func (*ProtocolAttributes) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_epoch_proto_rawDescGZIP(), []int{4}
}

func (x *ProtocolAttributes) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type ProtocolConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion *uint64                `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3,oneof" json:"protocol_version,omitempty"`
	FeatureFlags    *ProtocolFeatureFlags  `protobuf:"bytes,2,opt,name=feature_flags,json=featureFlags,proto3,oneof" json:"feature_flags,omitempty"`
	Attributes      *ProtocolAttributes    `protobuf:"bytes,3,opt,name=attributes,proto3,oneof" json:"attributes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProtocolConfig) Reset() {
	*x = ProtocolConfig{}
	mi := &file_iota_grpc_v1_epoch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolConfig) ProtoMessage() {}

func (x *ProtocolConfig) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_epoch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolConfig.ProtoReflect.Descriptor instead.
func (*ProtocolConfig) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_epoch_proto_rawDescGZIP(), []int{5}
}

func (x *ProtocolConfig) GetProtocolVersion() uint64 {
	if x != nil && x.ProtocolVersion != nil {
		return *x.ProtocolVersion
	}
	return 0
}

func (x *ProtocolConfig) GetFeatureFlags() *ProtocolFeatureFlags {
	if x != nil {
		return x.FeatureFlags
	}
	return nil
}

func (x *ProtocolConfig) GetAttributes() *ProtocolAttributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type Epoch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Epoch *uint64                `protobuf:"varint,1,opt,name=epoch,proto3,oneof" json:"epoch,omitempty"`
	// The committee governing this epoch.
	Committee *ValidatorCommittee `protobuf:"bytes,2,opt,name=committee,proto3,oneof" json:"committee,omitempty"`
	// Snapshot of IOTA's SystemState (`0x3::iota_system::SystemState`) at the
	// beginning of the epoch, for past epochs, or the current state for the
	// current epoch.
	BcsSystemState  *bcs.BcsData           `protobuf:"bytes,3,opt,name=bcs_system_state,json=bcsSystemState,proto3,oneof" json:"bcs_system_state,omitempty"`
	FirstCheckpoint *uint64                `protobuf:"varint,4,opt,name=first_checkpoint,json=firstCheckpoint,proto3,oneof" json:"first_checkpoint,omitempty"`
	LastCheckpoint  *uint64                `protobuf:"varint,5,opt,name=last_checkpoint,json=lastCheckpoint,proto3,oneof" json:"last_checkpoint,omitempty"`
	Start           *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start,proto3,oneof" json:"start,omitempty"`
	End             *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end,proto3,oneof" json:"end,omitempty"`
	// Reference gas price denominated in NANOS
	ReferenceGasPrice *uint64         `protobuf:"varint,8,opt,name=reference_gas_price,json=referenceGasPrice,proto3,oneof" json:"reference_gas_price,omitempty"`
	ProtocolConfig    *ProtocolConfig `protobuf:"bytes,9,opt,name=protocol_config,json=protocolConfig,proto3,oneof" json:"protocol_config,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Epoch) Reset() {
	*x = Epoch{}
	mi := &file_iota_grpc_v1_epoch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Epoch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Epoch) ProtoMessage() {}

func (x *Epoch) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_epoch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Epoch.ProtoReflect.Descriptor instead.
func (*Epoch) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_epoch_proto_rawDescGZIP(), []int{6}
}

func (x *Epoch) GetEpoch() uint64 {
	if x != nil && x.Epoch != nil {
		return *x.Epoch
	}
	return 0
}

func (x *Epoch) GetCommittee() *ValidatorCommittee {
	if x != nil {
		return x.Committee
	}
	return nil
}

func (x *Epoch) GetBcsSystemState() *bcs.BcsData {
	if x != nil {
		return x.BcsSystemState
	}
	return nil
}

func (x *Epoch) GetFirstCheckpoint() uint64 {
	if x != nil && x.FirstCheckpoint != nil {
		return *x.FirstCheckpoint
	}
	return 0
}

func (x *Epoch) GetLastCheckpoint() uint64 {
	if x != nil && x.LastCheckpoint != nil {
		return *x.LastCheckpoint
	}
	return 0
}

func (x *Epoch) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Epoch) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *Epoch) GetReferenceGasPrice() uint64 {
	if x != nil && x.ReferenceGasPrice != nil {
		return *x.ReferenceGasPrice
	}
	return 0
}

func (x *Epoch) GetProtocolConfig() *ProtocolConfig {
	if x != nil {
		return x.ProtocolConfig
	}
	return nil
}

var File_iota_grpc_v1_epoch_proto protoreflect.FileDescriptor

const file_iota_grpc_v1_epoch_proto_rawDesc = "" +
	"\n" +
	"\x18iota/grpc/v1/epoch.proto\x12\x12iota.grpc.v1.epoch\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17iota/grpc/options.proto\x1a\x16iota/grpc/v1/bcs.proto\"\x7f\n" +
	"\x18ValidatorCommitteeMember\x12\"\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fH\x00R\tpublicKey\x88\x01\x01\x12\x1b\n" +
	"\x06weight\x18\x02 \x01(\x04H\x01R\x06weight\x88\x01\x01:\b\x82\xb5\x18\x04withB\r\n" +
	"\v_public_keyB\t\n" +
	"\a_weight\"m\n" +
	"\x19ValidatorCommitteeMembers\x12F\n" +
	"\amembers\x18\x01 \x03(\v2,.iota.grpc.v1.epoch.ValidatorCommitteeMemberR\amembers:\b\x82\xb5\x18\x04with\"\x9d\x01\n" +
	"\x12ValidatorCommittee\x12\x19\n" +
	"\x05epoch\x18\x01 \x01(\x04H\x00R\x05epoch\x88\x01\x01\x12L\n" +
	"\amembers\x18\x02 \x01(\v2-.iota.grpc.v1.epoch.ValidatorCommitteeMembersH\x01R\amembers\x88\x01\x01:\b\x82\xb5\x18\x04withB\b\n" +
	"\x06_epochB\n" +
	"\n" +
	"\b_members\"\xa9\x01\n" +
	"\x14ProtocolFeatureFlags\x12I\n" +
	"\x05flags\x18\x01 \x03(\v23.iota.grpc.v1.epoch.ProtocolFeatureFlags.FlagsEntryR\x05flags\x1a8\n" +
	"\n" +
	"FlagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01:\f\x82\xb5\x18\x04with\x90\xb5\x18\x01\"\xb9\x01\n" +
	"\x12ProtocolAttributes\x12V\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v26.iota.grpc.v1.epoch.ProtocolAttributes.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\f\x82\xb5\x18\x04with\x90\xb5\x18\x01\"\xa1\x02\n" +
	"\x0eProtocolConfig\x12.\n" +
	"\x10protocol_version\x18\x01 \x01(\x04H\x00R\x0fprotocolVersion\x88\x01\x01\x12R\n" +
	"\rfeature_flags\x18\x02 \x01(\v2(.iota.grpc.v1.epoch.ProtocolFeatureFlagsH\x01R\ffeatureFlags\x88\x01\x01\x12K\n" +
	"\n" +
	"attributes\x18\x03 \x01(\v2&.iota.grpc.v1.epoch.ProtocolAttributesH\x02R\n" +
	"attributes\x88\x01\x01:\b\x82\xb5\x18\x04withB\x13\n" +
	"\x11_protocol_versionB\x10\n" +
	"\x0e_feature_flagsB\r\n" +
	"\v_attributes\"\xa4\x05\n" +
	"\x05Epoch\x12\x19\n" +
	"\x05epoch\x18\x01 \x01(\x04H\x00R\x05epoch\x88\x01\x01\x12I\n" +
	"\tcommittee\x18\x02 \x01(\v2&.iota.grpc.v1.epoch.ValidatorCommitteeH\x01R\tcommittee\x88\x01\x01\x12H\n" +
	"\x10bcs_system_state\x18\x03 \x01(\v2\x19.iota.grpc.v1.bcs.BcsDataH\x02R\x0ebcsSystemState\x88\x01\x01\x12.\n" +
	"\x10first_checkpoint\x18\x04 \x01(\x04H\x03R\x0ffirstCheckpoint\x88\x01\x01\x12,\n" +
	"\x0flast_checkpoint\x18\x05 \x01(\x04H\x04R\x0elastCheckpoint\x88\x01\x01\x125\n" +
	"\x05start\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x05R\x05start\x88\x01\x01\x121\n" +
	"\x03end\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x06R\x03end\x88\x01\x01\x123\n" +
	"\x13reference_gas_price\x18\b \x01(\x04H\aR\x11referenceGasPrice\x88\x01\x01\x12P\n" +
	"\x0fprotocol_config\x18\t \x01(\v2\".iota.grpc.v1.epoch.ProtocolConfigH\bR\x0eprotocolConfig\x88\x01\x01:\b\x82\xb5\x18\x04withB\b\n" +
	"\x06_epochB\f\n" +
	"\n" +
	"_committeeB\x13\n" +
	"\x11_bcs_system_stateB\x13\n" +
	"\x11_first_checkpointB\x12\n" +
	"\x10_last_checkpointB\b\n" +
	"\x06_startB\x06\n" +
	"\x04_endB\x16\n" +
	"\x14_reference_gas_priceB\x12\n" +
	"\x10_protocol_configb\x06proto3"

var (
	file_iota_grpc_v1_epoch_proto_rawDescOnce sync.Once
	file_iota_grpc_v1_epoch_proto_rawDescData []byte
)

func file_iota_grpc_v1_epoch_proto_rawDescGZIP() []byte {
	file_iota_grpc_v1_epoch_proto_rawDescOnce.Do(func() {
		file_iota_grpc_v1_epoch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_epoch_proto_rawDesc), len(file_iota_grpc_v1_epoch_proto_rawDesc)))
	})
	return file_iota_grpc_v1_epoch_proto_rawDescData
}

var file_iota_grpc_v1_epoch_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_iota_grpc_v1_epoch_proto_goTypes = []any{
	(*ValidatorCommitteeMember)(nil),  // 0: iota.grpc.v1.epoch.ValidatorCommitteeMember
	(*ValidatorCommitteeMembers)(nil), // 1: iota.grpc.v1.epoch.ValidatorCommitteeMembers
	(*ValidatorCommittee)(nil),        // 2: iota.grpc.v1.epoch.ValidatorCommittee
	(*ProtocolFeatureFlags)(nil),      // 3: iota.grpc.v1.epoch.ProtocolFeatureFlags
	(*ProtocolAttributes)(nil),        // 4: iota.grpc.v1.epoch.ProtocolAttributes
	(*ProtocolConfig)(nil),            // 5: iota.grpc.v1.epoch.ProtocolConfig
	(*Epoch)(nil),                     // 6: iota.grpc.v1.epoch.Epoch
	nil,                               // 7: iota.grpc.v1.epoch.ProtocolFeatureFlags.FlagsEntry
	nil,                               // 8: iota.grpc.v1.epoch.ProtocolAttributes.AttributesEntry
	(*bcs.BcsData)(nil),               // 9: iota.grpc.v1.bcs.BcsData
	(*timestamppb.Timestamp)(nil),     // 10: google.protobuf.Timestamp
}
var file_iota_grpc_v1_epoch_proto_depIdxs = []int32{
	0,  // 0: iota.grpc.v1.epoch.ValidatorCommitteeMembers.members:type_name -> iota.grpc.v1.epoch.ValidatorCommitteeMember
	1,  // 1: iota.grpc.v1.epoch.ValidatorCommittee.members:type_name -> iota.grpc.v1.epoch.ValidatorCommitteeMembers
	7,  // 2: iota.grpc.v1.epoch.ProtocolFeatureFlags.flags:type_name -> iota.grpc.v1.epoch.ProtocolFeatureFlags.FlagsEntry
	8,  // 3: iota.grpc.v1.epoch.ProtocolAttributes.attributes:type_name -> iota.grpc.v1.epoch.ProtocolAttributes.AttributesEntry
	3,  // 4: iota.grpc.v1.epoch.ProtocolConfig.feature_flags:type_name -> iota.grpc.v1.epoch.ProtocolFeatureFlags
	4,  // 5: iota.grpc.v1.epoch.ProtocolConfig.attributes:type_name -> iota.grpc.v1.epoch.ProtocolAttributes
	2,  // 6: iota.grpc.v1.epoch.Epoch.committee:type_name -> iota.grpc.v1.epoch.ValidatorCommittee
	9,  // 7: iota.grpc.v1.epoch.Epoch.bcs_system_state:type_name -> iota.grpc.v1.bcs.BcsData
	10, // 8: iota.grpc.v1.epoch.Epoch.start:type_name -> google.protobuf.Timestamp
	10, // 9: iota.grpc.v1.epoch.Epoch.end:type_name -> google.protobuf.Timestamp
	5,  // 10: iota.grpc.v1.epoch.Epoch.protocol_config:type_name -> iota.grpc.v1.epoch.ProtocolConfig
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_iota_grpc_v1_epoch_proto_init() }
func file_iota_grpc_v1_epoch_proto_init() {
	if File_iota_grpc_v1_epoch_proto != nil {
		return
	}
	file_iota_grpc_v1_epoch_proto_msgTypes[0].OneofWrappers = []any{}
	file_iota_grpc_v1_epoch_proto_msgTypes[2].OneofWrappers = []any{}
	file_iota_grpc_v1_epoch_proto_msgTypes[5].OneofWrappers = []any{}
	file_iota_grpc_v1_epoch_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_epoch_proto_rawDesc), len(file_iota_grpc_v1_epoch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_iota_grpc_v1_epoch_proto_goTypes,
		DependencyIndexes: file_iota_grpc_v1_epoch_proto_depIdxs,
		MessageInfos:      file_iota_grpc_v1_epoch_proto_msgTypes,
	}.Build()
	File_iota_grpc_v1_epoch_proto = out.File
	file_iota_grpc_v1_epoch_proto_goTypes = nil
	file_iota_grpc_v1_epoch_proto_depIdxs = nil
}
