// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2026 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: iota/grpc/v1/coin.proto

package coin

import (
	_ "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/options"
	types "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Information about the state of the coin's MetadataCap
type CoinMetadata_MetadataCapState int32

const (
	// Indicates the state of the MetadataCap is unknown.
	// Set when the coin has not been migrated to the CoinRegistry.
	CoinMetadata_METADATA_CAP_STATE_UNKNOWN CoinMetadata_MetadataCapState = 0
	// Indicates the MetadataCap has been claimed.
	CoinMetadata_CLAIMED CoinMetadata_MetadataCapState = 1
	// Indicates the MetadataCap has not been claimed.
	CoinMetadata_UNCLAIMED CoinMetadata_MetadataCapState = 2
	// Indicates the MetadataCap has been deleted.
	CoinMetadata_DELETED CoinMetadata_MetadataCapState = 3
)

// Enum value maps for CoinMetadata_MetadataCapState.
var (
	CoinMetadata_MetadataCapState_name = map[int32]string{
		0: "METADATA_CAP_STATE_UNKNOWN",
		1: "CLAIMED",
		2: "UNCLAIMED",
		3: "DELETED",
	}
	CoinMetadata_MetadataCapState_value = map[string]int32{
		"METADATA_CAP_STATE_UNKNOWN": 0,
		"CLAIMED":                    1,
		"UNCLAIMED":                  2,
		"DELETED":                    3,
	}
)

func (x CoinMetadata_MetadataCapState) Enum() *CoinMetadata_MetadataCapState {
	p := new(CoinMetadata_MetadataCapState)
	*p = x
	return p
}

func (x CoinMetadata_MetadataCapState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoinMetadata_MetadataCapState) Descriptor() protoreflect.EnumDescriptor {
	return file_iota_grpc_v1_coin_proto_enumTypes[0].Descriptor()
}

func (CoinMetadata_MetadataCapState) Type() protoreflect.EnumType {
	return &file_iota_grpc_v1_coin_proto_enumTypes[0]
}

func (x CoinMetadata_MetadataCapState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CoinMetadata_MetadataCapState.Descriptor instead.
func (CoinMetadata_MetadataCapState) EnumDescriptor() ([]byte, []int) {
	return file_iota_grpc_v1_coin_proto_rawDescGZIP(), []int{0, 0}
}

// Supply state of a coin, matching the Move SupplyState enum
type CoinTreasury_SupplyState int32

const (
	// Supply is unknown or TreasuryCap still exists (minting still possible)
	CoinTreasury_SUPPLY_STATE_UNKNOWN CoinTreasury_SupplyState = 0
	// Supply is fixed (TreasuryCap consumed, no more minting possible)
	CoinTreasury_FIXED CoinTreasury_SupplyState = 1
	// Supply can only decrease (burning allowed, minting not allowed)
	CoinTreasury_BURN_ONLY CoinTreasury_SupplyState = 2
)

// Enum value maps for CoinTreasury_SupplyState.
var (
	CoinTreasury_SupplyState_name = map[int32]string{
		0: "SUPPLY_STATE_UNKNOWN",
		1: "FIXED",
		2: "BURN_ONLY",
	}
	CoinTreasury_SupplyState_value = map[string]int32{
		"SUPPLY_STATE_UNKNOWN": 0,
		"FIXED":                1,
		"BURN_ONLY":            2,
	}
)

func (x CoinTreasury_SupplyState) Enum() *CoinTreasury_SupplyState {
	p := new(CoinTreasury_SupplyState)
	*p = x
	return p
}

func (x CoinTreasury_SupplyState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoinTreasury_SupplyState) Descriptor() protoreflect.EnumDescriptor {
	return file_iota_grpc_v1_coin_proto_enumTypes[1].Descriptor()
}

func (CoinTreasury_SupplyState) Type() protoreflect.EnumType {
	return &file_iota_grpc_v1_coin_proto_enumTypes[1]
}

func (x CoinTreasury_SupplyState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CoinTreasury_SupplyState.Descriptor instead.
func (CoinTreasury_SupplyState) EnumDescriptor() ([]byte, []int) {
	return file_iota_grpc_v1_coin_proto_rawDescGZIP(), []int{1, 0}
}

// Indicates the state of the regulation of the coin.
type RegulatedCoinMetadata_CoinRegulatedState int32

const (
	// Indicates the regulation state of the coin is unknown.
	// This is set when a coin has not been migrated to the
	// coin registry and has no `0x2::coin::RegulatedCoinMetadata`
	// object.
	RegulatedCoinMetadata_COIN_REGULATED_STATE_UNKNOWN RegulatedCoinMetadata_CoinRegulatedState = 0
	// Indicates a coin is regulated. RegulatedCoinMetadata will be populated.
	RegulatedCoinMetadata_REGULATED RegulatedCoinMetadata_CoinRegulatedState = 1
	// Indicates a coin is unregulated.
	RegulatedCoinMetadata_UNREGULATED RegulatedCoinMetadata_CoinRegulatedState = 2
)

// Enum value maps for RegulatedCoinMetadata_CoinRegulatedState.
var (
	RegulatedCoinMetadata_CoinRegulatedState_name = map[int32]string{
		0: "COIN_REGULATED_STATE_UNKNOWN",
		1: "REGULATED",
		2: "UNREGULATED",
	}
	RegulatedCoinMetadata_CoinRegulatedState_value = map[string]int32{
		"COIN_REGULATED_STATE_UNKNOWN": 0,
		"REGULATED":                    1,
		"UNREGULATED":                  2,
	}
)

func (x RegulatedCoinMetadata_CoinRegulatedState) Enum() *RegulatedCoinMetadata_CoinRegulatedState {
	p := new(RegulatedCoinMetadata_CoinRegulatedState)
	*p = x
	return p
}

func (x RegulatedCoinMetadata_CoinRegulatedState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegulatedCoinMetadata_CoinRegulatedState) Descriptor() protoreflect.EnumDescriptor {
	return file_iota_grpc_v1_coin_proto_enumTypes[2].Descriptor()
}

func (RegulatedCoinMetadata_CoinRegulatedState) Type() protoreflect.EnumType {
	return &file_iota_grpc_v1_coin_proto_enumTypes[2]
}

func (x RegulatedCoinMetadata_CoinRegulatedState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegulatedCoinMetadata_CoinRegulatedState.Descriptor instead.
func (RegulatedCoinMetadata_CoinRegulatedState) EnumDescriptor() ([]byte, []int) {
	return file_iota_grpc_v1_coin_proto_rawDescGZIP(), []int{2, 0}
}

// Metadata for a coin type
type CoinMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ObjectId of the `0x2::coin::CoinMetadata` object or
	// 0x2::iota::coin_registry::Currency object (when registered with CoinRegistry).
	Id *types.ObjectId `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// Number of decimal places the coin uses.
	Decimals *uint32 `protobuf:"varint,2,opt,name=decimals,proto3,oneof" json:"decimals,omitempty"`
	// Name for the token
	Name *string `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Symbol for the token
	Symbol *string `protobuf:"bytes,4,opt,name=symbol,proto3,oneof" json:"symbol,omitempty"`
	// Description of the token
	Description *string `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// URL for the token logo
	IconUrl *string `protobuf:"bytes,6,opt,name=icon_url,json=iconUrl,proto3,oneof" json:"icon_url,omitempty"`
	// The MetadataCap ID if it has been claimed for this coin type.
	// This capability allows updating the coin's metadata fields.
	// Only populated when metadata is from CoinRegistry.
	MetadataCapId *types.ObjectId `protobuf:"bytes,7,opt,name=metadata_cap_id,json=metadataCapId,proto3,oneof" json:"metadata_cap_id,omitempty"`
	// State of the MetadataCap for this coin type.
	MetadataCapState *CoinMetadata_MetadataCapState `protobuf:"varint,8,opt,name=metadata_cap_state,json=metadataCapState,proto3,enum=iota.grpc.v1.coin.CoinMetadata_MetadataCapState,oneof" json:"metadata_cap_state,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CoinMetadata) Reset() {
	*x = CoinMetadata{}
	mi := &file_iota_grpc_v1_coin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoinMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinMetadata) ProtoMessage() {}

func (x *CoinMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_coin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinMetadata.ProtoReflect.Descriptor instead.
func (*CoinMetadata) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_coin_proto_rawDescGZIP(), []int{0}
}

func (x *CoinMetadata) GetId() *types.ObjectId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *CoinMetadata) GetDecimals() uint32 {
	if x != nil && x.Decimals != nil {
		return *x.Decimals
	}
	return 0
}

func (x *CoinMetadata) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CoinMetadata) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *CoinMetadata) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CoinMetadata) GetIconUrl() string {
	if x != nil && x.IconUrl != nil {
		return *x.IconUrl
	}
	return ""
}

func (x *CoinMetadata) GetMetadataCapId() *types.ObjectId {
	if x != nil {
		return x.MetadataCapId
	}
	return nil
}

func (x *CoinMetadata) GetMetadataCapState() CoinMetadata_MetadataCapState {
	if x != nil && x.MetadataCapState != nil {
		return *x.MetadataCapState
	}
	return CoinMetadata_METADATA_CAP_STATE_UNKNOWN
}

// Information about a coin type's `0x2::coin::TreasuryCap` and its total available supply
type CoinTreasury struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ObjectId of the `0x2::coin::TreasuryCap` object.
	Id *types.ObjectId `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// Total available supply for this coin type.
	TotalSupply *uint64 `protobuf:"varint,2,opt,name=total_supply,json=totalSupply,proto3,oneof" json:"total_supply,omitempty"`
	// Supply state indicating if the supply is fixed or can still be minted
	SupplyState   *CoinTreasury_SupplyState `protobuf:"varint,3,opt,name=supply_state,json=supplyState,proto3,enum=iota.grpc.v1.coin.CoinTreasury_SupplyState,oneof" json:"supply_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoinTreasury) Reset() {
	*x = CoinTreasury{}
	mi := &file_iota_grpc_v1_coin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoinTreasury) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinTreasury) ProtoMessage() {}

func (x *CoinTreasury) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_coin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinTreasury.ProtoReflect.Descriptor instead.
func (*CoinTreasury) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_coin_proto_rawDescGZIP(), []int{1}
}

func (x *CoinTreasury) GetId() *types.ObjectId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *CoinTreasury) GetTotalSupply() uint64 {
	if x != nil && x.TotalSupply != nil {
		return *x.TotalSupply
	}
	return 0
}

func (x *CoinTreasury) GetSupplyState() CoinTreasury_SupplyState {
	if x != nil && x.SupplyState != nil {
		return *x.SupplyState
	}
	return CoinTreasury_SUPPLY_STATE_UNKNOWN
}

// Information about a regulated coin, which indicates that it makes use of the transfer deny list.
type RegulatedCoinMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ObjectId of the `0x2::coin::RegulatedCoinMetadata` object.
	// Only present for coins that have not been migrated to CoinRegistry.
	Id *types.ObjectId `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// The ID of the coin's `CoinMetadata` or `CoinData` object.
	CoinMetadataObject *types.ObjectId `protobuf:"bytes,2,opt,name=coin_metadata_object,json=coinMetadataObject,proto3,oneof" json:"coin_metadata_object,omitempty"`
	// The ID of the coin's `DenyCap` object.
	DenyCapObject *types.ObjectId `protobuf:"bytes,3,opt,name=deny_cap_object,json=denyCapObject,proto3,oneof" json:"deny_cap_object,omitempty"`
	// Whether the coin can be globally paused
	AllowGlobalPause *bool `protobuf:"varint,4,opt,name=allow_global_pause,json=allowGlobalPause,proto3,oneof" json:"allow_global_pause,omitempty"`
	// Variant of the regulated coin metadata
	Variant *uint32 `protobuf:"varint,5,opt,name=variant,proto3,oneof" json:"variant,omitempty"`
	// Indicates the coin's regulated state.
	CoinRegulatedState *RegulatedCoinMetadata_CoinRegulatedState `protobuf:"varint,6,opt,name=coin_regulated_state,json=coinRegulatedState,proto3,enum=iota.grpc.v1.coin.RegulatedCoinMetadata_CoinRegulatedState,oneof" json:"coin_regulated_state,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegulatedCoinMetadata) Reset() {
	*x = RegulatedCoinMetadata{}
	mi := &file_iota_grpc_v1_coin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegulatedCoinMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegulatedCoinMetadata) ProtoMessage() {}

func (x *RegulatedCoinMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_coin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegulatedCoinMetadata.ProtoReflect.Descriptor instead.
func (*RegulatedCoinMetadata) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_coin_proto_rawDescGZIP(), []int{2}
}

func (x *RegulatedCoinMetadata) GetId() *types.ObjectId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *RegulatedCoinMetadata) GetCoinMetadataObject() *types.ObjectId {
	if x != nil {
		return x.CoinMetadataObject
	}
	return nil
}

func (x *RegulatedCoinMetadata) GetDenyCapObject() *types.ObjectId {
	if x != nil {
		return x.DenyCapObject
	}
	return nil
}

func (x *RegulatedCoinMetadata) GetAllowGlobalPause() bool {
	if x != nil && x.AllowGlobalPause != nil {
		return *x.AllowGlobalPause
	}
	return false
}

func (x *RegulatedCoinMetadata) GetVariant() uint32 {
	if x != nil && x.Variant != nil {
		return *x.Variant
	}
	return 0
}

func (x *RegulatedCoinMetadata) GetCoinRegulatedState() RegulatedCoinMetadata_CoinRegulatedState {
	if x != nil && x.CoinRegulatedState != nil {
		return *x.CoinRegulatedState
	}
	return RegulatedCoinMetadata_COIN_REGULATED_STATE_UNKNOWN
}

var File_iota_grpc_v1_coin_proto protoreflect.FileDescriptor

const file_iota_grpc_v1_coin_proto_rawDesc = "" +
	"\n" +
	"\x17iota/grpc/v1/coin.proto\x12\x11iota.grpc.v1.coin\x1a\x17iota/grpc/options.proto\x1a\x18iota/grpc/v1/types.proto\"\xe6\x04\n" +
	"\fCoinMetadata\x121\n" +
	"\x02id\x18\x01 \x01(\v2\x1c.iota.grpc.v1.types.ObjectIdH\x00R\x02id\x88\x01\x01\x12\x1f\n" +
	"\bdecimals\x18\x02 \x01(\rH\x01R\bdecimals\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x02R\x04name\x88\x01\x01\x12\x1b\n" +
	"\x06symbol\x18\x04 \x01(\tH\x03R\x06symbol\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x04R\vdescription\x88\x01\x01\x12\x1e\n" +
	"\bicon_url\x18\x06 \x01(\tH\x05R\aiconUrl\x88\x01\x01\x12I\n" +
	"\x0fmetadata_cap_id\x18\a \x01(\v2\x1c.iota.grpc.v1.types.ObjectIdH\x06R\rmetadataCapId\x88\x01\x01\x12c\n" +
	"\x12metadata_cap_state\x18\b \x01(\x0e20.iota.grpc.v1.coin.CoinMetadata.MetadataCapStateH\aR\x10metadataCapState\x88\x01\x01\"[\n" +
	"\x10MetadataCapState\x12\x1e\n" +
	"\x1aMETADATA_CAP_STATE_UNKNOWN\x10\x00\x12\v\n" +
	"\aCLAIMED\x10\x01\x12\r\n" +
	"\tUNCLAIMED\x10\x02\x12\v\n" +
	"\aDELETED\x10\x03:\b\x82\xb5\x18\x04withB\x05\n" +
	"\x03_idB\v\n" +
	"\t_decimalsB\a\n" +
	"\x05_nameB\t\n" +
	"\a_symbolB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_icon_urlB\x12\n" +
	"\x10_metadata_cap_idB\x15\n" +
	"\x13_metadata_cap_state\"\xb4\x02\n" +
	"\fCoinTreasury\x121\n" +
	"\x02id\x18\x01 \x01(\v2\x1c.iota.grpc.v1.types.ObjectIdH\x00R\x02id\x88\x01\x01\x12&\n" +
	"\ftotal_supply\x18\x02 \x01(\x04H\x01R\vtotalSupply\x88\x01\x01\x12S\n" +
	"\fsupply_state\x18\x03 \x01(\x0e2+.iota.grpc.v1.coin.CoinTreasury.SupplyStateH\x02R\vsupplyState\x88\x01\x01\"A\n" +
	"\vSupplyState\x12\x18\n" +
	"\x14SUPPLY_STATE_UNKNOWN\x10\x00\x12\t\n" +
	"\x05FIXED\x10\x01\x12\r\n" +
	"\tBURN_ONLY\x10\x02:\b\x82\xb5\x18\x04withB\x05\n" +
	"\x03_idB\x0f\n" +
	"\r_total_supplyB\x0f\n" +
	"\r_supply_state\"\x82\x05\n" +
	"\x15RegulatedCoinMetadata\x121\n" +
	"\x02id\x18\x01 \x01(\v2\x1c.iota.grpc.v1.types.ObjectIdH\x00R\x02id\x88\x01\x01\x12S\n" +
	"\x14coin_metadata_object\x18\x02 \x01(\v2\x1c.iota.grpc.v1.types.ObjectIdH\x01R\x12coinMetadataObject\x88\x01\x01\x12I\n" +
	"\x0fdeny_cap_object\x18\x03 \x01(\v2\x1c.iota.grpc.v1.types.ObjectIdH\x02R\rdenyCapObject\x88\x01\x01\x121\n" +
	"\x12allow_global_pause\x18\x04 \x01(\bH\x03R\x10allowGlobalPause\x88\x01\x01\x12\x1d\n" +
	"\avariant\x18\x05 \x01(\rH\x04R\avariant\x88\x01\x01\x12r\n" +
	"\x14coin_regulated_state\x18\x06 \x01(\x0e2;.iota.grpc.v1.coin.RegulatedCoinMetadata.CoinRegulatedStateH\x05R\x12coinRegulatedState\x88\x01\x01\"V\n" +
	"\x12CoinRegulatedState\x12 \n" +
	"\x1cCOIN_REGULATED_STATE_UNKNOWN\x10\x00\x12\r\n" +
	"\tREGULATED\x10\x01\x12\x0f\n" +
	"\vUNREGULATED\x10\x02:\b\x82\xb5\x18\x04withB\x05\n" +
	"\x03_idB\x17\n" +
	"\x15_coin_metadata_objectB\x12\n" +
	"\x10_deny_cap_objectB\x15\n" +
	"\x13_allow_global_pauseB\n" +
	"\n" +
	"\b_variantB\x17\n" +
	"\x15_coin_regulated_stateb\x06proto3"

var (
	file_iota_grpc_v1_coin_proto_rawDescOnce sync.Once
	file_iota_grpc_v1_coin_proto_rawDescData []byte
)

func file_iota_grpc_v1_coin_proto_rawDescGZIP() []byte {
	file_iota_grpc_v1_coin_proto_rawDescOnce.Do(func() {
		file_iota_grpc_v1_coin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_coin_proto_rawDesc), len(file_iota_grpc_v1_coin_proto_rawDesc)))
	})
	return file_iota_grpc_v1_coin_proto_rawDescData
}

var file_iota_grpc_v1_coin_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_iota_grpc_v1_coin_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_iota_grpc_v1_coin_proto_goTypes = []any{
	(CoinMetadata_MetadataCapState)(0),            // 0: iota.grpc.v1.coin.CoinMetadata.MetadataCapState
	(CoinTreasury_SupplyState)(0),                 // 1: iota.grpc.v1.coin.CoinTreasury.SupplyState
	(RegulatedCoinMetadata_CoinRegulatedState)(0), // 2: iota.grpc.v1.coin.RegulatedCoinMetadata.CoinRegulatedState
	(*CoinMetadata)(nil),                          // 3: iota.grpc.v1.coin.CoinMetadata
	(*CoinTreasury)(nil),                          // 4: iota.grpc.v1.coin.CoinTreasury
	(*RegulatedCoinMetadata)(nil),                 // 5: iota.grpc.v1.coin.RegulatedCoinMetadata
	(*types.ObjectId)(nil),                        // 6: iota.grpc.v1.types.ObjectId
}
var file_iota_grpc_v1_coin_proto_depIdxs = []int32{
	6, // 0: iota.grpc.v1.coin.CoinMetadata.id:type_name -> iota.grpc.v1.types.ObjectId
	6, // 1: iota.grpc.v1.coin.CoinMetadata.metadata_cap_id:type_name -> iota.grpc.v1.types.ObjectId
	0, // 2: iota.grpc.v1.coin.CoinMetadata.metadata_cap_state:type_name -> iota.grpc.v1.coin.CoinMetadata.MetadataCapState
	6, // 3: iota.grpc.v1.coin.CoinTreasury.id:type_name -> iota.grpc.v1.types.ObjectId
	1, // 4: iota.grpc.v1.coin.CoinTreasury.supply_state:type_name -> iota.grpc.v1.coin.CoinTreasury.SupplyState
	6, // 5: iota.grpc.v1.coin.RegulatedCoinMetadata.id:type_name -> iota.grpc.v1.types.ObjectId
	6, // 6: iota.grpc.v1.coin.RegulatedCoinMetadata.coin_metadata_object:type_name -> iota.grpc.v1.types.ObjectId
	6, // 7: iota.grpc.v1.coin.RegulatedCoinMetadata.deny_cap_object:type_name -> iota.grpc.v1.types.ObjectId
	2, // 8: iota.grpc.v1.coin.RegulatedCoinMetadata.coin_regulated_state:type_name -> iota.grpc.v1.coin.RegulatedCoinMetadata.CoinRegulatedState
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_iota_grpc_v1_coin_proto_init() }
func file_iota_grpc_v1_coin_proto_init() {
	if File_iota_grpc_v1_coin_proto != nil {
		return
	}
	file_iota_grpc_v1_coin_proto_msgTypes[0].OneofWrappers = []any{}
	file_iota_grpc_v1_coin_proto_msgTypes[1].OneofWrappers = []any{}
	file_iota_grpc_v1_coin_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_coin_proto_rawDesc), len(file_iota_grpc_v1_coin_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_iota_grpc_v1_coin_proto_goTypes,
		DependencyIndexes: file_iota_grpc_v1_coin_proto_depIdxs,
		EnumInfos:         file_iota_grpc_v1_coin_proto_enumTypes,
		MessageInfos:      file_iota_grpc_v1_coin_proto_msgTypes,
	}.Build()
	File_iota_grpc_v1_coin_proto = out.File
	file_iota_grpc_v1_coin_proto_goTypes = nil
	file_iota_grpc_v1_coin_proto_depIdxs = nil
}
