// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: iota/grpc/v1/transaction_execution_service.proto

package transaction_execution_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransactionExecutionService_ExecuteTransactions_FullMethodName  = "/iota.grpc.v1.transaction_execution_service.TransactionExecutionService/ExecuteTransactions"
	TransactionExecutionService_SimulateTransactions_FullMethodName = "/iota.grpc.v1.transaction_execution_service.TransactionExecutionService/SimulateTransactions"
)

// TransactionExecutionServiceClient is the client API for TransactionExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionExecutionServiceClient interface {
	ExecuteTransactions(ctx context.Context, in *ExecuteTransactionsRequest, opts ...grpc.CallOption) (*ExecuteTransactionsResponse, error)
	SimulateTransactions(ctx context.Context, in *SimulateTransactionsRequest, opts ...grpc.CallOption) (*SimulateTransactionsResponse, error)
}

type transactionExecutionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionExecutionServiceClient(cc grpc.ClientConnInterface) TransactionExecutionServiceClient {
	return &transactionExecutionServiceClient{cc}
}

func (c *transactionExecutionServiceClient) ExecuteTransactions(ctx context.Context, in *ExecuteTransactionsRequest, opts ...grpc.CallOption) (*ExecuteTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteTransactionsResponse)
	err := c.cc.Invoke(ctx, TransactionExecutionService_ExecuteTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionExecutionServiceClient) SimulateTransactions(ctx context.Context, in *SimulateTransactionsRequest, opts ...grpc.CallOption) (*SimulateTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimulateTransactionsResponse)
	err := c.cc.Invoke(ctx, TransactionExecutionService_SimulateTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionExecutionServiceServer is the server API for TransactionExecutionService service.
// All implementations must embed UnimplementedTransactionExecutionServiceServer
// for forward compatibility.
type TransactionExecutionServiceServer interface {
	ExecuteTransactions(context.Context, *ExecuteTransactionsRequest) (*ExecuteTransactionsResponse, error)
	SimulateTransactions(context.Context, *SimulateTransactionsRequest) (*SimulateTransactionsResponse, error)
	mustEmbedUnimplementedTransactionExecutionServiceServer()
}

// UnimplementedTransactionExecutionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionExecutionServiceServer struct{}

func (UnimplementedTransactionExecutionServiceServer) ExecuteTransactions(context.Context, *ExecuteTransactionsRequest) (*ExecuteTransactionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTransactions not implemented")
}
func (UnimplementedTransactionExecutionServiceServer) SimulateTransactions(context.Context, *SimulateTransactionsRequest) (*SimulateTransactionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SimulateTransactions not implemented")
}
func (UnimplementedTransactionExecutionServiceServer) mustEmbedUnimplementedTransactionExecutionServiceServer() {
}
func (UnimplementedTransactionExecutionServiceServer) testEmbeddedByValue() {}

// UnsafeTransactionExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionExecutionServiceServer will
// result in compilation errors.
type UnsafeTransactionExecutionServiceServer interface {
	mustEmbedUnimplementedTransactionExecutionServiceServer()
}

func RegisterTransactionExecutionServiceServer(s grpc.ServiceRegistrar, srv TransactionExecutionServiceServer) {
	// If the following call panics, it indicates UnimplementedTransactionExecutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionExecutionService_ServiceDesc, srv)
}

func _TransactionExecutionService_ExecuteTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionExecutionServiceServer).ExecuteTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionExecutionService_ExecuteTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionExecutionServiceServer).ExecuteTransactions(ctx, req.(*ExecuteTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionExecutionService_SimulateTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulateTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionExecutionServiceServer).SimulateTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionExecutionService_SimulateTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionExecutionServiceServer).SimulateTransactions(ctx, req.(*SimulateTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionExecutionService_ServiceDesc is the grpc.ServiceDesc for TransactionExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iota.grpc.v1.transaction_execution_service.TransactionExecutionService",
	HandlerType: (*TransactionExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteTransactions",
			Handler:    _TransactionExecutionService_ExecuteTransactions_Handler,
		},
		{
			MethodName: "SimulateTransactions",
			Handler:    _TransactionExecutionService_SimulateTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iota/grpc/v1/transaction_execution_service.proto",
}
