// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: iota/grpc/v1/transaction_execution_service.proto

package transaction_execution_service

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	_ "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/options"
	bcs "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/bcs"
	command "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/command"
	signatures "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/signatures"
	transaction "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/transaction"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	_ "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Individual check modes that can be enabled/disabled
type SimulateTransactionItem_TransactionCheckModes int32

const (
	// / WARNING! Using this mode will bypass all normal checks around Move entry functions! This
	// / includes the various rules for function arguments, meaning any object can be created just from
	// / BCS bytes!
	SimulateTransactionItem_DISABLE_VM_CHECKS SimulateTransactionItem_TransactionCheckModes = 0
)

// Enum value maps for SimulateTransactionItem_TransactionCheckModes.
var (
	SimulateTransactionItem_TransactionCheckModes_name = map[int32]string{
		0: "DISABLE_VM_CHECKS",
	}
	SimulateTransactionItem_TransactionCheckModes_value = map[string]int32{
		"DISABLE_VM_CHECKS": 0,
	}
)

func (x SimulateTransactionItem_TransactionCheckModes) Enum() *SimulateTransactionItem_TransactionCheckModes {
	p := new(SimulateTransactionItem_TransactionCheckModes)
	*p = x
	return p
}

func (x SimulateTransactionItem_TransactionCheckModes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimulateTransactionItem_TransactionCheckModes) Descriptor() protoreflect.EnumDescriptor {
	return file_iota_grpc_v1_transaction_execution_service_proto_enumTypes[0].Descriptor()
}

func (SimulateTransactionItem_TransactionCheckModes) Type() protoreflect.EnumType {
	return &file_iota_grpc_v1_transaction_execution_service_proto_enumTypes[0]
}

func (x SimulateTransactionItem_TransactionCheckModes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SimulateTransactionItem_TransactionCheckModes.Descriptor instead.
func (SimulateTransactionItem_TransactionCheckModes) EnumDescriptor() ([]byte, []int) {
	return file_iota_grpc_v1_transaction_execution_service_proto_rawDescGZIP(), []int{4, 0}
}

// A single transaction to execute, along with its authorizing signatures.
type ExecuteTransactionItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The transaction to execute.
	Transaction *transaction.Transaction `protobuf:"bytes,1,opt,name=transaction,proto3,oneof" json:"transaction,omitempty"`
	// Set of `iota.grpc.v1.signatures.UserSignature`s authorizing the execution of the provided
	// transaction.
	Signatures    *signatures.UserSignatures `protobuf:"bytes,2,opt,name=signatures,proto3,oneof" json:"signatures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTransactionItem) Reset() {
	*x = ExecuteTransactionItem{}
	mi := &file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTransactionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTransactionItem) ProtoMessage() {}

func (x *ExecuteTransactionItem) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTransactionItem.ProtoReflect.Descriptor instead.
func (*ExecuteTransactionItem) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_transaction_execution_service_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteTransactionItem) GetTransaction() *transaction.Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *ExecuteTransactionItem) GetSignatures() *signatures.UserSignatures {
	if x != nil {
		return x.Signatures
	}
	return nil
}

type ExecuteTransactionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of transactions to execute. Transactions are executed sequentially in order.
	// For a single transaction, provide a list with one item.
	Transactions []*ExecuteTransactionItem `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	// Mask specifying which fields to read, applied to each ExecutedTransaction in the response.
	// If no mask is specified, defaults to `transaction.digest,effects,events,input_objects,output_objects`.
	ReadMask *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3,oneof" json:"read_mask,omitempty"`
	// Optional timeout in milliseconds for waiting for checkpoint inclusion.
	// If set and > 0, after executing all transactions, the server waits up to
	// this duration for them to be included in a checkpoint, populating the
	// `checkpoint` and `timestamp` fields in the response, if specified in `read_mask`.
	// If not set or zero, no waiting is done (default behavior).
	// The server may clamp this to a configured maximum.
	CheckpointInclusionTimeoutMs *uint64 `protobuf:"varint,3,opt,name=checkpoint_inclusion_timeout_ms,json=checkpointInclusionTimeoutMs,proto3,oneof" json:"checkpoint_inclusion_timeout_ms,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *ExecuteTransactionsRequest) Reset() {
	*x = ExecuteTransactionsRequest{}
	mi := &file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTransactionsRequest) ProtoMessage() {}

func (x *ExecuteTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ExecuteTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_transaction_execution_service_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteTransactionsRequest) GetTransactions() []*ExecuteTransactionItem {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ExecuteTransactionsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

func (x *ExecuteTransactionsRequest) GetCheckpointInclusionTimeoutMs() uint64 {
	if x != nil && x.CheckpointInclusionTimeoutMs != nil {
		return *x.CheckpointInclusionTimeoutMs
	}
	return 0
}

// The result of executing a single transaction: either the executed transaction or an error.
type ExecuteTransactionResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ExecuteTransactionResult_ExecutedTransaction
	//	*ExecuteTransactionResult_Error
	Result        isExecuteTransactionResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTransactionResult) Reset() {
	*x = ExecuteTransactionResult{}
	mi := &file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTransactionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTransactionResult) ProtoMessage() {}

func (x *ExecuteTransactionResult) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTransactionResult.ProtoReflect.Descriptor instead.
func (*ExecuteTransactionResult) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_transaction_execution_service_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteTransactionResult) GetResult() isExecuteTransactionResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecuteTransactionResult) GetExecutedTransaction() *transaction.ExecutedTransaction {
	if x != nil {
		if x, ok := x.Result.(*ExecuteTransactionResult_ExecutedTransaction); ok {
			return x.ExecutedTransaction
		}
	}
	return nil
}

func (x *ExecuteTransactionResult) GetError() *status.Status {
	if x != nil {
		if x, ok := x.Result.(*ExecuteTransactionResult_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isExecuteTransactionResult_Result interface {
	isExecuteTransactionResult_Result()
}

type ExecuteTransactionResult_ExecutedTransaction struct {
	ExecutedTransaction *transaction.ExecutedTransaction `protobuf:"bytes,1,opt,name=executed_transaction,json=executedTransaction,proto3,oneof"`
}

type ExecuteTransactionResult_Error struct {
	Error *status.Status `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ExecuteTransactionResult_ExecutedTransaction) isExecuteTransactionResult_Result() {}

func (*ExecuteTransactionResult_Error) isExecuteTransactionResult_Result() {}

// Response message for `TransactionExecutionService.ExecuteTransactions`.
type ExecuteTransactionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Results for each transaction in the request, in the same order.
	TransactionResults []*ExecuteTransactionResult `protobuf:"bytes,1,rep,name=transaction_results,json=transactionResults,proto3" json:"transaction_results,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExecuteTransactionsResponse) Reset() {
	*x = ExecuteTransactionsResponse{}
	mi := &file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTransactionsResponse) ProtoMessage() {}

func (x *ExecuteTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ExecuteTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_transaction_execution_service_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteTransactionsResponse) GetTransactionResults() []*ExecuteTransactionResult {
	if x != nil {
		return x.TransactionResults
	}
	return nil
}

// A single transaction to simulate, along with simulation options.
type SimulateTransactionItem struct {
	state       protoimpl.MessageState   `protogen:"open.v1"`
	Transaction *transaction.Transaction `protobuf:"bytes,1,opt,name=transaction,proto3,oneof" json:"transaction,omitempty"`
	// List of checks to disable. If empty, all checks are enabled (default).
	TxChecks      []SimulateTransactionItem_TransactionCheckModes `protobuf:"varint,2,rep,packed,name=tx_checks,json=txChecks,proto3,enum=iota.grpc.v1.transaction_execution_service.SimulateTransactionItem_TransactionCheckModes" json:"tx_checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulateTransactionItem) Reset() {
	*x = SimulateTransactionItem{}
	mi := &file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateTransactionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateTransactionItem) ProtoMessage() {}

func (x *SimulateTransactionItem) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateTransactionItem.ProtoReflect.Descriptor instead.
func (*SimulateTransactionItem) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_transaction_execution_service_proto_rawDescGZIP(), []int{4}
}

func (x *SimulateTransactionItem) GetTransaction() *transaction.Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *SimulateTransactionItem) GetTxChecks() []SimulateTransactionItem_TransactionCheckModes {
	if x != nil {
		return x.TxChecks
	}
	return nil
}

type SimulateTransactionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of transactions to simulate. Transactions are simulated sequentially in order.
	// For a single transaction, provide a list with one item.
	Transactions []*SimulateTransactionItem `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	// Mask specifying which fields to read, applied to each SimulatedTransaction in the response.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3,oneof" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulateTransactionsRequest) Reset() {
	*x = SimulateTransactionsRequest{}
	mi := &file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateTransactionsRequest) ProtoMessage() {}

func (x *SimulateTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateTransactionsRequest.ProtoReflect.Descriptor instead.
func (*SimulateTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_transaction_execution_service_proto_rawDescGZIP(), []int{5}
}

func (x *SimulateTransactionsRequest) GetTransactions() []*SimulateTransactionItem {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *SimulateTransactionsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

type ExecutionError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The execution error kind as BCS-encoded data
	BcsKind *bcs.BcsData `protobuf:"bytes,1,opt,name=bcs_kind,json=bcsKind,proto3,oneof" json:"bcs_kind,omitempty"`
	// Optional error source as string
	Source *string `protobuf:"bytes,2,opt,name=source,proto3,oneof" json:"source,omitempty"`
	// Optional command index
	CommandIndex  *uint64 `protobuf:"varint,3,opt,name=command_index,json=commandIndex,proto3,oneof" json:"command_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionError) Reset() {
	*x = ExecutionError{}
	mi := &file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionError) ProtoMessage() {}

func (x *ExecutionError) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionError.ProtoReflect.Descriptor instead.
func (*ExecutionError) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_transaction_execution_service_proto_rawDescGZIP(), []int{6}
}

func (x *ExecutionError) GetBcsKind() *bcs.BcsData {
	if x != nil {
		return x.BcsKind
	}
	return nil
}

func (x *ExecutionError) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *ExecutionError) GetCommandIndex() uint64 {
	if x != nil && x.CommandIndex != nil {
		return *x.CommandIndex
	}
	return 0
}

// The result of simulating a single transaction.
type SimulatedTransaction struct {
	state               protoimpl.MessageState           `protogen:"open.v1"`
	ExecutedTransaction *transaction.ExecutedTransaction `protobuf:"bytes,1,opt,name=executed_transaction,json=executedTransaction,proto3,oneof" json:"executed_transaction,omitempty"`
	SuggestedGasPrice   *uint64                          `protobuf:"varint,2,opt,name=suggested_gas_price,json=suggestedGasPrice,proto3,oneof" json:"suggested_gas_price,omitempty"`
	// Types that are valid to be assigned to ExecutionResult:
	//
	//	*SimulatedTransaction_CommandResults
	//	*SimulatedTransaction_ExecutionError
	ExecutionResult isSimulatedTransaction_ExecutionResult `protobuf_oneof:"execution_result"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SimulatedTransaction) Reset() {
	*x = SimulatedTransaction{}
	mi := &file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulatedTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulatedTransaction) ProtoMessage() {}

func (x *SimulatedTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulatedTransaction.ProtoReflect.Descriptor instead.
func (*SimulatedTransaction) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_transaction_execution_service_proto_rawDescGZIP(), []int{7}
}

func (x *SimulatedTransaction) GetExecutedTransaction() *transaction.ExecutedTransaction {
	if x != nil {
		return x.ExecutedTransaction
	}
	return nil
}

func (x *SimulatedTransaction) GetSuggestedGasPrice() uint64 {
	if x != nil && x.SuggestedGasPrice != nil {
		return *x.SuggestedGasPrice
	}
	return 0
}

func (x *SimulatedTransaction) GetExecutionResult() isSimulatedTransaction_ExecutionResult {
	if x != nil {
		return x.ExecutionResult
	}
	return nil
}

func (x *SimulatedTransaction) GetCommandResults() *command.CommandResults {
	if x != nil {
		if x, ok := x.ExecutionResult.(*SimulatedTransaction_CommandResults); ok {
			return x.CommandResults
		}
	}
	return nil
}

func (x *SimulatedTransaction) GetExecutionError() *ExecutionError {
	if x != nil {
		if x, ok := x.ExecutionResult.(*SimulatedTransaction_ExecutionError); ok {
			return x.ExecutionError
		}
	}
	return nil
}

type isSimulatedTransaction_ExecutionResult interface {
	isSimulatedTransaction_ExecutionResult()
}

type SimulatedTransaction_CommandResults struct {
	CommandResults *command.CommandResults `protobuf:"bytes,3,opt,name=command_results,json=commandResults,proto3,oneof"`
}

type SimulatedTransaction_ExecutionError struct {
	ExecutionError *ExecutionError `protobuf:"bytes,4,opt,name=execution_error,json=executionError,proto3,oneof"`
}

func (*SimulatedTransaction_CommandResults) isSimulatedTransaction_ExecutionResult() {}

func (*SimulatedTransaction_ExecutionError) isSimulatedTransaction_ExecutionResult() {}

// The result of simulating a single transaction: either the simulated transaction or an error.
type SimulateTransactionResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*SimulateTransactionResult_SimulatedTransaction
	//	*SimulateTransactionResult_Error
	Result        isSimulateTransactionResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulateTransactionResult) Reset() {
	*x = SimulateTransactionResult{}
	mi := &file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateTransactionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateTransactionResult) ProtoMessage() {}

func (x *SimulateTransactionResult) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateTransactionResult.ProtoReflect.Descriptor instead.
func (*SimulateTransactionResult) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_transaction_execution_service_proto_rawDescGZIP(), []int{8}
}

func (x *SimulateTransactionResult) GetResult() isSimulateTransactionResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *SimulateTransactionResult) GetSimulatedTransaction() *SimulatedTransaction {
	if x != nil {
		if x, ok := x.Result.(*SimulateTransactionResult_SimulatedTransaction); ok {
			return x.SimulatedTransaction
		}
	}
	return nil
}

func (x *SimulateTransactionResult) GetError() *status.Status {
	if x != nil {
		if x, ok := x.Result.(*SimulateTransactionResult_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isSimulateTransactionResult_Result interface {
	isSimulateTransactionResult_Result()
}

type SimulateTransactionResult_SimulatedTransaction struct {
	SimulatedTransaction *SimulatedTransaction `protobuf:"bytes,1,opt,name=simulated_transaction,json=simulatedTransaction,proto3,oneof"`
}

type SimulateTransactionResult_Error struct {
	Error *status.Status `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*SimulateTransactionResult_SimulatedTransaction) isSimulateTransactionResult_Result() {}

func (*SimulateTransactionResult_Error) isSimulateTransactionResult_Result() {}

// Response message for `TransactionExecutionService.SimulateTransactions`.
type SimulateTransactionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Results for each transaction in the request, in the same order.
	TransactionResults []*SimulateTransactionResult `protobuf:"bytes,1,rep,name=transaction_results,json=transactionResults,proto3" json:"transaction_results,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SimulateTransactionsResponse) Reset() {
	*x = SimulateTransactionsResponse{}
	mi := &file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateTransactionsResponse) ProtoMessage() {}

func (x *SimulateTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateTransactionsResponse.ProtoReflect.Descriptor instead.
func (*SimulateTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_transaction_execution_service_proto_rawDescGZIP(), []int{9}
}

func (x *SimulateTransactionsResponse) GetTransactionResults() []*SimulateTransactionResult {
	if x != nil {
		return x.TransactionResults
	}
	return nil
}

var File_iota_grpc_v1_transaction_execution_service_proto protoreflect.FileDescriptor

const file_iota_grpc_v1_transaction_execution_service_proto_rawDesc = "" +
	"\n" +
	"0iota/grpc/v1/transaction_execution_service.proto\x12*iota.grpc.v1.transaction_execution_service\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x17google/rpc/status.proto\x1a\x17iota/grpc/options.proto\x1a\x16iota/grpc/v1/bcs.proto\x1a\x1aiota/grpc/v1/command.proto\x1a\x1diota/grpc/v1/signatures.proto\x1a\x1eiota/grpc/v1/transaction.proto\"\xdd\x01\n" +
	"\x16ExecuteTransactionItem\x12L\n" +
	"\vtransaction\x18\x01 \x01(\v2%.iota.grpc.v1.transaction.TransactionH\x00R\vtransaction\x88\x01\x01\x12L\n" +
	"\n" +
	"signatures\x18\x02 \x01(\v2'.iota.grpc.v1.signatures.UserSignaturesH\x01R\n" +
	"signatures\x88\x01\x01:\b\x82\xb5\x18\x04withB\x0e\n" +
	"\f_transactionB\r\n" +
	"\v_signatures\"\xca\x02\n" +
	"\x1aExecuteTransactionsRequest\x12f\n" +
	"\ftransactions\x18\x01 \x03(\v2B.iota.grpc.v1.transaction_execution_service.ExecuteTransactionItemR\ftransactions\x12<\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskH\x00R\breadMask\x88\x01\x01\x12J\n" +
	"\x1fcheckpoint_inclusion_timeout_ms\x18\x03 \x01(\x04H\x01R\x1ccheckpointInclusionTimeoutMs\x88\x01\x01:\b\x82\xb5\x18\x04withB\f\n" +
	"\n" +
	"_read_maskB\"\n" +
	" _checkpoint_inclusion_timeout_ms\"\xbe\x01\n" +
	"\x18ExecuteTransactionResult\x12b\n" +
	"\x14executed_transaction\x18\x01 \x01(\v2-.iota.grpc.v1.transaction.ExecutedTransactionH\x00R\x13executedTransaction\x12*\n" +
	"\x05error\x18\x02 \x01(\v2\x12.google.rpc.StatusH\x00R\x05error:\b\x82\xb5\x18\x04withB\b\n" +
	"\x06result\"\x9e\x01\n" +
	"\x1bExecuteTransactionsResponse\x12u\n" +
	"\x13transaction_results\x18\x01 \x03(\v2D.iota.grpc.v1.transaction_execution_service.ExecuteTransactionResultR\x12transactionResults:\b\x82\xb5\x18\x04with\"\xa9\x02\n" +
	"\x17SimulateTransactionItem\x12L\n" +
	"\vtransaction\x18\x01 \x01(\v2%.iota.grpc.v1.transaction.TransactionH\x00R\vtransaction\x88\x01\x01\x12v\n" +
	"\ttx_checks\x18\x02 \x03(\x0e2Y.iota.grpc.v1.transaction_execution_service.SimulateTransactionItem.TransactionCheckModesR\btxChecks\".\n" +
	"\x15TransactionCheckModes\x12\x15\n" +
	"\x11DISABLE_VM_CHECKS\x10\x00:\b\x82\xb5\x18\x04withB\x0e\n" +
	"\f_transaction\"\xdc\x01\n" +
	"\x1bSimulateTransactionsRequest\x12g\n" +
	"\ftransactions\x18\x01 \x03(\v2C.iota.grpc.v1.transaction_execution_service.SimulateTransactionItemR\ftransactions\x12<\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskH\x00R\breadMask\x88\x01\x01:\b\x82\xb5\x18\x04withB\f\n" +
	"\n" +
	"_read_mask\"\xc6\x01\n" +
	"\x0eExecutionError\x129\n" +
	"\bbcs_kind\x18\x01 \x01(\v2\x19.iota.grpc.v1.bcs.BcsDataH\x00R\abcsKind\x88\x01\x01\x12\x1b\n" +
	"\x06source\x18\x02 \x01(\tH\x01R\x06source\x88\x01\x01\x12(\n" +
	"\rcommand_index\x18\x03 \x01(\x04H\x02R\fcommandIndex\x88\x01\x01:\b\x82\xb5\x18\x04withB\v\n" +
	"\t_bcs_kindB\t\n" +
	"\a_sourceB\x10\n" +
	"\x0e_command_index\"\xb9\x03\n" +
	"\x14SimulatedTransaction\x12e\n" +
	"\x14executed_transaction\x18\x01 \x01(\v2-.iota.grpc.v1.transaction.ExecutedTransactionH\x01R\x13executedTransaction\x88\x01\x01\x123\n" +
	"\x13suggested_gas_price\x18\x02 \x01(\x04H\x02R\x11suggestedGasPrice\x88\x01\x01\x12O\n" +
	"\x0fcommand_results\x18\x03 \x01(\v2$.iota.grpc.v1.command.CommandResultsH\x00R\x0ecommandResults\x12e\n" +
	"\x0fexecution_error\x18\x04 \x01(\v2:.iota.grpc.v1.transaction_execution_service.ExecutionErrorH\x00R\x0eexecutionError:\b\x82\xb5\x18\x04withB\x12\n" +
	"\x10execution_resultB\x17\n" +
	"\x15_executed_transactionB\x16\n" +
	"\x14_suggested_gas_price\"\xd4\x01\n" +
	"\x19SimulateTransactionResult\x12w\n" +
	"\x15simulated_transaction\x18\x01 \x01(\v2@.iota.grpc.v1.transaction_execution_service.SimulatedTransactionH\x00R\x14simulatedTransaction\x12*\n" +
	"\x05error\x18\x02 \x01(\v2\x12.google.rpc.StatusH\x00R\x05error:\b\x82\xb5\x18\x04withB\b\n" +
	"\x06result\"\xa0\x01\n" +
	"\x1cSimulateTransactionsResponse\x12v\n" +
	"\x13transaction_results\x18\x01 \x03(\v2E.iota.grpc.v1.transaction_execution_service.SimulateTransactionResultR\x12transactionResults:\b\x82\xb5\x18\x04with2\xf2\x02\n" +
	"\x1bTransactionExecutionService\x12\xa6\x01\n" +
	"\x13ExecuteTransactions\x12F.iota.grpc.v1.transaction_execution_service.ExecuteTransactionsRequest\x1aG.iota.grpc.v1.transaction_execution_service.ExecuteTransactionsResponse\x12\xa9\x01\n" +
	"\x14SimulateTransactions\x12G.iota.grpc.v1.transaction_execution_service.SimulateTransactionsRequest\x1aH.iota.grpc.v1.transaction_execution_service.SimulateTransactionsResponseb\x06proto3"

var (
	file_iota_grpc_v1_transaction_execution_service_proto_rawDescOnce sync.Once
	file_iota_grpc_v1_transaction_execution_service_proto_rawDescData []byte
)

func file_iota_grpc_v1_transaction_execution_service_proto_rawDescGZIP() []byte {
	file_iota_grpc_v1_transaction_execution_service_proto_rawDescOnce.Do(func() {
		file_iota_grpc_v1_transaction_execution_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_transaction_execution_service_proto_rawDesc), len(file_iota_grpc_v1_transaction_execution_service_proto_rawDesc)))
	})
	return file_iota_grpc_v1_transaction_execution_service_proto_rawDescData
}

var file_iota_grpc_v1_transaction_execution_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_iota_grpc_v1_transaction_execution_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_iota_grpc_v1_transaction_execution_service_proto_goTypes = []any{
	(SimulateTransactionItem_TransactionCheckModes)(0), // 0: iota.grpc.v1.transaction_execution_service.SimulateTransactionItem.TransactionCheckModes
	(*ExecuteTransactionItem)(nil),                     // 1: iota.grpc.v1.transaction_execution_service.ExecuteTransactionItem
	(*ExecuteTransactionsRequest)(nil),                 // 2: iota.grpc.v1.transaction_execution_service.ExecuteTransactionsRequest
	(*ExecuteTransactionResult)(nil),                   // 3: iota.grpc.v1.transaction_execution_service.ExecuteTransactionResult
	(*ExecuteTransactionsResponse)(nil),                // 4: iota.grpc.v1.transaction_execution_service.ExecuteTransactionsResponse
	(*SimulateTransactionItem)(nil),                    // 5: iota.grpc.v1.transaction_execution_service.SimulateTransactionItem
	(*SimulateTransactionsRequest)(nil),                // 6: iota.grpc.v1.transaction_execution_service.SimulateTransactionsRequest
	(*ExecutionError)(nil),                             // 7: iota.grpc.v1.transaction_execution_service.ExecutionError
	(*SimulatedTransaction)(nil),                       // 8: iota.grpc.v1.transaction_execution_service.SimulatedTransaction
	(*SimulateTransactionResult)(nil),                  // 9: iota.grpc.v1.transaction_execution_service.SimulateTransactionResult
	(*SimulateTransactionsResponse)(nil),               // 10: iota.grpc.v1.transaction_execution_service.SimulateTransactionsResponse
	(*transaction.Transaction)(nil),                    // 11: iota.grpc.v1.transaction.Transaction
	(*signatures.UserSignatures)(nil),                  // 12: iota.grpc.v1.signatures.UserSignatures
	(*fieldmaskpb.FieldMask)(nil),                      // 13: google.protobuf.FieldMask
	(*transaction.ExecutedTransaction)(nil),            // 14: iota.grpc.v1.transaction.ExecutedTransaction
	(*status.Status)(nil),                              // 15: google.rpc.Status
	(*bcs.BcsData)(nil),                                // 16: iota.grpc.v1.bcs.BcsData
	(*command.CommandResults)(nil),                     // 17: iota.grpc.v1.command.CommandResults
}
var file_iota_grpc_v1_transaction_execution_service_proto_depIdxs = []int32{
	11, // 0: iota.grpc.v1.transaction_execution_service.ExecuteTransactionItem.transaction:type_name -> iota.grpc.v1.transaction.Transaction
	12, // 1: iota.grpc.v1.transaction_execution_service.ExecuteTransactionItem.signatures:type_name -> iota.grpc.v1.signatures.UserSignatures
	1,  // 2: iota.grpc.v1.transaction_execution_service.ExecuteTransactionsRequest.transactions:type_name -> iota.grpc.v1.transaction_execution_service.ExecuteTransactionItem
	13, // 3: iota.grpc.v1.transaction_execution_service.ExecuteTransactionsRequest.read_mask:type_name -> google.protobuf.FieldMask
	14, // 4: iota.grpc.v1.transaction_execution_service.ExecuteTransactionResult.executed_transaction:type_name -> iota.grpc.v1.transaction.ExecutedTransaction
	15, // 5: iota.grpc.v1.transaction_execution_service.ExecuteTransactionResult.error:type_name -> google.rpc.Status
	3,  // 6: iota.grpc.v1.transaction_execution_service.ExecuteTransactionsResponse.transaction_results:type_name -> iota.grpc.v1.transaction_execution_service.ExecuteTransactionResult
	11, // 7: iota.grpc.v1.transaction_execution_service.SimulateTransactionItem.transaction:type_name -> iota.grpc.v1.transaction.Transaction
	0,  // 8: iota.grpc.v1.transaction_execution_service.SimulateTransactionItem.tx_checks:type_name -> iota.grpc.v1.transaction_execution_service.SimulateTransactionItem.TransactionCheckModes
	5,  // 9: iota.grpc.v1.transaction_execution_service.SimulateTransactionsRequest.transactions:type_name -> iota.grpc.v1.transaction_execution_service.SimulateTransactionItem
	13, // 10: iota.grpc.v1.transaction_execution_service.SimulateTransactionsRequest.read_mask:type_name -> google.protobuf.FieldMask
	16, // 11: iota.grpc.v1.transaction_execution_service.ExecutionError.bcs_kind:type_name -> iota.grpc.v1.bcs.BcsData
	14, // 12: iota.grpc.v1.transaction_execution_service.SimulatedTransaction.executed_transaction:type_name -> iota.grpc.v1.transaction.ExecutedTransaction
	17, // 13: iota.grpc.v1.transaction_execution_service.SimulatedTransaction.command_results:type_name -> iota.grpc.v1.command.CommandResults
	7,  // 14: iota.grpc.v1.transaction_execution_service.SimulatedTransaction.execution_error:type_name -> iota.grpc.v1.transaction_execution_service.ExecutionError
	8,  // 15: iota.grpc.v1.transaction_execution_service.SimulateTransactionResult.simulated_transaction:type_name -> iota.grpc.v1.transaction_execution_service.SimulatedTransaction
	15, // 16: iota.grpc.v1.transaction_execution_service.SimulateTransactionResult.error:type_name -> google.rpc.Status
	9,  // 17: iota.grpc.v1.transaction_execution_service.SimulateTransactionsResponse.transaction_results:type_name -> iota.grpc.v1.transaction_execution_service.SimulateTransactionResult
	2,  // 18: iota.grpc.v1.transaction_execution_service.TransactionExecutionService.ExecuteTransactions:input_type -> iota.grpc.v1.transaction_execution_service.ExecuteTransactionsRequest
	6,  // 19: iota.grpc.v1.transaction_execution_service.TransactionExecutionService.SimulateTransactions:input_type -> iota.grpc.v1.transaction_execution_service.SimulateTransactionsRequest
	4,  // 20: iota.grpc.v1.transaction_execution_service.TransactionExecutionService.ExecuteTransactions:output_type -> iota.grpc.v1.transaction_execution_service.ExecuteTransactionsResponse
	10, // 21: iota.grpc.v1.transaction_execution_service.TransactionExecutionService.SimulateTransactions:output_type -> iota.grpc.v1.transaction_execution_service.SimulateTransactionsResponse
	20, // [20:22] is the sub-list for method output_type
	18, // [18:20] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_iota_grpc_v1_transaction_execution_service_proto_init() }
func file_iota_grpc_v1_transaction_execution_service_proto_init() {
	if File_iota_grpc_v1_transaction_execution_service_proto != nil {
		return
	}
	file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[2].OneofWrappers = []any{
		(*ExecuteTransactionResult_ExecutedTransaction)(nil),
		(*ExecuteTransactionResult_Error)(nil),
	}
	file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[5].OneofWrappers = []any{}
	file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[7].OneofWrappers = []any{
		(*SimulatedTransaction_CommandResults)(nil),
		(*SimulatedTransaction_ExecutionError)(nil),
	}
	file_iota_grpc_v1_transaction_execution_service_proto_msgTypes[8].OneofWrappers = []any{
		(*SimulateTransactionResult_SimulatedTransaction)(nil),
		(*SimulateTransactionResult_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_transaction_execution_service_proto_rawDesc), len(file_iota_grpc_v1_transaction_execution_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iota_grpc_v1_transaction_execution_service_proto_goTypes,
		DependencyIndexes: file_iota_grpc_v1_transaction_execution_service_proto_depIdxs,
		EnumInfos:         file_iota_grpc_v1_transaction_execution_service_proto_enumTypes,
		MessageInfos:      file_iota_grpc_v1_transaction_execution_service_proto_msgTypes,
	}.Build()
	File_iota_grpc_v1_transaction_execution_service_proto = out.File
	file_iota_grpc_v1_transaction_execution_service_proto_goTypes = nil
	file_iota_grpc_v1_transaction_execution_service_proto_depIdxs = nil
}
