// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: iota/grpc/v1/transaction.proto

package transaction

import (
	_ "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/options"
	bcs "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/bcs"
	event "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/event"
	object "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/object"
	signatures "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/signatures"
	types "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A transaction.
type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The digest of this Transaction.
	Digest *types.Digest `protobuf:"bytes,1,opt,name=digest,proto3,oneof" json:"digest,omitempty"`
	// This Transaction serialized as BCS.
	Bcs           *bcs.BcsData `protobuf:"bytes,2,opt,name=bcs,proto3,oneof" json:"bcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_iota_grpc_v1_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetDigest() *types.Digest {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *Transaction) GetBcs() *bcs.BcsData {
	if x != nil {
		return x.Bcs
	}
	return nil
}

// The effects of executing a transaction.
type TransactionEffects struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The digest of this TransactionEffects.
	Digest *types.Digest `protobuf:"bytes,1,opt,name=digest,proto3,oneof" json:"digest,omitempty"`
	// This TransactionEffects serialized as BCS.
	Bcs           *bcs.BcsData `protobuf:"bytes,2,opt,name=bcs,proto3,oneof" json:"bcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionEffects) Reset() {
	*x = TransactionEffects{}
	mi := &file_iota_grpc_v1_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionEffects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionEffects) ProtoMessage() {}

func (x *TransactionEffects) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionEffects.ProtoReflect.Descriptor instead.
func (*TransactionEffects) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionEffects) GetDigest() *types.Digest {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *TransactionEffects) GetBcs() *bcs.BcsData {
	if x != nil {
		return x.Bcs
	}
	return nil
}

// iota.grpc.v1.event.Events emitted during the successful execution of a transaction.
type TransactionEvents struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The digest of this TransactionEvents.
	Digest *types.Digest `protobuf:"bytes,1,opt,name=digest,proto3,oneof" json:"digest,omitempty"`
	// List of events emitted by a transaction.
	Events        *event.Events `protobuf:"bytes,2,opt,name=events,proto3,oneof" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionEvents) Reset() {
	*x = TransactionEvents{}
	mi := &file_iota_grpc_v1_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionEvents) ProtoMessage() {}

func (x *TransactionEvents) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionEvents.ProtoReflect.Descriptor instead.
func (*TransactionEvents) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionEvents) GetDigest() *types.Digest {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *TransactionEvents) GetEvents() *event.Events {
	if x != nil {
		return x.Events
	}
	return nil
}

// A transaction that has been executed, along with its signatures, effects, events and objects.
type ExecutedTransaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The transaction itself.
	Transaction *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3,oneof" json:"transaction,omitempty"`
	// List of user signatures that are used to authorize the
	// execution of this transaction.
	Signatures *signatures.UserSignatures `protobuf:"bytes,2,opt,name=signatures,proto3,oneof" json:"signatures,omitempty"`
	// The `TransactionEffects` for this transaction.
	Effects *TransactionEffects `protobuf:"bytes,3,opt,name=effects,proto3,oneof" json:"effects,omitempty"`
	// The `TransactionEvents` for this transaction.
	//
	// This field might be empty, even if it was explicitly requested, if the
	// transaction didn't produce any events.
	// `iota.types.TransactionEffects.events_digest` is populated if the
	// transaction produced any events.
	Events *TransactionEvents `protobuf:"bytes,4,opt,name=events,proto3,oneof" json:"events,omitempty"`
	// The sequence number for the checkpoint that includes this transaction.
	Checkpoint *uint64 `protobuf:"varint,5,opt,name=checkpoint,proto3,oneof" json:"checkpoint,omitempty"`
	// The Unix timestamp of the checkpoint that includes this transaction.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`
	// Set of input objects used by this transaction.
	InputObjects *object.Objects `protobuf:"bytes,7,opt,name=input_objects,json=inputObjects,proto3,oneof" json:"input_objects,omitempty"`
	// Set of output objects produced by this transaction.
	OutputObjects *object.Objects `protobuf:"bytes,8,opt,name=output_objects,json=outputObjects,proto3,oneof" json:"output_objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutedTransaction) Reset() {
	*x = ExecutedTransaction{}
	mi := &file_iota_grpc_v1_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutedTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutedTransaction) ProtoMessage() {}

func (x *ExecutedTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutedTransaction.ProtoReflect.Descriptor instead.
func (*ExecutedTransaction) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *ExecutedTransaction) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *ExecutedTransaction) GetSignatures() *signatures.UserSignatures {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *ExecutedTransaction) GetEffects() *TransactionEffects {
	if x != nil {
		return x.Effects
	}
	return nil
}

func (x *ExecutedTransaction) GetEvents() *TransactionEvents {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ExecutedTransaction) GetCheckpoint() uint64 {
	if x != nil && x.Checkpoint != nil {
		return *x.Checkpoint
	}
	return 0
}

func (x *ExecutedTransaction) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ExecutedTransaction) GetInputObjects() *object.Objects {
	if x != nil {
		return x.InputObjects
	}
	return nil
}

func (x *ExecutedTransaction) GetOutputObjects() *object.Objects {
	if x != nil {
		return x.OutputObjects
	}
	return nil
}

type ExecutedTransactions struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ExecutedTransactions []*ExecutedTransaction `protobuf:"bytes,1,rep,name=executed_transactions,json=executedTransactions,proto3" json:"executed_transactions,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ExecutedTransactions) Reset() {
	*x = ExecutedTransactions{}
	mi := &file_iota_grpc_v1_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutedTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutedTransactions) ProtoMessage() {}

func (x *ExecutedTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutedTransactions.ProtoReflect.Descriptor instead.
func (*ExecutedTransactions) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *ExecutedTransactions) GetExecutedTransactions() []*ExecutedTransaction {
	if x != nil {
		return x.ExecutedTransactions
	}
	return nil
}

var File_iota_grpc_v1_transaction_proto protoreflect.FileDescriptor

const file_iota_grpc_v1_transaction_proto_rawDesc = "" +
	"\n" +
	"\x1eiota/grpc/v1/transaction.proto\x12\x18iota.grpc.v1.transaction\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17iota/grpc/options.proto\x1a\x16iota/grpc/v1/bcs.proto\x1a\x18iota/grpc/v1/event.proto\x1a\x19iota/grpc/v1/object.proto\x1a\x1diota/grpc/v1/signatures.proto\x1a\x18iota/grpc/v1/types.proto\"\x95\x01\n" +
	"\vTransaction\x127\n" +
	"\x06digest\x18\x01 \x01(\v2\x1a.iota.grpc.v1.types.DigestH\x00R\x06digest\x88\x01\x01\x120\n" +
	"\x03bcs\x18\x02 \x01(\v2\x19.iota.grpc.v1.bcs.BcsDataH\x01R\x03bcs\x88\x01\x01:\b\x82\xb5\x18\x04withB\t\n" +
	"\a_digestB\x06\n" +
	"\x04_bcs\"\x9c\x01\n" +
	"\x12TransactionEffects\x127\n" +
	"\x06digest\x18\x01 \x01(\v2\x1a.iota.grpc.v1.types.DigestH\x00R\x06digest\x88\x01\x01\x120\n" +
	"\x03bcs\x18\x02 \x01(\v2\x19.iota.grpc.v1.bcs.BcsDataH\x01R\x03bcs\x88\x01\x01:\b\x82\xb5\x18\x04withB\t\n" +
	"\a_digestB\x06\n" +
	"\x04_bcs\"\xa5\x01\n" +
	"\x11TransactionEvents\x127\n" +
	"\x06digest\x18\x01 \x01(\v2\x1a.iota.grpc.v1.types.DigestH\x00R\x06digest\x88\x01\x01\x127\n" +
	"\x06events\x18\x02 \x01(\v2\x1a.iota.grpc.v1.event.EventsH\x01R\x06events\x88\x01\x01:\b\x82\xb5\x18\x04withB\t\n" +
	"\a_digestB\t\n" +
	"\a_events\"\xc0\x05\n" +
	"\x13ExecutedTransaction\x12L\n" +
	"\vtransaction\x18\x01 \x01(\v2%.iota.grpc.v1.transaction.TransactionH\x00R\vtransaction\x88\x01\x01\x12L\n" +
	"\n" +
	"signatures\x18\x02 \x01(\v2'.iota.grpc.v1.signatures.UserSignaturesH\x01R\n" +
	"signatures\x88\x01\x01\x12K\n" +
	"\aeffects\x18\x03 \x01(\v2,.iota.grpc.v1.transaction.TransactionEffectsH\x02R\aeffects\x88\x01\x01\x12H\n" +
	"\x06events\x18\x04 \x01(\v2+.iota.grpc.v1.transaction.TransactionEventsH\x03R\x06events\x88\x01\x01\x12#\n" +
	"\n" +
	"checkpoint\x18\x05 \x01(\x04H\x04R\n" +
	"checkpoint\x88\x01\x01\x12=\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x05R\ttimestamp\x88\x01\x01\x12F\n" +
	"\rinput_objects\x18\a \x01(\v2\x1c.iota.grpc.v1.object.ObjectsH\x06R\finputObjects\x88\x01\x01\x12H\n" +
	"\x0eoutput_objects\x18\b \x01(\v2\x1c.iota.grpc.v1.object.ObjectsH\aR\routputObjects\x88\x01\x01:\b\x82\xb5\x18\x04withB\x0e\n" +
	"\f_transactionB\r\n" +
	"\v_signaturesB\n" +
	"\n" +
	"\b_effectsB\t\n" +
	"\a_eventsB\r\n" +
	"\v_checkpointB\f\n" +
	"\n" +
	"_timestampB\x10\n" +
	"\x0e_input_objectsB\x11\n" +
	"\x0f_output_objects\"\x84\x01\n" +
	"\x14ExecutedTransactions\x12b\n" +
	"\x15executed_transactions\x18\x01 \x03(\v2-.iota.grpc.v1.transaction.ExecutedTransactionR\x14executedTransactions:\b\x82\xb5\x18\x04withb\x06proto3"

var (
	file_iota_grpc_v1_transaction_proto_rawDescOnce sync.Once
	file_iota_grpc_v1_transaction_proto_rawDescData []byte
)

func file_iota_grpc_v1_transaction_proto_rawDescGZIP() []byte {
	file_iota_grpc_v1_transaction_proto_rawDescOnce.Do(func() {
		file_iota_grpc_v1_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_transaction_proto_rawDesc), len(file_iota_grpc_v1_transaction_proto_rawDesc)))
	})
	return file_iota_grpc_v1_transaction_proto_rawDescData
}

var file_iota_grpc_v1_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_iota_grpc_v1_transaction_proto_goTypes = []any{
	(*Transaction)(nil),               // 0: iota.grpc.v1.transaction.Transaction
	(*TransactionEffects)(nil),        // 1: iota.grpc.v1.transaction.TransactionEffects
	(*TransactionEvents)(nil),         // 2: iota.grpc.v1.transaction.TransactionEvents
	(*ExecutedTransaction)(nil),       // 3: iota.grpc.v1.transaction.ExecutedTransaction
	(*ExecutedTransactions)(nil),      // 4: iota.grpc.v1.transaction.ExecutedTransactions
	(*types.Digest)(nil),              // 5: iota.grpc.v1.types.Digest
	(*bcs.BcsData)(nil),               // 6: iota.grpc.v1.bcs.BcsData
	(*event.Events)(nil),              // 7: iota.grpc.v1.event.Events
	(*signatures.UserSignatures)(nil), // 8: iota.grpc.v1.signatures.UserSignatures
	(*timestamppb.Timestamp)(nil),     // 9: google.protobuf.Timestamp
	(*object.Objects)(nil),            // 10: iota.grpc.v1.object.Objects
}
var file_iota_grpc_v1_transaction_proto_depIdxs = []int32{
	5,  // 0: iota.grpc.v1.transaction.Transaction.digest:type_name -> iota.grpc.v1.types.Digest
	6,  // 1: iota.grpc.v1.transaction.Transaction.bcs:type_name -> iota.grpc.v1.bcs.BcsData
	5,  // 2: iota.grpc.v1.transaction.TransactionEffects.digest:type_name -> iota.grpc.v1.types.Digest
	6,  // 3: iota.grpc.v1.transaction.TransactionEffects.bcs:type_name -> iota.grpc.v1.bcs.BcsData
	5,  // 4: iota.grpc.v1.transaction.TransactionEvents.digest:type_name -> iota.grpc.v1.types.Digest
	7,  // 5: iota.grpc.v1.transaction.TransactionEvents.events:type_name -> iota.grpc.v1.event.Events
	0,  // 6: iota.grpc.v1.transaction.ExecutedTransaction.transaction:type_name -> iota.grpc.v1.transaction.Transaction
	8,  // 7: iota.grpc.v1.transaction.ExecutedTransaction.signatures:type_name -> iota.grpc.v1.signatures.UserSignatures
	1,  // 8: iota.grpc.v1.transaction.ExecutedTransaction.effects:type_name -> iota.grpc.v1.transaction.TransactionEffects
	2,  // 9: iota.grpc.v1.transaction.ExecutedTransaction.events:type_name -> iota.grpc.v1.transaction.TransactionEvents
	9,  // 10: iota.grpc.v1.transaction.ExecutedTransaction.timestamp:type_name -> google.protobuf.Timestamp
	10, // 11: iota.grpc.v1.transaction.ExecutedTransaction.input_objects:type_name -> iota.grpc.v1.object.Objects
	10, // 12: iota.grpc.v1.transaction.ExecutedTransaction.output_objects:type_name -> iota.grpc.v1.object.Objects
	3,  // 13: iota.grpc.v1.transaction.ExecutedTransactions.executed_transactions:type_name -> iota.grpc.v1.transaction.ExecutedTransaction
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_iota_grpc_v1_transaction_proto_init() }
func file_iota_grpc_v1_transaction_proto_init() {
	if File_iota_grpc_v1_transaction_proto != nil {
		return
	}
	file_iota_grpc_v1_transaction_proto_msgTypes[0].OneofWrappers = []any{}
	file_iota_grpc_v1_transaction_proto_msgTypes[1].OneofWrappers = []any{}
	file_iota_grpc_v1_transaction_proto_msgTypes[2].OneofWrappers = []any{}
	file_iota_grpc_v1_transaction_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_transaction_proto_rawDesc), len(file_iota_grpc_v1_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_iota_grpc_v1_transaction_proto_goTypes,
		DependencyIndexes: file_iota_grpc_v1_transaction_proto_depIdxs,
		MessageInfos:      file_iota_grpc_v1_transaction_proto_msgTypes,
	}.Build()
	File_iota_grpc_v1_transaction_proto = out.File
	file_iota_grpc_v1_transaction_proto_goTypes = nil
	file_iota_grpc_v1_transaction_proto_depIdxs = nil
}
