// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: iota/grpc/v1/signatures.proto

package signatures

import (
	_ "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/options"
	bcs "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/bcs"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A signature from a user.
type UserSignature struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This signature serialized as as BCS.
	//
	// When provided as input this will support both the form that is length
	// prefixed as well as not length prefixed.
	Bcs           *bcs.BcsData `protobuf:"bytes,1,opt,name=bcs,proto3,oneof" json:"bcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSignature) Reset() {
	*x = UserSignature{}
	mi := &file_iota_grpc_v1_signatures_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSignature) ProtoMessage() {}

func (x *UserSignature) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_signatures_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSignature.ProtoReflect.Descriptor instead.
func (*UserSignature) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_signatures_proto_rawDescGZIP(), []int{0}
}

func (x *UserSignature) GetBcs() *bcs.BcsData {
	if x != nil {
		return x.Bcs
	}
	return nil
}

// A list of user signatures.
type UserSignatures struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signatures    []*UserSignature       `protobuf:"bytes,1,rep,name=signatures,proto3" json:"signatures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSignatures) Reset() {
	*x = UserSignatures{}
	mi := &file_iota_grpc_v1_signatures_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSignatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSignatures) ProtoMessage() {}

func (x *UserSignatures) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_signatures_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSignatures.ProtoReflect.Descriptor instead.
func (*UserSignatures) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_signatures_proto_rawDescGZIP(), []int{1}
}

func (x *UserSignatures) GetSignatures() []*UserSignature {
	if x != nil {
		return x.Signatures
	}
	return nil
}

// / An aggregated signature from multiple validators.
type ValidatorAggregatedSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bcs           *bcs.BcsData           `protobuf:"bytes,1,opt,name=bcs,proto3,oneof" json:"bcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatorAggregatedSignature) Reset() {
	*x = ValidatorAggregatedSignature{}
	mi := &file_iota_grpc_v1_signatures_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorAggregatedSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorAggregatedSignature) ProtoMessage() {}

func (x *ValidatorAggregatedSignature) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_signatures_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorAggregatedSignature.ProtoReflect.Descriptor instead.
func (*ValidatorAggregatedSignature) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_signatures_proto_rawDescGZIP(), []int{2}
}

func (x *ValidatorAggregatedSignature) GetBcs() *bcs.BcsData {
	if x != nil {
		return x.Bcs
	}
	return nil
}

var File_iota_grpc_v1_signatures_proto protoreflect.FileDescriptor

const file_iota_grpc_v1_signatures_proto_rawDesc = "" +
	"\n" +
	"\x1diota/grpc/v1/signatures.proto\x12\x17iota.grpc.v1.signatures\x1a\x17iota/grpc/options.proto\x1a\x16iota/grpc/v1/bcs.proto\"S\n" +
	"\rUserSignature\x120\n" +
	"\x03bcs\x18\x01 \x01(\v2\x19.iota.grpc.v1.bcs.BcsDataH\x00R\x03bcs\x88\x01\x01:\b\x82\xb5\x18\x04withB\x06\n" +
	"\x04_bcs\"f\n" +
	"\x0eUserSignatures\x12F\n" +
	"\n" +
	"signatures\x18\x01 \x03(\v2&.iota.grpc.v1.signatures.UserSignatureR\n" +
	"signatures:\f\x82\xb5\x18\x04with\x90\xb5\x18\x01\"b\n" +
	"\x1cValidatorAggregatedSignature\x120\n" +
	"\x03bcs\x18\x01 \x01(\v2\x19.iota.grpc.v1.bcs.BcsDataH\x00R\x03bcs\x88\x01\x01:\b\x82\xb5\x18\x04withB\x06\n" +
	"\x04_bcsb\x06proto3"

var (
	file_iota_grpc_v1_signatures_proto_rawDescOnce sync.Once
	file_iota_grpc_v1_signatures_proto_rawDescData []byte
)

func file_iota_grpc_v1_signatures_proto_rawDescGZIP() []byte {
	file_iota_grpc_v1_signatures_proto_rawDescOnce.Do(func() {
		file_iota_grpc_v1_signatures_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_signatures_proto_rawDesc), len(file_iota_grpc_v1_signatures_proto_rawDesc)))
	})
	return file_iota_grpc_v1_signatures_proto_rawDescData
}

var file_iota_grpc_v1_signatures_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_iota_grpc_v1_signatures_proto_goTypes = []any{
	(*UserSignature)(nil),                // 0: iota.grpc.v1.signatures.UserSignature
	(*UserSignatures)(nil),               // 1: iota.grpc.v1.signatures.UserSignatures
	(*ValidatorAggregatedSignature)(nil), // 2: iota.grpc.v1.signatures.ValidatorAggregatedSignature
	(*bcs.BcsData)(nil),                  // 3: iota.grpc.v1.bcs.BcsData
}
var file_iota_grpc_v1_signatures_proto_depIdxs = []int32{
	3, // 0: iota.grpc.v1.signatures.UserSignature.bcs:type_name -> iota.grpc.v1.bcs.BcsData
	0, // 1: iota.grpc.v1.signatures.UserSignatures.signatures:type_name -> iota.grpc.v1.signatures.UserSignature
	3, // 2: iota.grpc.v1.signatures.ValidatorAggregatedSignature.bcs:type_name -> iota.grpc.v1.bcs.BcsData
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_iota_grpc_v1_signatures_proto_init() }
func file_iota_grpc_v1_signatures_proto_init() {
	if File_iota_grpc_v1_signatures_proto != nil {
		return
	}
	file_iota_grpc_v1_signatures_proto_msgTypes[0].OneofWrappers = []any{}
	file_iota_grpc_v1_signatures_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_signatures_proto_rawDesc), len(file_iota_grpc_v1_signatures_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_iota_grpc_v1_signatures_proto_goTypes,
		DependencyIndexes: file_iota_grpc_v1_signatures_proto_depIdxs,
		MessageInfos:      file_iota_grpc_v1_signatures_proto_msgTypes,
	}.Build()
	File_iota_grpc_v1_signatures_proto = out.File
	file_iota_grpc_v1_signatures_proto_goTypes = nil
	file_iota_grpc_v1_signatures_proto_depIdxs = nil
}
