// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: iota/grpc/options.proto

package options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_iota_grpc_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50000,
		Name:          "iota.grpc.message_accessors",
		Tag:           "bytes,50000,opt,name=message_accessors",
		Filename:      "iota/grpc/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50002,
		Name:          "iota.grpc.field_mask_transparent",
		Tag:           "varint,50002,opt,name=field_mask_transparent",
		Filename:      "iota/grpc/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "iota.grpc.field_accessors",
		Tag:           "bytes,50001,opt,name=field_accessors",
		Filename:      "iota/grpc/options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// Default accessor types to generate for all fields in this message.
	// Valid values: getter, getter_opt, set, with, mut, mut_opt, all
	// Example: "with" generates with_field() for all fields
	// Field-level field_accessors annotations override this default.
	//
	// optional string message_accessors = 50000;
	E_MessageAccessors = &file_iota_grpc_options_proto_extTypes[0]
	// When true, parent fields pointing to this message will skip this wrapper
	// layer in field_info (read_mask paths) and FieldPathBuilders. The wrapper
	// must contain exactly one repeated or map field.
	//
	// optional bool field_mask_transparent = 50002;
	E_FieldMaskTransparent = &file_iota_grpc_options_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// Comma-separated list of accessor types to generate for this field.
	// Valid values: getter, getter_opt, set, with, mut, mut_opt, all
	// Example: "set,with" generates set_field() and with_field()
	// Overrides message-level message_accessors option.
	//
	// optional string field_accessors = 50001;
	E_FieldAccessors = &file_iota_grpc_options_proto_extTypes[2]
)

var File_iota_grpc_options_proto protoreflect.FileDescriptor

const file_iota_grpc_options_proto_rawDesc = "" +
	"\n" +
	"\x17iota/grpc/options.proto\x12\tiota.grpc\x1a google/protobuf/descriptor.proto:Q\n" +
	"\x11message_accessors\x12\x1f.google.protobuf.MessageOptions\x18І\x03 \x01(\tR\x10messageAccessors\x88\x01\x01:Z\n" +
	"\x16field_mask_transparent\x12\x1f.google.protobuf.MessageOptions\x18҆\x03 \x01(\bR\x14fieldMaskTransparent\x88\x01\x01:K\n" +
	"\x0ffield_accessors\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\tR\x0efieldAccessors\x88\x01\x01b\x06proto3"

var file_iota_grpc_options_proto_goTypes = []any{
	(*descriptorpb.MessageOptions)(nil), // 0: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 1: google.protobuf.FieldOptions
}
var file_iota_grpc_options_proto_depIdxs = []int32{
	0, // 0: iota.grpc.message_accessors:extendee -> google.protobuf.MessageOptions
	0, // 1: iota.grpc.field_mask_transparent:extendee -> google.protobuf.MessageOptions
	1, // 2: iota.grpc.field_accessors:extendee -> google.protobuf.FieldOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_iota_grpc_options_proto_init() }
func file_iota_grpc_options_proto_init() {
	if File_iota_grpc_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iota_grpc_options_proto_rawDesc), len(file_iota_grpc_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_iota_grpc_options_proto_goTypes,
		DependencyIndexes: file_iota_grpc_options_proto_depIdxs,
		ExtensionInfos:    file_iota_grpc_options_proto_extTypes,
	}.Build()
	File_iota_grpc_options_proto = out.File
	file_iota_grpc_options_proto_goTypes = nil
	file_iota_grpc_options_proto_depIdxs = nil
}
