// Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: iota/grpc/v1/types.proto

package types

import (
	_ "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 32-byte address type for IOTA account addresses.
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_iota_grpc_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

// 32-byte identifier for on-chain objects and packages.
type ObjectId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      []byte                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectId) Reset() {
	*x = ObjectId{}
	mi := &file_iota_grpc_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectId) ProtoMessage() {}

func (x *ObjectId) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectId.ProtoReflect.Descriptor instead.
func (*ObjectId) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectId) GetObjectId() []byte {
	if x != nil {
		return x.ObjectId
	}
	return nil
}

// Generic 32-byte digest (used for transactions, objects, etc.)
type Digest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        []byte                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Digest) Reset() {
	*x = Digest{}
	mi := &file_iota_grpc_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Digest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Digest) ProtoMessage() {}

func (x *Digest) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Digest.ProtoReflect.Descriptor instead.
func (*Digest) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *Digest) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

// Reference to an object.
type ObjectReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The object id of this object.
	ObjectId *ObjectId `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3,oneof" json:"object_id,omitempty"`
	// The version of this object.
	Version *uint64 `protobuf:"varint,2,opt,name=version,proto3,oneof" json:"version,omitempty"`
	// The digest of this object.
	Digest        *Digest `protobuf:"bytes,3,opt,name=digest,proto3,oneof" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectReference) Reset() {
	*x = ObjectReference{}
	mi := &file_iota_grpc_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectReference) ProtoMessage() {}

func (x *ObjectReference) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectReference.ProtoReflect.Descriptor instead.
func (*ObjectReference) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *ObjectReference) GetObjectId() *ObjectId {
	if x != nil {
		return x.ObjectId
	}
	return nil
}

func (x *ObjectReference) GetVersion() uint64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *ObjectReference) GetDigest() *Digest {
	if x != nil {
		return x.Digest
	}
	return nil
}

type TypeTagVector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InnerType     *TypeTag               `protobuf:"bytes,1,opt,name=inner_type,json=innerType,proto3" json:"inner_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeTagVector) Reset() {
	*x = TypeTagVector{}
	mi := &file_iota_grpc_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeTagVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeTagVector) ProtoMessage() {}

func (x *TypeTagVector) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeTagVector.ProtoReflect.Descriptor instead.
func (*TypeTagVector) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *TypeTagVector) GetInnerType() *TypeTag {
	if x != nil {
		return x.InnerType
	}
	return nil
}

type TypeTagStruct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StructTag     string                 `protobuf:"bytes,1,opt,name=struct_tag,json=structTag,proto3" json:"struct_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeTagStruct) Reset() {
	*x = TypeTagStruct{}
	mi := &file_iota_grpc_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeTagStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeTagStruct) ProtoMessage() {}

func (x *TypeTagStruct) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeTagStruct.ProtoReflect.Descriptor instead.
func (*TypeTagStruct) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *TypeTagStruct) GetStructTag() string {
	if x != nil {
		return x.StructTag
	}
	return ""
}

type TypeTag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to TypeTag:
	//
	//	*TypeTag_BoolTag
	//	*TypeTag_U8Tag
	//	*TypeTag_U16Tag
	//	*TypeTag_U32Tag
	//	*TypeTag_U64Tag
	//	*TypeTag_U128Tag
	//	*TypeTag_U256Tag
	//	*TypeTag_AddressTag
	//	*TypeTag_SignerTag
	//	*TypeTag_VectorTag
	//	*TypeTag_StructTag
	TypeTag       isTypeTag_TypeTag `protobuf_oneof:"type_tag"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeTag) Reset() {
	*x = TypeTag{}
	mi := &file_iota_grpc_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeTag) ProtoMessage() {}

func (x *TypeTag) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeTag.ProtoReflect.Descriptor instead.
func (*TypeTag) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *TypeTag) GetTypeTag() isTypeTag_TypeTag {
	if x != nil {
		return x.TypeTag
	}
	return nil
}

func (x *TypeTag) GetBoolTag() bool {
	if x != nil {
		if x, ok := x.TypeTag.(*TypeTag_BoolTag); ok {
			return x.BoolTag
		}
	}
	return false
}

func (x *TypeTag) GetU8Tag() bool {
	if x != nil {
		if x, ok := x.TypeTag.(*TypeTag_U8Tag); ok {
			return x.U8Tag
		}
	}
	return false
}

func (x *TypeTag) GetU16Tag() bool {
	if x != nil {
		if x, ok := x.TypeTag.(*TypeTag_U16Tag); ok {
			return x.U16Tag
		}
	}
	return false
}

func (x *TypeTag) GetU32Tag() bool {
	if x != nil {
		if x, ok := x.TypeTag.(*TypeTag_U32Tag); ok {
			return x.U32Tag
		}
	}
	return false
}

func (x *TypeTag) GetU64Tag() bool {
	if x != nil {
		if x, ok := x.TypeTag.(*TypeTag_U64Tag); ok {
			return x.U64Tag
		}
	}
	return false
}

func (x *TypeTag) GetU128Tag() bool {
	if x != nil {
		if x, ok := x.TypeTag.(*TypeTag_U128Tag); ok {
			return x.U128Tag
		}
	}
	return false
}

func (x *TypeTag) GetU256Tag() bool {
	if x != nil {
		if x, ok := x.TypeTag.(*TypeTag_U256Tag); ok {
			return x.U256Tag
		}
	}
	return false
}

func (x *TypeTag) GetAddressTag() bool {
	if x != nil {
		if x, ok := x.TypeTag.(*TypeTag_AddressTag); ok {
			return x.AddressTag
		}
	}
	return false
}

func (x *TypeTag) GetSignerTag() bool {
	if x != nil {
		if x, ok := x.TypeTag.(*TypeTag_SignerTag); ok {
			return x.SignerTag
		}
	}
	return false
}

func (x *TypeTag) GetVectorTag() *TypeTagVector {
	if x != nil {
		if x, ok := x.TypeTag.(*TypeTag_VectorTag); ok {
			return x.VectorTag
		}
	}
	return nil
}

func (x *TypeTag) GetStructTag() *TypeTagStruct {
	if x != nil {
		if x, ok := x.TypeTag.(*TypeTag_StructTag); ok {
			return x.StructTag
		}
	}
	return nil
}

type isTypeTag_TypeTag interface {
	isTypeTag_TypeTag()
}

type TypeTag_BoolTag struct {
	BoolTag bool `protobuf:"varint,1,opt,name=bool_tag,json=boolTag,proto3,oneof"`
}

type TypeTag_U8Tag struct {
	U8Tag bool `protobuf:"varint,2,opt,name=u8_tag,json=u8Tag,proto3,oneof"`
}

type TypeTag_U16Tag struct {
	U16Tag bool `protobuf:"varint,3,opt,name=u16_tag,json=u16Tag,proto3,oneof"`
}

type TypeTag_U32Tag struct {
	U32Tag bool `protobuf:"varint,4,opt,name=u32_tag,json=u32Tag,proto3,oneof"`
}

type TypeTag_U64Tag struct {
	U64Tag bool `protobuf:"varint,5,opt,name=u64_tag,json=u64Tag,proto3,oneof"`
}

type TypeTag_U128Tag struct {
	U128Tag bool `protobuf:"varint,6,opt,name=u128_tag,json=u128Tag,proto3,oneof"`
}

type TypeTag_U256Tag struct {
	U256Tag bool `protobuf:"varint,7,opt,name=u256_tag,json=u256Tag,proto3,oneof"`
}

type TypeTag_AddressTag struct {
	AddressTag bool `protobuf:"varint,8,opt,name=address_tag,json=addressTag,proto3,oneof"`
}

type TypeTag_SignerTag struct {
	SignerTag bool `protobuf:"varint,9,opt,name=signer_tag,json=signerTag,proto3,oneof"`
}

type TypeTag_VectorTag struct {
	VectorTag *TypeTagVector `protobuf:"bytes,10,opt,name=vector_tag,json=vectorTag,proto3,oneof"`
}

type TypeTag_StructTag struct {
	StructTag *TypeTagStruct `protobuf:"bytes,11,opt,name=struct_tag,json=structTag,proto3,oneof"`
}

func (*TypeTag_BoolTag) isTypeTag_TypeTag() {}

func (*TypeTag_U8Tag) isTypeTag_TypeTag() {}

func (*TypeTag_U16Tag) isTypeTag_TypeTag() {}

func (*TypeTag_U32Tag) isTypeTag_TypeTag() {}

func (*TypeTag_U64Tag) isTypeTag_TypeTag() {}

func (*TypeTag_U128Tag) isTypeTag_TypeTag() {}

func (*TypeTag_U256Tag) isTypeTag_TypeTag() {}

func (*TypeTag_AddressTag) isTypeTag_TypeTag() {}

func (*TypeTag_SignerTag) isTypeTag_TypeTag() {}

func (*TypeTag_VectorTag) isTypeTag_TypeTag() {}

func (*TypeTag_StructTag) isTypeTag_TypeTag() {}

type TypeTags struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeTags      []*TypeTag             `protobuf:"bytes,1,rep,name=type_tags,json=typeTags,proto3" json:"type_tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeTags) Reset() {
	*x = TypeTags{}
	mi := &file_iota_grpc_v1_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeTags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeTags) ProtoMessage() {}

func (x *TypeTags) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeTags.ProtoReflect.Descriptor instead.
func (*TypeTags) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *TypeTags) GetTypeTags() []*TypeTag {
	if x != nil {
		return x.TypeTags
	}
	return nil
}

var File_iota_grpc_v1_types_proto protoreflect.FileDescriptor

const file_iota_grpc_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x18iota/grpc/v1/types.proto\x12\x12iota.grpc.v1.types\x1a\x17iota/grpc/options.proto\"-\n" +
	"\aAddress\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress:\b\x82\xb5\x18\x04with\"1\n" +
	"\bObjectId\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\fR\bobjectId:\b\x82\xb5\x18\x04with\"*\n" +
	"\x06Digest\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\fR\x06digest:\b\x82\xb5\x18\x04with\"\xd8\x01\n" +
	"\x0fObjectReference\x12>\n" +
	"\tobject_id\x18\x01 \x01(\v2\x1c.iota.grpc.v1.types.ObjectIdH\x00R\bobjectId\x88\x01\x01\x12\x1d\n" +
	"\aversion\x18\x02 \x01(\x04H\x01R\aversion\x88\x01\x01\x127\n" +
	"\x06digest\x18\x03 \x01(\v2\x1a.iota.grpc.v1.types.DigestH\x02R\x06digest\x88\x01\x01:\b\x82\xb5\x18\x04withB\f\n" +
	"\n" +
	"_object_idB\n" +
	"\n" +
	"\b_versionB\t\n" +
	"\a_digest\"K\n" +
	"\rTypeTagVector\x12:\n" +
	"\n" +
	"inner_type\x18\x01 \x01(\v2\x1b.iota.grpc.v1.types.TypeTagR\tinnerType\".\n" +
	"\rTypeTagStruct\x12\x1d\n" +
	"\n" +
	"struct_tag\x18\x01 \x01(\tR\tstructTag\"\xa2\x03\n" +
	"\aTypeTag\x12\x1b\n" +
	"\bbool_tag\x18\x01 \x01(\bH\x00R\aboolTag\x12\x17\n" +
	"\x06u8_tag\x18\x02 \x01(\bH\x00R\x05u8Tag\x12\x19\n" +
	"\au16_tag\x18\x03 \x01(\bH\x00R\x06u16Tag\x12\x19\n" +
	"\au32_tag\x18\x04 \x01(\bH\x00R\x06u32Tag\x12\x19\n" +
	"\au64_tag\x18\x05 \x01(\bH\x00R\x06u64Tag\x12\x1b\n" +
	"\bu128_tag\x18\x06 \x01(\bH\x00R\au128Tag\x12\x1b\n" +
	"\bu256_tag\x18\a \x01(\bH\x00R\au256Tag\x12!\n" +
	"\vaddress_tag\x18\b \x01(\bH\x00R\n" +
	"addressTag\x12\x1f\n" +
	"\n" +
	"signer_tag\x18\t \x01(\bH\x00R\tsignerTag\x12B\n" +
	"\n" +
	"vector_tag\x18\n" +
	" \x01(\v2!.iota.grpc.v1.types.TypeTagVectorH\x00R\tvectorTag\x12B\n" +
	"\n" +
	"struct_tag\x18\v \x01(\v2!.iota.grpc.v1.types.TypeTagStructH\x00R\tstructTagB\n" +
	"\n" +
	"\btype_tag\"D\n" +
	"\bTypeTags\x128\n" +
	"\ttype_tags\x18\x01 \x03(\v2\x1b.iota.grpc.v1.types.TypeTagR\btypeTagsb\x06proto3"

var (
	file_iota_grpc_v1_types_proto_rawDescOnce sync.Once
	file_iota_grpc_v1_types_proto_rawDescData []byte
)

func file_iota_grpc_v1_types_proto_rawDescGZIP() []byte {
	file_iota_grpc_v1_types_proto_rawDescOnce.Do(func() {
		file_iota_grpc_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_types_proto_rawDesc), len(file_iota_grpc_v1_types_proto_rawDesc)))
	})
	return file_iota_grpc_v1_types_proto_rawDescData
}

var file_iota_grpc_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_iota_grpc_v1_types_proto_goTypes = []any{
	(*Address)(nil),         // 0: iota.grpc.v1.types.Address
	(*ObjectId)(nil),        // 1: iota.grpc.v1.types.ObjectId
	(*Digest)(nil),          // 2: iota.grpc.v1.types.Digest
	(*ObjectReference)(nil), // 3: iota.grpc.v1.types.ObjectReference
	(*TypeTagVector)(nil),   // 4: iota.grpc.v1.types.TypeTagVector
	(*TypeTagStruct)(nil),   // 5: iota.grpc.v1.types.TypeTagStruct
	(*TypeTag)(nil),         // 6: iota.grpc.v1.types.TypeTag
	(*TypeTags)(nil),        // 7: iota.grpc.v1.types.TypeTags
}
var file_iota_grpc_v1_types_proto_depIdxs = []int32{
	1, // 0: iota.grpc.v1.types.ObjectReference.object_id:type_name -> iota.grpc.v1.types.ObjectId
	2, // 1: iota.grpc.v1.types.ObjectReference.digest:type_name -> iota.grpc.v1.types.Digest
	6, // 2: iota.grpc.v1.types.TypeTagVector.inner_type:type_name -> iota.grpc.v1.types.TypeTag
	4, // 3: iota.grpc.v1.types.TypeTag.vector_tag:type_name -> iota.grpc.v1.types.TypeTagVector
	5, // 4: iota.grpc.v1.types.TypeTag.struct_tag:type_name -> iota.grpc.v1.types.TypeTagStruct
	6, // 5: iota.grpc.v1.types.TypeTags.type_tags:type_name -> iota.grpc.v1.types.TypeTag
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_iota_grpc_v1_types_proto_init() }
func file_iota_grpc_v1_types_proto_init() {
	if File_iota_grpc_v1_types_proto != nil {
		return
	}
	file_iota_grpc_v1_types_proto_msgTypes[3].OneofWrappers = []any{}
	file_iota_grpc_v1_types_proto_msgTypes[6].OneofWrappers = []any{
		(*TypeTag_BoolTag)(nil),
		(*TypeTag_U8Tag)(nil),
		(*TypeTag_U16Tag)(nil),
		(*TypeTag_U32Tag)(nil),
		(*TypeTag_U64Tag)(nil),
		(*TypeTag_U128Tag)(nil),
		(*TypeTag_U256Tag)(nil),
		(*TypeTag_AddressTag)(nil),
		(*TypeTag_SignerTag)(nil),
		(*TypeTag_VectorTag)(nil),
		(*TypeTag_StructTag)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_types_proto_rawDesc), len(file_iota_grpc_v1_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_iota_grpc_v1_types_proto_goTypes,
		DependencyIndexes: file_iota_grpc_v1_types_proto_depIdxs,
		MessageInfos:      file_iota_grpc_v1_types_proto_msgTypes,
	}.Build()
	File_iota_grpc_v1_types_proto = out.File
	file_iota_grpc_v1_types_proto_goTypes = nil
	file_iota_grpc_v1_types_proto_depIdxs = nil
}
