// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2026 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: iota/grpc/v1/move_package_service.proto

package move_package_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MovePackageService_ListPackageVersions_FullMethodName = "/iota.grpc.v1.move_package_service.MovePackageService/ListPackageVersions"
)

// MovePackageServiceClient is the client API for MovePackageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MovePackageServiceClient interface {
	ListPackageVersions(ctx context.Context, in *ListPackageVersionsRequest, opts ...grpc.CallOption) (*ListPackageVersionsResponse, error)
}

type movePackageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMovePackageServiceClient(cc grpc.ClientConnInterface) MovePackageServiceClient {
	return &movePackageServiceClient{cc}
}

func (c *movePackageServiceClient) ListPackageVersions(ctx context.Context, in *ListPackageVersionsRequest, opts ...grpc.CallOption) (*ListPackageVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPackageVersionsResponse)
	err := c.cc.Invoke(ctx, MovePackageService_ListPackageVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MovePackageServiceServer is the server API for MovePackageService service.
// All implementations must embed UnimplementedMovePackageServiceServer
// for forward compatibility.
type MovePackageServiceServer interface {
	ListPackageVersions(context.Context, *ListPackageVersionsRequest) (*ListPackageVersionsResponse, error)
	mustEmbedUnimplementedMovePackageServiceServer()
}

// UnimplementedMovePackageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMovePackageServiceServer struct{}

func (UnimplementedMovePackageServiceServer) ListPackageVersions(context.Context, *ListPackageVersionsRequest) (*ListPackageVersionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPackageVersions not implemented")
}
func (UnimplementedMovePackageServiceServer) mustEmbedUnimplementedMovePackageServiceServer() {}
func (UnimplementedMovePackageServiceServer) testEmbeddedByValue()                            {}

// UnsafeMovePackageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MovePackageServiceServer will
// result in compilation errors.
type UnsafeMovePackageServiceServer interface {
	mustEmbedUnimplementedMovePackageServiceServer()
}

func RegisterMovePackageServiceServer(s grpc.ServiceRegistrar, srv MovePackageServiceServer) {
	// If the following call panics, it indicates UnimplementedMovePackageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MovePackageService_ServiceDesc, srv)
}

func _MovePackageService_ListPackageVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPackageVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovePackageServiceServer).ListPackageVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovePackageService_ListPackageVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovePackageServiceServer).ListPackageVersions(ctx, req.(*ListPackageVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MovePackageService_ServiceDesc is the grpc.ServiceDesc for MovePackageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MovePackageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iota.grpc.v1.move_package_service.MovePackageService",
	HandlerType: (*MovePackageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPackageVersions",
			Handler:    _MovePackageService_ListPackageVersions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iota/grpc/v1/move_package_service.proto",
}
