// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2026 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: iota/grpc/v1/move_package_service.proto

package move_package_service

import (
	_ "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/options"
	types "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListPackageVersionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Either the `storage_id` of any version of an upgraded package,
	// or the `original_id` of an immutable (first version) package.
	PackageId *types.ObjectId `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3,oneof" json:"package_id,omitempty"`
	// The maximum number of versions to return. The service may return fewer than this value.
	// If unspecified, at most `1000` entries will be returned.
	// The maximum value is `10000`; values above `10000` will be coerced to `10000`.
	PageSize *uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	// A page token, received from a previous `ListPackageVersions` call.
	// Provide this to retrieve the subsequent page.
	//
	// When paginating, all other parameters provided to `ListPackageVersions` must
	// match the call that provided the page token.
	PageToken []byte `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	// Optional maximum message size the client can receive (1MB - 128MB).
	// If not specified, server uses default chunking threshold (4MB).
	MaxMessageSizeBytes *uint32 `protobuf:"varint,4,opt,name=max_message_size_bytes,json=maxMessageSizeBytes,proto3,oneof" json:"max_message_size_bytes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListPackageVersionsRequest) Reset() {
	*x = ListPackageVersionsRequest{}
	mi := &file_iota_grpc_v1_move_package_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPackageVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPackageVersionsRequest) ProtoMessage() {}

func (x *ListPackageVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_move_package_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPackageVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListPackageVersionsRequest) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_move_package_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListPackageVersionsRequest) GetPackageId() *types.ObjectId {
	if x != nil {
		return x.PackageId
	}
	return nil
}

func (x *ListPackageVersionsRequest) GetPageSize() uint32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListPackageVersionsRequest) GetPageToken() []byte {
	if x != nil {
		return x.PageToken
	}
	return nil
}

func (x *ListPackageVersionsRequest) GetMaxMessageSizeBytes() uint32 {
	if x != nil && x.MaxMessageSizeBytes != nil {
		return *x.MaxMessageSizeBytes
	}
	return 0
}

type ListPackageVersionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of all package versions, ordered by version.
	Versions []*PackageVersion `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	// A token, which can be sent as `page_token` to retrieve the next page.
	// If this field is omitted, there are no subsequent pages.
	NextPageToken []byte `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3,oneof" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPackageVersionsResponse) Reset() {
	*x = ListPackageVersionsResponse{}
	mi := &file_iota_grpc_v1_move_package_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPackageVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPackageVersionsResponse) ProtoMessage() {}

func (x *ListPackageVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_move_package_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPackageVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListPackageVersionsResponse) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_move_package_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListPackageVersionsResponse) GetVersions() []*PackageVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *ListPackageVersionsResponse) GetNextPageToken() []byte {
	if x != nil {
		return x.NextPageToken
	}
	return nil
}

// A simplified representation of a package version.
type PackageVersion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The original (immutable) package ID shared across all versions
	OriginalId *types.ObjectId `protobuf:"bytes,1,opt,name=original_id,json=originalId,proto3,oneof" json:"original_id,omitempty"`
	// The storage ID of this specific package version
	StorageId *types.ObjectId `protobuf:"bytes,2,opt,name=storage_id,json=storageId,proto3,oneof" json:"storage_id,omitempty"`
	// The version number
	Version       *uint64 `protobuf:"varint,3,opt,name=version,proto3,oneof" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageVersion) Reset() {
	*x = PackageVersion{}
	mi := &file_iota_grpc_v1_move_package_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageVersion) ProtoMessage() {}

func (x *PackageVersion) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_move_package_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageVersion.ProtoReflect.Descriptor instead.
func (*PackageVersion) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_move_package_service_proto_rawDescGZIP(), []int{2}
}

func (x *PackageVersion) GetOriginalId() *types.ObjectId {
	if x != nil {
		return x.OriginalId
	}
	return nil
}

func (x *PackageVersion) GetStorageId() *types.ObjectId {
	if x != nil {
		return x.StorageId
	}
	return nil
}

func (x *PackageVersion) GetVersion() uint64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

var File_iota_grpc_v1_move_package_service_proto protoreflect.FileDescriptor

const file_iota_grpc_v1_move_package_service_proto_rawDesc = "" +
	"\n" +
	"'iota/grpc/v1/move_package_service.proto\x12!iota.grpc.v1.move_package_service\x1a\x17iota/grpc/options.proto\x1a\x18iota/grpc/v1/types.proto\"\xaf\x02\n" +
	"\x1aListPackageVersionsRequest\x12@\n" +
	"\n" +
	"package_id\x18\x01 \x01(\v2\x1c.iota.grpc.v1.types.ObjectIdH\x00R\tpackageId\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x02 \x01(\rH\x01R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\fH\x02R\tpageToken\x88\x01\x01\x128\n" +
	"\x16max_message_size_bytes\x18\x04 \x01(\rH\x03R\x13maxMessageSizeBytes\x88\x01\x01:\b\x82\xb5\x18\x04withB\r\n" +
	"\v_package_idB\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_tokenB\x19\n" +
	"\x17_max_message_size_bytes\"\xb7\x01\n" +
	"\x1bListPackageVersionsResponse\x12M\n" +
	"\bversions\x18\x01 \x03(\v21.iota.grpc.v1.move_package_service.PackageVersionR\bversions\x12+\n" +
	"\x0fnext_page_token\x18\x02 \x01(\fH\x00R\rnextPageToken\x88\x01\x01:\b\x82\xb5\x18\x04withB\x12\n" +
	"\x10_next_page_token\"\xea\x01\n" +
	"\x0ePackageVersion\x12B\n" +
	"\voriginal_id\x18\x01 \x01(\v2\x1c.iota.grpc.v1.types.ObjectIdH\x00R\n" +
	"originalId\x88\x01\x01\x12@\n" +
	"\n" +
	"storage_id\x18\x02 \x01(\v2\x1c.iota.grpc.v1.types.ObjectIdH\x01R\tstorageId\x88\x01\x01\x12\x1d\n" +
	"\aversion\x18\x03 \x01(\x04H\x02R\aversion\x88\x01\x01:\b\x82\xb5\x18\x04withB\x0e\n" +
	"\f_original_idB\r\n" +
	"\v_storage_idB\n" +
	"\n" +
	"\b_version2\xab\x01\n" +
	"\x12MovePackageService\x12\x94\x01\n" +
	"\x13ListPackageVersions\x12=.iota.grpc.v1.move_package_service.ListPackageVersionsRequest\x1a>.iota.grpc.v1.move_package_service.ListPackageVersionsResponseb\x06proto3"

var (
	file_iota_grpc_v1_move_package_service_proto_rawDescOnce sync.Once
	file_iota_grpc_v1_move_package_service_proto_rawDescData []byte
)

func file_iota_grpc_v1_move_package_service_proto_rawDescGZIP() []byte {
	file_iota_grpc_v1_move_package_service_proto_rawDescOnce.Do(func() {
		file_iota_grpc_v1_move_package_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_move_package_service_proto_rawDesc), len(file_iota_grpc_v1_move_package_service_proto_rawDesc)))
	})
	return file_iota_grpc_v1_move_package_service_proto_rawDescData
}

var file_iota_grpc_v1_move_package_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_iota_grpc_v1_move_package_service_proto_goTypes = []any{
	(*ListPackageVersionsRequest)(nil),  // 0: iota.grpc.v1.move_package_service.ListPackageVersionsRequest
	(*ListPackageVersionsResponse)(nil), // 1: iota.grpc.v1.move_package_service.ListPackageVersionsResponse
	(*PackageVersion)(nil),              // 2: iota.grpc.v1.move_package_service.PackageVersion
	(*types.ObjectId)(nil),              // 3: iota.grpc.v1.types.ObjectId
}
var file_iota_grpc_v1_move_package_service_proto_depIdxs = []int32{
	3, // 0: iota.grpc.v1.move_package_service.ListPackageVersionsRequest.package_id:type_name -> iota.grpc.v1.types.ObjectId
	2, // 1: iota.grpc.v1.move_package_service.ListPackageVersionsResponse.versions:type_name -> iota.grpc.v1.move_package_service.PackageVersion
	3, // 2: iota.grpc.v1.move_package_service.PackageVersion.original_id:type_name -> iota.grpc.v1.types.ObjectId
	3, // 3: iota.grpc.v1.move_package_service.PackageVersion.storage_id:type_name -> iota.grpc.v1.types.ObjectId
	0, // 4: iota.grpc.v1.move_package_service.MovePackageService.ListPackageVersions:input_type -> iota.grpc.v1.move_package_service.ListPackageVersionsRequest
	1, // 5: iota.grpc.v1.move_package_service.MovePackageService.ListPackageVersions:output_type -> iota.grpc.v1.move_package_service.ListPackageVersionsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_iota_grpc_v1_move_package_service_proto_init() }
func file_iota_grpc_v1_move_package_service_proto_init() {
	if File_iota_grpc_v1_move_package_service_proto != nil {
		return
	}
	file_iota_grpc_v1_move_package_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_iota_grpc_v1_move_package_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_iota_grpc_v1_move_package_service_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_move_package_service_proto_rawDesc), len(file_iota_grpc_v1_move_package_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iota_grpc_v1_move_package_service_proto_goTypes,
		DependencyIndexes: file_iota_grpc_v1_move_package_service_proto_depIdxs,
		MessageInfos:      file_iota_grpc_v1_move_package_service_proto_msgTypes,
	}.Build()
	File_iota_grpc_v1_move_package_service_proto = out.File
	file_iota_grpc_v1_move_package_service_proto_goTypes = nil
	file_iota_grpc_v1_move_package_service_proto_depIdxs = nil
}
