// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: iota/grpc/v1/ledger_service.proto

package ledger_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LedgerService_GetHealth_FullMethodName         = "/iota.grpc.v1.ledger_service.LedgerService/GetHealth"
	LedgerService_GetServiceInfo_FullMethodName    = "/iota.grpc.v1.ledger_service.LedgerService/GetServiceInfo"
	LedgerService_GetObjects_FullMethodName        = "/iota.grpc.v1.ledger_service.LedgerService/GetObjects"
	LedgerService_GetTransactions_FullMethodName   = "/iota.grpc.v1.ledger_service.LedgerService/GetTransactions"
	LedgerService_GetCheckpoint_FullMethodName     = "/iota.grpc.v1.ledger_service.LedgerService/GetCheckpoint"
	LedgerService_StreamCheckpoints_FullMethodName = "/iota.grpc.v1.ledger_service.LedgerService/StreamCheckpoints"
	LedgerService_GetEpoch_FullMethodName          = "/iota.grpc.v1.ledger_service.LedgerService/GetEpoch"
)

// LedgerServiceClient is the client API for LedgerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LedgerServiceClient interface {
	// Check the health of the node.
	GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error)
	// Query the service for general information about its current state.
	GetServiceInfo(ctx context.Context, in *GetServiceInfoRequest, opts ...grpc.CallOption) (*GetServiceInfoResponse, error)
	GetObjects(ctx context.Context, in *GetObjectsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetObjectsResponse], error)
	GetTransactions(ctx context.Context, in *GetTransactionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetTransactionsResponse], error)
	// Checkpoint operations
	GetCheckpoint(ctx context.Context, in *GetCheckpointRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CheckpointData], error)
	StreamCheckpoints(ctx context.Context, in *StreamCheckpointsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CheckpointData], error)
	GetEpoch(ctx context.Context, in *GetEpochRequest, opts ...grpc.CallOption) (*GetEpochResponse, error)
}

type ledgerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLedgerServiceClient(cc grpc.ClientConnInterface) LedgerServiceClient {
	return &ledgerServiceClient{cc}
}

func (c *ledgerServiceClient) GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHealthResponse)
	err := c.cc.Invoke(ctx, LedgerService_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetServiceInfo(ctx context.Context, in *GetServiceInfoRequest, opts ...grpc.CallOption) (*GetServiceInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceInfoResponse)
	err := c.cc.Invoke(ctx, LedgerService_GetServiceInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetObjects(ctx context.Context, in *GetObjectsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetObjectsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LedgerService_ServiceDesc.Streams[0], LedgerService_GetObjects_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetObjectsRequest, GetObjectsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LedgerService_GetObjectsClient = grpc.ServerStreamingClient[GetObjectsResponse]

func (c *ledgerServiceClient) GetTransactions(ctx context.Context, in *GetTransactionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetTransactionsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LedgerService_ServiceDesc.Streams[1], LedgerService_GetTransactions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetTransactionsRequest, GetTransactionsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LedgerService_GetTransactionsClient = grpc.ServerStreamingClient[GetTransactionsResponse]

func (c *ledgerServiceClient) GetCheckpoint(ctx context.Context, in *GetCheckpointRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CheckpointData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LedgerService_ServiceDesc.Streams[2], LedgerService_GetCheckpoint_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetCheckpointRequest, CheckpointData]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LedgerService_GetCheckpointClient = grpc.ServerStreamingClient[CheckpointData]

func (c *ledgerServiceClient) StreamCheckpoints(ctx context.Context, in *StreamCheckpointsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CheckpointData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LedgerService_ServiceDesc.Streams[3], LedgerService_StreamCheckpoints_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamCheckpointsRequest, CheckpointData]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LedgerService_StreamCheckpointsClient = grpc.ServerStreamingClient[CheckpointData]

func (c *ledgerServiceClient) GetEpoch(ctx context.Context, in *GetEpochRequest, opts ...grpc.CallOption) (*GetEpochResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEpochResponse)
	err := c.cc.Invoke(ctx, LedgerService_GetEpoch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LedgerServiceServer is the server API for LedgerService service.
// All implementations must embed UnimplementedLedgerServiceServer
// for forward compatibility.
type LedgerServiceServer interface {
	// Check the health of the node.
	GetHealth(context.Context, *GetHealthRequest) (*GetHealthResponse, error)
	// Query the service for general information about its current state.
	GetServiceInfo(context.Context, *GetServiceInfoRequest) (*GetServiceInfoResponse, error)
	GetObjects(*GetObjectsRequest, grpc.ServerStreamingServer[GetObjectsResponse]) error
	GetTransactions(*GetTransactionsRequest, grpc.ServerStreamingServer[GetTransactionsResponse]) error
	// Checkpoint operations
	GetCheckpoint(*GetCheckpointRequest, grpc.ServerStreamingServer[CheckpointData]) error
	StreamCheckpoints(*StreamCheckpointsRequest, grpc.ServerStreamingServer[CheckpointData]) error
	GetEpoch(context.Context, *GetEpochRequest) (*GetEpochResponse, error)
	mustEmbedUnimplementedLedgerServiceServer()
}

// UnimplementedLedgerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLedgerServiceServer struct{}

func (UnimplementedLedgerServiceServer) GetHealth(context.Context, *GetHealthRequest) (*GetHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedLedgerServiceServer) GetServiceInfo(context.Context, *GetServiceInfoRequest) (*GetServiceInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServiceInfo not implemented")
}
func (UnimplementedLedgerServiceServer) GetObjects(*GetObjectsRequest, grpc.ServerStreamingServer[GetObjectsResponse]) error {
	return status.Error(codes.Unimplemented, "method GetObjects not implemented")
}
func (UnimplementedLedgerServiceServer) GetTransactions(*GetTransactionsRequest, grpc.ServerStreamingServer[GetTransactionsResponse]) error {
	return status.Error(codes.Unimplemented, "method GetTransactions not implemented")
}
func (UnimplementedLedgerServiceServer) GetCheckpoint(*GetCheckpointRequest, grpc.ServerStreamingServer[CheckpointData]) error {
	return status.Error(codes.Unimplemented, "method GetCheckpoint not implemented")
}
func (UnimplementedLedgerServiceServer) StreamCheckpoints(*StreamCheckpointsRequest, grpc.ServerStreamingServer[CheckpointData]) error {
	return status.Error(codes.Unimplemented, "method StreamCheckpoints not implemented")
}
func (UnimplementedLedgerServiceServer) GetEpoch(context.Context, *GetEpochRequest) (*GetEpochResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEpoch not implemented")
}
func (UnimplementedLedgerServiceServer) mustEmbedUnimplementedLedgerServiceServer() {}
func (UnimplementedLedgerServiceServer) testEmbeddedByValue()                       {}

// UnsafeLedgerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LedgerServiceServer will
// result in compilation errors.
type UnsafeLedgerServiceServer interface {
	mustEmbedUnimplementedLedgerServiceServer()
}

func RegisterLedgerServiceServer(s grpc.ServiceRegistrar, srv LedgerServiceServer) {
	// If the following call panics, it indicates UnimplementedLedgerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LedgerService_ServiceDesc, srv)
}

func _LedgerService_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetHealth(ctx, req.(*GetHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetServiceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetServiceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetServiceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetServiceInfo(ctx, req.(*GetServiceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetObjects_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetObjectsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LedgerServiceServer).GetObjects(m, &grpc.GenericServerStream[GetObjectsRequest, GetObjectsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LedgerService_GetObjectsServer = grpc.ServerStreamingServer[GetObjectsResponse]

func _LedgerService_GetTransactions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetTransactionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LedgerServiceServer).GetTransactions(m, &grpc.GenericServerStream[GetTransactionsRequest, GetTransactionsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LedgerService_GetTransactionsServer = grpc.ServerStreamingServer[GetTransactionsResponse]

func _LedgerService_GetCheckpoint_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetCheckpointRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LedgerServiceServer).GetCheckpoint(m, &grpc.GenericServerStream[GetCheckpointRequest, CheckpointData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LedgerService_GetCheckpointServer = grpc.ServerStreamingServer[CheckpointData]

func _LedgerService_StreamCheckpoints_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamCheckpointsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LedgerServiceServer).StreamCheckpoints(m, &grpc.GenericServerStream[StreamCheckpointsRequest, CheckpointData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LedgerService_StreamCheckpointsServer = grpc.ServerStreamingServer[CheckpointData]

func _LedgerService_GetEpoch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEpochRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetEpoch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetEpoch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetEpoch(ctx, req.(*GetEpochRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LedgerService_ServiceDesc is the grpc.ServiceDesc for LedgerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LedgerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iota.grpc.v1.ledger_service.LedgerService",
	HandlerType: (*LedgerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHealth",
			Handler:    _LedgerService_GetHealth_Handler,
		},
		{
			MethodName: "GetServiceInfo",
			Handler:    _LedgerService_GetServiceInfo_Handler,
		},
		{
			MethodName: "GetEpoch",
			Handler:    _LedgerService_GetEpoch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetObjects",
			Handler:       _LedgerService_GetObjects_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetTransactions",
			Handler:       _LedgerService_GetTransactions_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetCheckpoint",
			Handler:       _LedgerService_GetCheckpoint_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamCheckpoints",
			Handler:       _LedgerService_StreamCheckpoints_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "iota/grpc/v1/ledger_service.proto",
}
