// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: iota/grpc/v1/ledger_service.proto

package ledger_service

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	_ "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/options"
	checkpoint "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/checkpoint"
	epoch "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/epoch"
	event "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/event"
	filter "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/filter"
	object "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/object"
	transaction "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/transaction"
	types "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHealthRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional threshold in milliseconds. The node is considered healthy only if
	// the latest executed checkpoint timestamp is within this many milliseconds of
	// the current system time. If not provided, the server applies a default
	// threshold of 5 seconds.
	ThresholdMs   *uint64 `protobuf:"varint,1,opt,name=threshold_ms,json=thresholdMs,proto3,oneof" json:"threshold_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthRequest) Reset() {
	*x = GetHealthRequest{}
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthRequest) ProtoMessage() {}

func (x *GetHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthRequest.ProtoReflect.Descriptor instead.
func (*GetHealthRequest) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_ledger_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetHealthRequest) GetThresholdMs() uint64 {
	if x != nil && x.ThresholdMs != nil {
		return *x.ThresholdMs
	}
	return 0
}

type GetHealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Checkpoint height of the most recently executed checkpoint.
	ExecutedCheckpointHeight *uint64 `protobuf:"varint,1,opt,name=executed_checkpoint_height,json=executedCheckpointHeight,proto3,oneof" json:"executed_checkpoint_height,omitempty"`
	// Estimated validator latency in milliseconds.
	// Reserved for future use.
	EstimatedValidatorLatencyMs *uint32 `protobuf:"varint,2,opt,name=estimated_validator_latency_ms,json=estimatedValidatorLatencyMs,proto3,oneof" json:"estimated_validator_latency_ms,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *GetHealthResponse) Reset() {
	*x = GetHealthResponse{}
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthResponse) ProtoMessage() {}

func (x *GetHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthResponse.ProtoReflect.Descriptor instead.
func (*GetHealthResponse) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_ledger_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetHealthResponse) GetExecutedCheckpointHeight() uint64 {
	if x != nil && x.ExecutedCheckpointHeight != nil {
		return *x.ExecutedCheckpointHeight
	}
	return 0
}

func (x *GetHealthResponse) GetEstimatedValidatorLatencyMs() uint32 {
	if x != nil && x.EstimatedValidatorLatencyMs != nil {
		return *x.EstimatedValidatorLatencyMs
	}
	return 0
}

type GetServiceInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Mask specifying which ServiceInfo fields to read.
	// If no mask is specified, defaults to `chain_id,epoch,checkpoint_height`.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,1,opt,name=read_mask,json=readMask,proto3,oneof" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceInfoRequest) Reset() {
	*x = GetServiceInfoRequest{}
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceInfoRequest) ProtoMessage() {}

func (x *GetServiceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceInfoRequest.ProtoReflect.Descriptor instead.
func (*GetServiceInfoRequest) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_ledger_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetServiceInfoRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

type GetServiceInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The chain identifier of the chain that this node is on.
	//
	// The chain identifier is the digest of the genesis checkpoint, the
	// checkpoint with sequence number 0.
	ChainId *types.Digest `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3,oneof" json:"chain_id,omitempty"`
	// Human-readable name of the chain that this node is on.
	//
	// This is intended to be a human-readable name like `mainnet`, `testnet`, and so on.
	Chain *string `protobuf:"bytes,2,opt,name=chain,proto3,oneof" json:"chain,omitempty"`
	// Current epoch of the node based on its highest executed checkpoint.
	Epoch *uint64 `protobuf:"varint,3,opt,name=epoch,proto3,oneof" json:"epoch,omitempty"`
	// Checkpoint height of the most recently executed checkpoint.
	ExecutedCheckpointHeight *uint64 `protobuf:"varint,4,opt,name=executed_checkpoint_height,json=executedCheckpointHeight,proto3,oneof" json:"executed_checkpoint_height,omitempty"`
	// Unix timestamp of the most recently executed checkpoint.
	ExecutedCheckpointTimestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=executed_checkpoint_timestamp,json=executedCheckpointTimestamp,proto3,oneof" json:"executed_checkpoint_timestamp,omitempty"`
	// The lowest checkpoint for which checkpoints and transaction data are available.
	LowestAvailableCheckpoint *uint64 `protobuf:"varint,6,opt,name=lowest_available_checkpoint,json=lowestAvailableCheckpoint,proto3,oneof" json:"lowest_available_checkpoint,omitempty"`
	// The lowest checkpoint for which object data is available.
	LowestAvailableCheckpointObjects *uint64 `protobuf:"varint,7,opt,name=lowest_available_checkpoint_objects,json=lowestAvailableCheckpointObjects,proto3,oneof" json:"lowest_available_checkpoint_objects,omitempty"`
	// Software version of the service. Similar to the `server` http header.
	Server        *string `protobuf:"bytes,8,opt,name=server,proto3,oneof" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceInfoResponse) Reset() {
	*x = GetServiceInfoResponse{}
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceInfoResponse) ProtoMessage() {}

func (x *GetServiceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceInfoResponse.ProtoReflect.Descriptor instead.
func (*GetServiceInfoResponse) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_ledger_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetServiceInfoResponse) GetChainId() *types.Digest {
	if x != nil {
		return x.ChainId
	}
	return nil
}

func (x *GetServiceInfoResponse) GetChain() string {
	if x != nil && x.Chain != nil {
		return *x.Chain
	}
	return ""
}

func (x *GetServiceInfoResponse) GetEpoch() uint64 {
	if x != nil && x.Epoch != nil {
		return *x.Epoch
	}
	return 0
}

func (x *GetServiceInfoResponse) GetExecutedCheckpointHeight() uint64 {
	if x != nil && x.ExecutedCheckpointHeight != nil {
		return *x.ExecutedCheckpointHeight
	}
	return 0
}

func (x *GetServiceInfoResponse) GetExecutedCheckpointTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecutedCheckpointTimestamp
	}
	return nil
}

func (x *GetServiceInfoResponse) GetLowestAvailableCheckpoint() uint64 {
	if x != nil && x.LowestAvailableCheckpoint != nil {
		return *x.LowestAvailableCheckpoint
	}
	return 0
}

func (x *GetServiceInfoResponse) GetLowestAvailableCheckpointObjects() uint64 {
	if x != nil && x.LowestAvailableCheckpointObjects != nil {
		return *x.LowestAvailableCheckpointObjects
	}
	return 0
}

func (x *GetServiceInfoResponse) GetServer() string {
	if x != nil && x.Server != nil {
		return *x.Server
	}
	return ""
}

type ObjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The `ObjectId` of the requested object.
	// If no version is specified, and the object is live, then the latest
	// version of the object is returned.
	ObjectRef     *types.ObjectReference `protobuf:"bytes,1,opt,name=object_ref,json=objectRef,proto3,oneof" json:"object_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectRequest) Reset() {
	*x = ObjectRequest{}
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectRequest) ProtoMessage() {}

func (x *ObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectRequest.ProtoReflect.Descriptor instead.
func (*ObjectRequest) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_ledger_service_proto_rawDescGZIP(), []int{4}
}

func (x *ObjectRequest) GetObjectRef() *types.ObjectReference {
	if x != nil {
		return x.ObjectRef
	}
	return nil
}

type ObjectRequests struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*ObjectRequest       `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectRequests) Reset() {
	*x = ObjectRequests{}
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectRequests) ProtoMessage() {}

func (x *ObjectRequests) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectRequests.ProtoReflect.Descriptor instead.
func (*ObjectRequests) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_ledger_service_proto_rawDescGZIP(), []int{5}
}

func (x *ObjectRequests) GetRequests() []*ObjectRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type GetObjectsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Requests *ObjectRequests        `protobuf:"bytes,1,opt,name=requests,proto3,oneof" json:"requests,omitempty"`
	// Mask specifying which fields to read.
	// If no mask is specified, defaults to `object_id,version,digest`.
	ReadMask *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3,oneof" json:"read_mask,omitempty"`
	// Optional maximum message size the client can receive (1MB - 128MB)
	// If not specified, server uses default chunking threshold (4MB)
	MaxMessageSizeBytes *uint32 `protobuf:"varint,3,opt,name=max_message_size_bytes,json=maxMessageSizeBytes,proto3,oneof" json:"max_message_size_bytes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetObjectsRequest) Reset() {
	*x = GetObjectsRequest{}
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectsRequest) ProtoMessage() {}

func (x *GetObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectsRequest.ProtoReflect.Descriptor instead.
func (*GetObjectsRequest) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_ledger_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetObjectsRequest) GetRequests() *ObjectRequests {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *GetObjectsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

func (x *GetObjectsRequest) GetMaxMessageSizeBytes() uint32 {
	if x != nil && x.MaxMessageSizeBytes != nil {
		return *x.MaxMessageSizeBytes
	}
	return 0
}

type ObjectResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ObjectResult_Object
	//	*ObjectResult_Error
	Result        isObjectResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectResult) Reset() {
	*x = ObjectResult{}
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectResult) ProtoMessage() {}

func (x *ObjectResult) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectResult.ProtoReflect.Descriptor instead.
func (*ObjectResult) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_ledger_service_proto_rawDescGZIP(), []int{7}
}

func (x *ObjectResult) GetResult() isObjectResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ObjectResult) GetObject() *object.Object {
	if x != nil {
		if x, ok := x.Result.(*ObjectResult_Object); ok {
			return x.Object
		}
	}
	return nil
}

func (x *ObjectResult) GetError() *status.Status {
	if x != nil {
		if x, ok := x.Result.(*ObjectResult_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isObjectResult_Result interface {
	isObjectResult_Result()
}

type ObjectResult_Object struct {
	Object *object.Object `protobuf:"bytes,1,opt,name=object,proto3,oneof"`
}

type ObjectResult_Error struct {
	Error *status.Status `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ObjectResult_Object) isObjectResult_Result() {}

func (*ObjectResult_Error) isObjectResult_Result() {}

type GetObjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*ObjectResult        `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	HasNext       bool                   `protobuf:"varint,2,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectsResponse) Reset() {
	*x = GetObjectsResponse{}
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectsResponse) ProtoMessage() {}

func (x *GetObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectsResponse.ProtoReflect.Descriptor instead.
func (*GetObjectsResponse) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_ledger_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetObjectsResponse) GetObjects() []*ObjectResult {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *GetObjectsResponse) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

type TransactionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The digest of the requested transaction.
	Digest        *types.Digest `protobuf:"bytes,1,opt,name=digest,proto3,oneof" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_ledger_service_proto_rawDescGZIP(), []int{9}
}

func (x *TransactionRequest) GetDigest() *types.Digest {
	if x != nil {
		return x.Digest
	}
	return nil
}

type TransactionRequests struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*TransactionRequest  `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequests) Reset() {
	*x = TransactionRequests{}
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequests) ProtoMessage() {}

func (x *TransactionRequests) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequests.ProtoReflect.Descriptor instead.
func (*TransactionRequests) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_ledger_service_proto_rawDescGZIP(), []int{10}
}

func (x *TransactionRequests) GetRequests() []*TransactionRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type GetTransactionsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Requests *TransactionRequests   `protobuf:"bytes,1,opt,name=requests,proto3,oneof" json:"requests,omitempty"`
	// Mask specifying which fields to read.
	// If no mask is specified, defaults to `transaction.digest`.
	ReadMask *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3,oneof" json:"read_mask,omitempty"`
	// Optional maximum message size the client can receive (1MB - 128MB)
	// If not specified, server uses default chunking threshold (4MB)
	MaxMessageSizeBytes *uint32 `protobuf:"varint,3,opt,name=max_message_size_bytes,json=maxMessageSizeBytes,proto3,oneof" json:"max_message_size_bytes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetTransactionsRequest) Reset() {
	*x = GetTransactionsRequest{}
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsRequest) ProtoMessage() {}

func (x *GetTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_ledger_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetTransactionsRequest) GetRequests() *TransactionRequests {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *GetTransactionsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

func (x *GetTransactionsRequest) GetMaxMessageSizeBytes() uint32 {
	if x != nil && x.MaxMessageSizeBytes != nil {
		return *x.MaxMessageSizeBytes
	}
	return 0
}

type TransactionResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*TransactionResult_ExecutedTransaction
	//	*TransactionResult_Error
	Result        isTransactionResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResult) Reset() {
	*x = TransactionResult{}
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResult) ProtoMessage() {}

func (x *TransactionResult) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResult.ProtoReflect.Descriptor instead.
func (*TransactionResult) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_ledger_service_proto_rawDescGZIP(), []int{12}
}

func (x *TransactionResult) GetResult() isTransactionResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TransactionResult) GetExecutedTransaction() *transaction.ExecutedTransaction {
	if x != nil {
		if x, ok := x.Result.(*TransactionResult_ExecutedTransaction); ok {
			return x.ExecutedTransaction
		}
	}
	return nil
}

func (x *TransactionResult) GetError() *status.Status {
	if x != nil {
		if x, ok := x.Result.(*TransactionResult_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isTransactionResult_Result interface {
	isTransactionResult_Result()
}

type TransactionResult_ExecutedTransaction struct {
	ExecutedTransaction *transaction.ExecutedTransaction `protobuf:"bytes,1,opt,name=executed_transaction,json=executedTransaction,proto3,oneof"`
}

type TransactionResult_Error struct {
	Error *status.Status `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*TransactionResult_ExecutedTransaction) isTransactionResult_Result() {}

func (*TransactionResult_Error) isTransactionResult_Result() {}

type GetTransactionsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TransactionResults []*TransactionResult   `protobuf:"bytes,1,rep,name=transaction_results,json=transactionResults,proto3" json:"transaction_results,omitempty"`
	HasNext            bool                   `protobuf:"varint,2,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetTransactionsResponse) Reset() {
	*x = GetTransactionsResponse{}
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsResponse) ProtoMessage() {}

func (x *GetTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_ledger_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetTransactionsResponse) GetTransactionResults() []*TransactionResult {
	if x != nil {
		return x.TransactionResults
	}
	return nil
}

func (x *GetTransactionsResponse) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

type GetCheckpointRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to CheckpointId:
	//
	//	*GetCheckpointRequest_Latest
	//	*GetCheckpointRequest_SequenceNumber
	//	*GetCheckpointRequest_Digest
	CheckpointId isGetCheckpointRequest_CheckpointId `protobuf_oneof:"checkpoint_id"`
	// Mask specifying which fields to read.
	// If no mask is specified, defaults to `summary`.
	ReadMask *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=read_mask,json=readMask,proto3,oneof" json:"read_mask,omitempty"`
	// if no filter is passed, all transactions are included (if mentioned in the read_mask)
	TransactionsFilter *filter.TransactionFilter `protobuf:"bytes,5,opt,name=transactions_filter,json=transactionsFilter,proto3,oneof" json:"transactions_filter,omitempty"`
	// if no filter is passed, all events are included (if mentioned in the read_mask)
	EventsFilter *filter.EventFilter `protobuf:"bytes,6,opt,name=events_filter,json=eventsFilter,proto3,oneof" json:"events_filter,omitempty"`
	// Optional maximum message size the client can receive (1MB - 128MB)
	// If not specified, server uses default chunking threshold (4MB)
	MaxMessageSizeBytes *uint32 `protobuf:"varint,7,opt,name=max_message_size_bytes,json=maxMessageSizeBytes,proto3,oneof" json:"max_message_size_bytes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetCheckpointRequest) Reset() {
	*x = GetCheckpointRequest{}
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckpointRequest) ProtoMessage() {}

func (x *GetCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckpointRequest.ProtoReflect.Descriptor instead.
func (*GetCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_ledger_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetCheckpointRequest) GetCheckpointId() isGetCheckpointRequest_CheckpointId {
	if x != nil {
		return x.CheckpointId
	}
	return nil
}

func (x *GetCheckpointRequest) GetLatest() bool {
	if x != nil {
		if x, ok := x.CheckpointId.(*GetCheckpointRequest_Latest); ok {
			return x.Latest
		}
	}
	return false
}

func (x *GetCheckpointRequest) GetSequenceNumber() uint64 {
	if x != nil {
		if x, ok := x.CheckpointId.(*GetCheckpointRequest_SequenceNumber); ok {
			return x.SequenceNumber
		}
	}
	return 0
}

func (x *GetCheckpointRequest) GetDigest() *types.Digest {
	if x != nil {
		if x, ok := x.CheckpointId.(*GetCheckpointRequest_Digest); ok {
			return x.Digest
		}
	}
	return nil
}

func (x *GetCheckpointRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

func (x *GetCheckpointRequest) GetTransactionsFilter() *filter.TransactionFilter {
	if x != nil {
		return x.TransactionsFilter
	}
	return nil
}

func (x *GetCheckpointRequest) GetEventsFilter() *filter.EventFilter {
	if x != nil {
		return x.EventsFilter
	}
	return nil
}

func (x *GetCheckpointRequest) GetMaxMessageSizeBytes() uint32 {
	if x != nil && x.MaxMessageSizeBytes != nil {
		return *x.MaxMessageSizeBytes
	}
	return 0
}

type isGetCheckpointRequest_CheckpointId interface {
	isGetCheckpointRequest_CheckpointId()
}

type GetCheckpointRequest_Latest struct {
	// If set to true, the latest checkpoint is requested.
	Latest bool `protobuf:"varint,1,opt,name=latest,proto3,oneof"`
}

type GetCheckpointRequest_SequenceNumber struct {
	// The sequence number of the requested checkpoint.
	SequenceNumber uint64 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3,oneof"`
}

type GetCheckpointRequest_Digest struct {
	// The digest of the requested checkpoint.
	Digest *types.Digest `protobuf:"bytes,3,opt,name=digest,proto3,oneof"`
}

func (*GetCheckpointRequest_Latest) isGetCheckpointRequest_CheckpointId() {}

func (*GetCheckpointRequest_SequenceNumber) isGetCheckpointRequest_CheckpointId() {}

func (*GetCheckpointRequest_Digest) isGetCheckpointRequest_CheckpointId() {}

type StreamCheckpointsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// if no start sequence number is provided, streaming starts from the latest checkpoint
	StartSequenceNumber *uint64 `protobuf:"varint,1,opt,name=start_sequence_number,json=startSequenceNumber,proto3,oneof" json:"start_sequence_number,omitempty"`
	// if no end sequence number is provided, streaming continues forever
	EndSequenceNumber *uint64 `protobuf:"varint,2,opt,name=end_sequence_number,json=endSequenceNumber,proto3,oneof" json:"end_sequence_number,omitempty"`
	// Mask specifying which fields to read.
	// If no mask is specified, defaults to `summary`.
	ReadMask *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=read_mask,json=readMask,proto3,oneof" json:"read_mask,omitempty"`
	// if no filter is passed, all transactions are included (if mentioned in the read_mask)
	TransactionsFilter *filter.TransactionFilter `protobuf:"bytes,4,opt,name=transactions_filter,json=transactionsFilter,proto3,oneof" json:"transactions_filter,omitempty"`
	// if no filter is passed, all events are included (if mentioned in the read_mask)
	EventsFilter *filter.EventFilter `protobuf:"bytes,5,opt,name=events_filter,json=eventsFilter,proto3,oneof" json:"events_filter,omitempty"`
	// When true, checkpoints with no matching transactions or events are skipped entirely.
	// At least one of transactions_filter or events_filter must be set.
	// A Progress message is sent periodically to indicate liveness and scan position.
	FilterCheckpoints *bool `protobuf:"varint,6,opt,name=filter_checkpoints,json=filterCheckpoints,proto3,oneof" json:"filter_checkpoints,omitempty"`
	// Progress message interval in milliseconds when filter_checkpoints is enabled.
	// Defaults to 2000ms. Minimum value is 500ms; lower values are clamped.
	ProgressIntervalMs *uint32 `protobuf:"varint,7,opt,name=progress_interval_ms,json=progressIntervalMs,proto3,oneof" json:"progress_interval_ms,omitempty"`
	// Optional maximum message size the client can receive (1MB - 128MB)
	// If not specified, server uses default chunking threshold (4MB)
	MaxMessageSizeBytes *uint32 `protobuf:"varint,8,opt,name=max_message_size_bytes,json=maxMessageSizeBytes,proto3,oneof" json:"max_message_size_bytes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StreamCheckpointsRequest) Reset() {
	*x = StreamCheckpointsRequest{}
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCheckpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCheckpointsRequest) ProtoMessage() {}

func (x *StreamCheckpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCheckpointsRequest.ProtoReflect.Descriptor instead.
func (*StreamCheckpointsRequest) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_ledger_service_proto_rawDescGZIP(), []int{15}
}

func (x *StreamCheckpointsRequest) GetStartSequenceNumber() uint64 {
	if x != nil && x.StartSequenceNumber != nil {
		return *x.StartSequenceNumber
	}
	return 0
}

func (x *StreamCheckpointsRequest) GetEndSequenceNumber() uint64 {
	if x != nil && x.EndSequenceNumber != nil {
		return *x.EndSequenceNumber
	}
	return 0
}

func (x *StreamCheckpointsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

func (x *StreamCheckpointsRequest) GetTransactionsFilter() *filter.TransactionFilter {
	if x != nil {
		return x.TransactionsFilter
	}
	return nil
}

func (x *StreamCheckpointsRequest) GetEventsFilter() *filter.EventFilter {
	if x != nil {
		return x.EventsFilter
	}
	return nil
}

func (x *StreamCheckpointsRequest) GetFilterCheckpoints() bool {
	if x != nil && x.FilterCheckpoints != nil {
		return *x.FilterCheckpoints
	}
	return false
}

func (x *StreamCheckpointsRequest) GetProgressIntervalMs() uint32 {
	if x != nil && x.ProgressIntervalMs != nil {
		return *x.ProgressIntervalMs
	}
	return 0
}

func (x *StreamCheckpointsRequest) GetMaxMessageSizeBytes() uint32 {
	if x != nil && x.MaxMessageSizeBytes != nil {
		return *x.MaxMessageSizeBytes
	}
	return 0
}

type CheckpointData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CheckpointData_Checkpoint
	//	*CheckpointData_ExecutedTransactions
	//	*CheckpointData_Events
	//	*CheckpointData_Progress_
	//	*CheckpointData_EndMarker_
	Payload       isCheckpointData_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointData) Reset() {
	*x = CheckpointData{}
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointData) ProtoMessage() {}

func (x *CheckpointData) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointData.ProtoReflect.Descriptor instead.
func (*CheckpointData) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_ledger_service_proto_rawDescGZIP(), []int{16}
}

func (x *CheckpointData) GetPayload() isCheckpointData_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CheckpointData) GetCheckpoint() *checkpoint.Checkpoint {
	if x != nil {
		if x, ok := x.Payload.(*CheckpointData_Checkpoint); ok {
			return x.Checkpoint
		}
	}
	return nil
}

func (x *CheckpointData) GetExecutedTransactions() *transaction.ExecutedTransactions {
	if x != nil {
		if x, ok := x.Payload.(*CheckpointData_ExecutedTransactions); ok {
			return x.ExecutedTransactions
		}
	}
	return nil
}

func (x *CheckpointData) GetEvents() *event.Events {
	if x != nil {
		if x, ok := x.Payload.(*CheckpointData_Events); ok {
			return x.Events
		}
	}
	return nil
}

func (x *CheckpointData) GetProgress() *CheckpointData_Progress {
	if x != nil {
		if x, ok := x.Payload.(*CheckpointData_Progress_); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *CheckpointData) GetEndMarker() *CheckpointData_EndMarker {
	if x != nil {
		if x, ok := x.Payload.(*CheckpointData_EndMarker_); ok {
			return x.EndMarker
		}
	}
	return nil
}

type isCheckpointData_Payload interface {
	isCheckpointData_Payload()
}

type CheckpointData_Checkpoint struct {
	Checkpoint *checkpoint.Checkpoint `protobuf:"bytes,1,opt,name=checkpoint,proto3,oneof"`
}

type CheckpointData_ExecutedTransactions struct {
	ExecutedTransactions *transaction.ExecutedTransactions `protobuf:"bytes,2,opt,name=executed_transactions,json=executedTransactions,proto3,oneof"`
}

type CheckpointData_Events struct {
	Events *event.Events `protobuf:"bytes,3,opt,name=events,proto3,oneof"`
}

type CheckpointData_Progress_ struct {
	Progress *CheckpointData_Progress `protobuf:"bytes,4,opt,name=progress,proto3,oneof"`
}

type CheckpointData_EndMarker_ struct {
	EndMarker *CheckpointData_EndMarker `protobuf:"bytes,5,opt,name=end_marker,json=endMarker,proto3,oneof"`
}

func (*CheckpointData_Checkpoint) isCheckpointData_Payload() {}

func (*CheckpointData_ExecutedTransactions) isCheckpointData_Payload() {}

func (*CheckpointData_Events) isCheckpointData_Payload() {}

func (*CheckpointData_Progress_) isCheckpointData_Payload() {}

func (*CheckpointData_EndMarker_) isCheckpointData_Payload() {}

type GetEpochRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested epoch.
	// If no epoch is provided the current epoch will be returned.
	Epoch *uint64 `protobuf:"varint,1,opt,name=epoch,proto3,oneof" json:"epoch,omitempty"`
	// Mask specifying which fields to read.
	// If no mask is specified, defaults to `epoch`.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3,oneof" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEpochRequest) Reset() {
	*x = GetEpochRequest{}
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEpochRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEpochRequest) ProtoMessage() {}

func (x *GetEpochRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEpochRequest.ProtoReflect.Descriptor instead.
func (*GetEpochRequest) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_ledger_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetEpochRequest) GetEpoch() uint64 {
	if x != nil && x.Epoch != nil {
		return *x.Epoch
	}
	return 0
}

func (x *GetEpochRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

type GetEpochResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         *epoch.Epoch           `protobuf:"bytes,1,opt,name=epoch,proto3,oneof" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEpochResponse) Reset() {
	*x = GetEpochResponse{}
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEpochResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEpochResponse) ProtoMessage() {}

func (x *GetEpochResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEpochResponse.ProtoReflect.Descriptor instead.
func (*GetEpochResponse) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_ledger_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetEpochResponse) GetEpoch() *epoch.Epoch {
	if x != nil {
		return x.Epoch
	}
	return nil
}

type CheckpointData_Progress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The sequence number of the latest scanned checkpoint.
	LatestScannedSequenceNumber uint64 `protobuf:"varint,1,opt,name=latest_scanned_sequence_number,json=latestScannedSequenceNumber,proto3" json:"latest_scanned_sequence_number,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *CheckpointData_Progress) Reset() {
	*x = CheckpointData_Progress{}
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointData_Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointData_Progress) ProtoMessage() {}

func (x *CheckpointData_Progress) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointData_Progress.ProtoReflect.Descriptor instead.
func (*CheckpointData_Progress) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_ledger_service_proto_rawDescGZIP(), []int{16, 0}
}

func (x *CheckpointData_Progress) GetLatestScannedSequenceNumber() uint64 {
	if x != nil {
		return x.LatestScannedSequenceNumber
	}
	return 0
}

type CheckpointData_EndMarker struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The height of this checkpoint.
	SequenceNumber *uint64 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3,oneof" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckpointData_EndMarker) Reset() {
	*x = CheckpointData_EndMarker{}
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointData_EndMarker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointData_EndMarker) ProtoMessage() {}

func (x *CheckpointData_EndMarker) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_ledger_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointData_EndMarker.ProtoReflect.Descriptor instead.
func (*CheckpointData_EndMarker) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_ledger_service_proto_rawDescGZIP(), []int{16, 1}
}

func (x *CheckpointData_EndMarker) GetSequenceNumber() uint64 {
	if x != nil && x.SequenceNumber != nil {
		return *x.SequenceNumber
	}
	return 0
}

var File_iota_grpc_v1_ledger_service_proto protoreflect.FileDescriptor

const file_iota_grpc_v1_ledger_service_proto_rawDesc = "" +
	"\n" +
	"!iota/grpc/v1/ledger_service.proto\x12\x1biota.grpc.v1.ledger_service\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17google/rpc/status.proto\x1a\x17iota/grpc/options.proto\x1a\x1diota/grpc/v1/checkpoint.proto\x1a\x18iota/grpc/v1/epoch.proto\x1a\x18iota/grpc/v1/event.proto\x1a\x19iota/grpc/v1/filter.proto\x1a\x19iota/grpc/v1/object.proto\x1a\x1eiota/grpc/v1/transaction.proto\x1a\x18iota/grpc/v1/types.proto\"U\n" +
	"\x10GetHealthRequest\x12&\n" +
	"\fthreshold_ms\x18\x01 \x01(\x04H\x00R\vthresholdMs\x88\x01\x01:\b\x82\xb5\x18\x04withB\x0f\n" +
	"\r_threshold_ms\"\xec\x01\n" +
	"\x11GetHealthResponse\x12A\n" +
	"\x1aexecuted_checkpoint_height\x18\x01 \x01(\x04H\x00R\x18executedCheckpointHeight\x88\x01\x01\x12H\n" +
	"\x1eestimated_validator_latency_ms\x18\x02 \x01(\rH\x01R\x1bestimatedValidatorLatencyMs\x88\x01\x01:\b\x82\xb5\x18\x04withB\x1d\n" +
	"\x1b_executed_checkpoint_heightB!\n" +
	"\x1f_estimated_validator_latency_ms\"m\n" +
	"\x15GetServiceInfoRequest\x12<\n" +
	"\tread_mask\x18\x01 \x01(\v2\x1a.google.protobuf.FieldMaskH\x00R\breadMask\x88\x01\x01:\b\x82\xb5\x18\x04withB\f\n" +
	"\n" +
	"_read_mask\"\xa7\x05\n" +
	"\x16GetServiceInfoResponse\x12:\n" +
	"\bchain_id\x18\x01 \x01(\v2\x1a.iota.grpc.v1.types.DigestH\x00R\achainId\x88\x01\x01\x12\x19\n" +
	"\x05chain\x18\x02 \x01(\tH\x01R\x05chain\x88\x01\x01\x12\x19\n" +
	"\x05epoch\x18\x03 \x01(\x04H\x02R\x05epoch\x88\x01\x01\x12A\n" +
	"\x1aexecuted_checkpoint_height\x18\x04 \x01(\x04H\x03R\x18executedCheckpointHeight\x88\x01\x01\x12c\n" +
	"\x1dexecuted_checkpoint_timestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\x1bexecutedCheckpointTimestamp\x88\x01\x01\x12C\n" +
	"\x1blowest_available_checkpoint\x18\x06 \x01(\x04H\x05R\x19lowestAvailableCheckpoint\x88\x01\x01\x12R\n" +
	"#lowest_available_checkpoint_objects\x18\a \x01(\x04H\x06R lowestAvailableCheckpointObjects\x88\x01\x01\x12\x1b\n" +
	"\x06server\x18\b \x01(\tH\aR\x06server\x88\x01\x01:\b\x82\xb5\x18\x04withB\v\n" +
	"\t_chain_idB\b\n" +
	"\x06_chainB\b\n" +
	"\x06_epochB\x1d\n" +
	"\x1b_executed_checkpoint_heightB \n" +
	"\x1e_executed_checkpoint_timestampB\x1e\n" +
	"\x1c_lowest_available_checkpointB&\n" +
	"$_lowest_available_checkpoint_objectsB\t\n" +
	"\a_server\"q\n" +
	"\rObjectRequest\x12G\n" +
	"\n" +
	"object_ref\x18\x01 \x01(\v2#.iota.grpc.v1.types.ObjectReferenceH\x00R\tobjectRef\x88\x01\x01:\b\x82\xb5\x18\x04withB\r\n" +
	"\v_object_ref\"b\n" +
	"\x0eObjectRequests\x12F\n" +
	"\brequests\x18\x01 \x03(\v2*.iota.grpc.v1.ledger_service.ObjectRequestR\brequests:\b\x82\xb5\x18\x04with\"\x99\x02\n" +
	"\x11GetObjectsRequest\x12L\n" +
	"\brequests\x18\x01 \x01(\v2+.iota.grpc.v1.ledger_service.ObjectRequestsH\x00R\brequests\x88\x01\x01\x12<\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskH\x01R\breadMask\x88\x01\x01\x128\n" +
	"\x16max_message_size_bytes\x18\x03 \x01(\rH\x02R\x13maxMessageSizeBytes\x88\x01\x01:\b\x82\xb5\x18\x04withB\v\n" +
	"\t_requestsB\f\n" +
	"\n" +
	"_read_maskB\x19\n" +
	"\x17_max_message_size_bytes\"\x85\x01\n" +
	"\fObjectResult\x125\n" +
	"\x06object\x18\x01 \x01(\v2\x1b.iota.grpc.v1.object.ObjectH\x00R\x06object\x12*\n" +
	"\x05error\x18\x02 \x01(\v2\x12.google.rpc.StatusH\x00R\x05error:\b\x82\xb5\x18\x04withB\b\n" +
	"\x06result\"~\n" +
	"\x12GetObjectsResponse\x12C\n" +
	"\aobjects\x18\x01 \x03(\v2).iota.grpc.v1.ledger_service.ObjectResultR\aobjects\x12\x19\n" +
	"\bhas_next\x18\x02 \x01(\bR\ahasNext:\b\x82\xb5\x18\x04with\"b\n" +
	"\x12TransactionRequest\x127\n" +
	"\x06digest\x18\x01 \x01(\v2\x1a.iota.grpc.v1.types.DigestH\x00R\x06digest\x88\x01\x01:\b\x82\xb5\x18\x04withB\t\n" +
	"\a_digest\"l\n" +
	"\x13TransactionRequests\x12K\n" +
	"\brequests\x18\x01 \x03(\v2/.iota.grpc.v1.ledger_service.TransactionRequestR\brequests:\b\x82\xb5\x18\x04with\"\xa3\x02\n" +
	"\x16GetTransactionsRequest\x12Q\n" +
	"\brequests\x18\x01 \x01(\v20.iota.grpc.v1.ledger_service.TransactionRequestsH\x00R\brequests\x88\x01\x01\x12<\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskH\x01R\breadMask\x88\x01\x01\x128\n" +
	"\x16max_message_size_bytes\x18\x03 \x01(\rH\x02R\x13maxMessageSizeBytes\x88\x01\x01:\b\x82\xb5\x18\x04withB\v\n" +
	"\t_requestsB\f\n" +
	"\n" +
	"_read_maskB\x19\n" +
	"\x17_max_message_size_bytes\"\xb7\x01\n" +
	"\x11TransactionResult\x12b\n" +
	"\x14executed_transaction\x18\x01 \x01(\v2-.iota.grpc.v1.transaction.ExecutedTransactionH\x00R\x13executedTransaction\x12*\n" +
	"\x05error\x18\x02 \x01(\v2\x12.google.rpc.StatusH\x00R\x05error:\b\x82\xb5\x18\x04withB\b\n" +
	"\x06result\"\x9f\x01\n" +
	"\x17GetTransactionsResponse\x12_\n" +
	"\x13transaction_results\x18\x01 \x03(\v2..iota.grpc.v1.ledger_service.TransactionResultR\x12transactionResults\x12\x19\n" +
	"\bhas_next\x18\x02 \x01(\bR\ahasNext:\b\x82\xb5\x18\x04with\"\xa1\x04\n" +
	"\x14GetCheckpointRequest\x12\x18\n" +
	"\x06latest\x18\x01 \x01(\bH\x00R\x06latest\x12)\n" +
	"\x0fsequence_number\x18\x02 \x01(\x04H\x00R\x0esequenceNumber\x124\n" +
	"\x06digest\x18\x03 \x01(\v2\x1a.iota.grpc.v1.types.DigestH\x00R\x06digest\x12<\n" +
	"\tread_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskH\x01R\breadMask\x88\x01\x01\x12\\\n" +
	"\x13transactions_filter\x18\x05 \x01(\v2&.iota.grpc.v1.filter.TransactionFilterH\x02R\x12transactionsFilter\x88\x01\x01\x12J\n" +
	"\revents_filter\x18\x06 \x01(\v2 .iota.grpc.v1.filter.EventFilterH\x03R\feventsFilter\x88\x01\x01\x128\n" +
	"\x16max_message_size_bytes\x18\a \x01(\rH\x04R\x13maxMessageSizeBytes\x88\x01\x01:\b\x82\xb5\x18\x04withB\x0f\n" +
	"\rcheckpoint_idB\f\n" +
	"\n" +
	"_read_maskB\x16\n" +
	"\x14_transactions_filterB\x10\n" +
	"\x0e_events_filterB\x19\n" +
	"\x17_max_message_size_bytes\"\xd4\x05\n" +
	"\x18StreamCheckpointsRequest\x127\n" +
	"\x15start_sequence_number\x18\x01 \x01(\x04H\x00R\x13startSequenceNumber\x88\x01\x01\x123\n" +
	"\x13end_sequence_number\x18\x02 \x01(\x04H\x01R\x11endSequenceNumber\x88\x01\x01\x12<\n" +
	"\tread_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskH\x02R\breadMask\x88\x01\x01\x12\\\n" +
	"\x13transactions_filter\x18\x04 \x01(\v2&.iota.grpc.v1.filter.TransactionFilterH\x03R\x12transactionsFilter\x88\x01\x01\x12J\n" +
	"\revents_filter\x18\x05 \x01(\v2 .iota.grpc.v1.filter.EventFilterH\x04R\feventsFilter\x88\x01\x01\x122\n" +
	"\x12filter_checkpoints\x18\x06 \x01(\bH\x05R\x11filterCheckpoints\x88\x01\x01\x125\n" +
	"\x14progress_interval_ms\x18\a \x01(\rH\x06R\x12progressIntervalMs\x88\x01\x01\x128\n" +
	"\x16max_message_size_bytes\x18\b \x01(\rH\aR\x13maxMessageSizeBytes\x88\x01\x01:\b\x82\xb5\x18\x04withB\x18\n" +
	"\x16_start_sequence_numberB\x16\n" +
	"\x14_end_sequence_numberB\f\n" +
	"\n" +
	"_read_maskB\x16\n" +
	"\x14_transactions_filterB\x10\n" +
	"\x0e_events_filterB\x15\n" +
	"\x13_filter_checkpointsB\x17\n" +
	"\x15_progress_interval_msB\x19\n" +
	"\x17_max_message_size_bytes\"\xe9\x04\n" +
	"\x0eCheckpointData\x12E\n" +
	"\n" +
	"checkpoint\x18\x01 \x01(\v2#.iota.grpc.v1.checkpoint.CheckpointH\x00R\n" +
	"checkpoint\x12e\n" +
	"\x15executed_transactions\x18\x02 \x01(\v2..iota.grpc.v1.transaction.ExecutedTransactionsH\x00R\x14executedTransactions\x124\n" +
	"\x06events\x18\x03 \x01(\v2\x1a.iota.grpc.v1.event.EventsH\x00R\x06events\x12R\n" +
	"\bprogress\x18\x04 \x01(\v24.iota.grpc.v1.ledger_service.CheckpointData.ProgressH\x00R\bprogress\x12V\n" +
	"\n" +
	"end_marker\x18\x05 \x01(\v25.iota.grpc.v1.ledger_service.CheckpointData.EndMarkerH\x00R\tendMarker\x1aY\n" +
	"\bProgress\x12C\n" +
	"\x1elatest_scanned_sequence_number\x18\x01 \x01(\x04R\x1blatestScannedSequenceNumber:\b\x82\xb5\x18\x04with\x1aW\n" +
	"\tEndMarker\x12,\n" +
	"\x0fsequence_number\x18\x01 \x01(\x04H\x00R\x0esequenceNumber\x88\x01\x01:\b\x82\xb5\x18\x04withB\x12\n" +
	"\x10_sequence_number:\b\x82\xb5\x18\x04withB\t\n" +
	"\apayload\"\x8c\x01\n" +
	"\x0fGetEpochRequest\x12\x19\n" +
	"\x05epoch\x18\x01 \x01(\x04H\x00R\x05epoch\x88\x01\x01\x12<\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskH\x01R\breadMask\x88\x01\x01:\b\x82\xb5\x18\x04withB\b\n" +
	"\x06_epochB\f\n" +
	"\n" +
	"_read_mask\"\\\n" +
	"\x10GetEpochResponse\x124\n" +
	"\x05epoch\x18\x01 \x01(\v2\x19.iota.grpc.v1.epoch.EpochH\x00R\x05epoch\x88\x01\x01:\b\x82\xb5\x18\x04withB\b\n" +
	"\x06_epoch2\xbe\x06\n" +
	"\rLedgerService\x12j\n" +
	"\tGetHealth\x12-.iota.grpc.v1.ledger_service.GetHealthRequest\x1a..iota.grpc.v1.ledger_service.GetHealthResponse\x12y\n" +
	"\x0eGetServiceInfo\x122.iota.grpc.v1.ledger_service.GetServiceInfoRequest\x1a3.iota.grpc.v1.ledger_service.GetServiceInfoResponse\x12o\n" +
	"\n" +
	"GetObjects\x12..iota.grpc.v1.ledger_service.GetObjectsRequest\x1a/.iota.grpc.v1.ledger_service.GetObjectsResponse0\x01\x12~\n" +
	"\x0fGetTransactions\x123.iota.grpc.v1.ledger_service.GetTransactionsRequest\x1a4.iota.grpc.v1.ledger_service.GetTransactionsResponse0\x01\x12q\n" +
	"\rGetCheckpoint\x121.iota.grpc.v1.ledger_service.GetCheckpointRequest\x1a+.iota.grpc.v1.ledger_service.CheckpointData0\x01\x12y\n" +
	"\x11StreamCheckpoints\x125.iota.grpc.v1.ledger_service.StreamCheckpointsRequest\x1a+.iota.grpc.v1.ledger_service.CheckpointData0\x01\x12g\n" +
	"\bGetEpoch\x12,.iota.grpc.v1.ledger_service.GetEpochRequest\x1a-.iota.grpc.v1.ledger_service.GetEpochResponseb\x06proto3"

var (
	file_iota_grpc_v1_ledger_service_proto_rawDescOnce sync.Once
	file_iota_grpc_v1_ledger_service_proto_rawDescData []byte
)

func file_iota_grpc_v1_ledger_service_proto_rawDescGZIP() []byte {
	file_iota_grpc_v1_ledger_service_proto_rawDescOnce.Do(func() {
		file_iota_grpc_v1_ledger_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_ledger_service_proto_rawDesc), len(file_iota_grpc_v1_ledger_service_proto_rawDesc)))
	})
	return file_iota_grpc_v1_ledger_service_proto_rawDescData
}

var file_iota_grpc_v1_ledger_service_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_iota_grpc_v1_ledger_service_proto_goTypes = []any{
	(*GetHealthRequest)(nil),                 // 0: iota.grpc.v1.ledger_service.GetHealthRequest
	(*GetHealthResponse)(nil),                // 1: iota.grpc.v1.ledger_service.GetHealthResponse
	(*GetServiceInfoRequest)(nil),            // 2: iota.grpc.v1.ledger_service.GetServiceInfoRequest
	(*GetServiceInfoResponse)(nil),           // 3: iota.grpc.v1.ledger_service.GetServiceInfoResponse
	(*ObjectRequest)(nil),                    // 4: iota.grpc.v1.ledger_service.ObjectRequest
	(*ObjectRequests)(nil),                   // 5: iota.grpc.v1.ledger_service.ObjectRequests
	(*GetObjectsRequest)(nil),                // 6: iota.grpc.v1.ledger_service.GetObjectsRequest
	(*ObjectResult)(nil),                     // 7: iota.grpc.v1.ledger_service.ObjectResult
	(*GetObjectsResponse)(nil),               // 8: iota.grpc.v1.ledger_service.GetObjectsResponse
	(*TransactionRequest)(nil),               // 9: iota.grpc.v1.ledger_service.TransactionRequest
	(*TransactionRequests)(nil),              // 10: iota.grpc.v1.ledger_service.TransactionRequests
	(*GetTransactionsRequest)(nil),           // 11: iota.grpc.v1.ledger_service.GetTransactionsRequest
	(*TransactionResult)(nil),                // 12: iota.grpc.v1.ledger_service.TransactionResult
	(*GetTransactionsResponse)(nil),          // 13: iota.grpc.v1.ledger_service.GetTransactionsResponse
	(*GetCheckpointRequest)(nil),             // 14: iota.grpc.v1.ledger_service.GetCheckpointRequest
	(*StreamCheckpointsRequest)(nil),         // 15: iota.grpc.v1.ledger_service.StreamCheckpointsRequest
	(*CheckpointData)(nil),                   // 16: iota.grpc.v1.ledger_service.CheckpointData
	(*GetEpochRequest)(nil),                  // 17: iota.grpc.v1.ledger_service.GetEpochRequest
	(*GetEpochResponse)(nil),                 // 18: iota.grpc.v1.ledger_service.GetEpochResponse
	(*CheckpointData_Progress)(nil),          // 19: iota.grpc.v1.ledger_service.CheckpointData.Progress
	(*CheckpointData_EndMarker)(nil),         // 20: iota.grpc.v1.ledger_service.CheckpointData.EndMarker
	(*fieldmaskpb.FieldMask)(nil),            // 21: google.protobuf.FieldMask
	(*types.Digest)(nil),                     // 22: iota.grpc.v1.types.Digest
	(*timestamppb.Timestamp)(nil),            // 23: google.protobuf.Timestamp
	(*types.ObjectReference)(nil),            // 24: iota.grpc.v1.types.ObjectReference
	(*object.Object)(nil),                    // 25: iota.grpc.v1.object.Object
	(*status.Status)(nil),                    // 26: google.rpc.Status
	(*transaction.ExecutedTransaction)(nil),  // 27: iota.grpc.v1.transaction.ExecutedTransaction
	(*filter.TransactionFilter)(nil),         // 28: iota.grpc.v1.filter.TransactionFilter
	(*filter.EventFilter)(nil),               // 29: iota.grpc.v1.filter.EventFilter
	(*checkpoint.Checkpoint)(nil),            // 30: iota.grpc.v1.checkpoint.Checkpoint
	(*transaction.ExecutedTransactions)(nil), // 31: iota.grpc.v1.transaction.ExecutedTransactions
	(*event.Events)(nil),                     // 32: iota.grpc.v1.event.Events
	(*epoch.Epoch)(nil),                      // 33: iota.grpc.v1.epoch.Epoch
}
var file_iota_grpc_v1_ledger_service_proto_depIdxs = []int32{
	21, // 0: iota.grpc.v1.ledger_service.GetServiceInfoRequest.read_mask:type_name -> google.protobuf.FieldMask
	22, // 1: iota.grpc.v1.ledger_service.GetServiceInfoResponse.chain_id:type_name -> iota.grpc.v1.types.Digest
	23, // 2: iota.grpc.v1.ledger_service.GetServiceInfoResponse.executed_checkpoint_timestamp:type_name -> google.protobuf.Timestamp
	24, // 3: iota.grpc.v1.ledger_service.ObjectRequest.object_ref:type_name -> iota.grpc.v1.types.ObjectReference
	4,  // 4: iota.grpc.v1.ledger_service.ObjectRequests.requests:type_name -> iota.grpc.v1.ledger_service.ObjectRequest
	5,  // 5: iota.grpc.v1.ledger_service.GetObjectsRequest.requests:type_name -> iota.grpc.v1.ledger_service.ObjectRequests
	21, // 6: iota.grpc.v1.ledger_service.GetObjectsRequest.read_mask:type_name -> google.protobuf.FieldMask
	25, // 7: iota.grpc.v1.ledger_service.ObjectResult.object:type_name -> iota.grpc.v1.object.Object
	26, // 8: iota.grpc.v1.ledger_service.ObjectResult.error:type_name -> google.rpc.Status
	7,  // 9: iota.grpc.v1.ledger_service.GetObjectsResponse.objects:type_name -> iota.grpc.v1.ledger_service.ObjectResult
	22, // 10: iota.grpc.v1.ledger_service.TransactionRequest.digest:type_name -> iota.grpc.v1.types.Digest
	9,  // 11: iota.grpc.v1.ledger_service.TransactionRequests.requests:type_name -> iota.grpc.v1.ledger_service.TransactionRequest
	10, // 12: iota.grpc.v1.ledger_service.GetTransactionsRequest.requests:type_name -> iota.grpc.v1.ledger_service.TransactionRequests
	21, // 13: iota.grpc.v1.ledger_service.GetTransactionsRequest.read_mask:type_name -> google.protobuf.FieldMask
	27, // 14: iota.grpc.v1.ledger_service.TransactionResult.executed_transaction:type_name -> iota.grpc.v1.transaction.ExecutedTransaction
	26, // 15: iota.grpc.v1.ledger_service.TransactionResult.error:type_name -> google.rpc.Status
	12, // 16: iota.grpc.v1.ledger_service.GetTransactionsResponse.transaction_results:type_name -> iota.grpc.v1.ledger_service.TransactionResult
	22, // 17: iota.grpc.v1.ledger_service.GetCheckpointRequest.digest:type_name -> iota.grpc.v1.types.Digest
	21, // 18: iota.grpc.v1.ledger_service.GetCheckpointRequest.read_mask:type_name -> google.protobuf.FieldMask
	28, // 19: iota.grpc.v1.ledger_service.GetCheckpointRequest.transactions_filter:type_name -> iota.grpc.v1.filter.TransactionFilter
	29, // 20: iota.grpc.v1.ledger_service.GetCheckpointRequest.events_filter:type_name -> iota.grpc.v1.filter.EventFilter
	21, // 21: iota.grpc.v1.ledger_service.StreamCheckpointsRequest.read_mask:type_name -> google.protobuf.FieldMask
	28, // 22: iota.grpc.v1.ledger_service.StreamCheckpointsRequest.transactions_filter:type_name -> iota.grpc.v1.filter.TransactionFilter
	29, // 23: iota.grpc.v1.ledger_service.StreamCheckpointsRequest.events_filter:type_name -> iota.grpc.v1.filter.EventFilter
	30, // 24: iota.grpc.v1.ledger_service.CheckpointData.checkpoint:type_name -> iota.grpc.v1.checkpoint.Checkpoint
	31, // 25: iota.grpc.v1.ledger_service.CheckpointData.executed_transactions:type_name -> iota.grpc.v1.transaction.ExecutedTransactions
	32, // 26: iota.grpc.v1.ledger_service.CheckpointData.events:type_name -> iota.grpc.v1.event.Events
	19, // 27: iota.grpc.v1.ledger_service.CheckpointData.progress:type_name -> iota.grpc.v1.ledger_service.CheckpointData.Progress
	20, // 28: iota.grpc.v1.ledger_service.CheckpointData.end_marker:type_name -> iota.grpc.v1.ledger_service.CheckpointData.EndMarker
	21, // 29: iota.grpc.v1.ledger_service.GetEpochRequest.read_mask:type_name -> google.protobuf.FieldMask
	33, // 30: iota.grpc.v1.ledger_service.GetEpochResponse.epoch:type_name -> iota.grpc.v1.epoch.Epoch
	0,  // 31: iota.grpc.v1.ledger_service.LedgerService.GetHealth:input_type -> iota.grpc.v1.ledger_service.GetHealthRequest
	2,  // 32: iota.grpc.v1.ledger_service.LedgerService.GetServiceInfo:input_type -> iota.grpc.v1.ledger_service.GetServiceInfoRequest
	6,  // 33: iota.grpc.v1.ledger_service.LedgerService.GetObjects:input_type -> iota.grpc.v1.ledger_service.GetObjectsRequest
	11, // 34: iota.grpc.v1.ledger_service.LedgerService.GetTransactions:input_type -> iota.grpc.v1.ledger_service.GetTransactionsRequest
	14, // 35: iota.grpc.v1.ledger_service.LedgerService.GetCheckpoint:input_type -> iota.grpc.v1.ledger_service.GetCheckpointRequest
	15, // 36: iota.grpc.v1.ledger_service.LedgerService.StreamCheckpoints:input_type -> iota.grpc.v1.ledger_service.StreamCheckpointsRequest
	17, // 37: iota.grpc.v1.ledger_service.LedgerService.GetEpoch:input_type -> iota.grpc.v1.ledger_service.GetEpochRequest
	1,  // 38: iota.grpc.v1.ledger_service.LedgerService.GetHealth:output_type -> iota.grpc.v1.ledger_service.GetHealthResponse
	3,  // 39: iota.grpc.v1.ledger_service.LedgerService.GetServiceInfo:output_type -> iota.grpc.v1.ledger_service.GetServiceInfoResponse
	8,  // 40: iota.grpc.v1.ledger_service.LedgerService.GetObjects:output_type -> iota.grpc.v1.ledger_service.GetObjectsResponse
	13, // 41: iota.grpc.v1.ledger_service.LedgerService.GetTransactions:output_type -> iota.grpc.v1.ledger_service.GetTransactionsResponse
	16, // 42: iota.grpc.v1.ledger_service.LedgerService.GetCheckpoint:output_type -> iota.grpc.v1.ledger_service.CheckpointData
	16, // 43: iota.grpc.v1.ledger_service.LedgerService.StreamCheckpoints:output_type -> iota.grpc.v1.ledger_service.CheckpointData
	18, // 44: iota.grpc.v1.ledger_service.LedgerService.GetEpoch:output_type -> iota.grpc.v1.ledger_service.GetEpochResponse
	38, // [38:45] is the sub-list for method output_type
	31, // [31:38] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_iota_grpc_v1_ledger_service_proto_init() }
func file_iota_grpc_v1_ledger_service_proto_init() {
	if File_iota_grpc_v1_ledger_service_proto != nil {
		return
	}
	file_iota_grpc_v1_ledger_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_iota_grpc_v1_ledger_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_iota_grpc_v1_ledger_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_iota_grpc_v1_ledger_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_iota_grpc_v1_ledger_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_iota_grpc_v1_ledger_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_iota_grpc_v1_ledger_service_proto_msgTypes[7].OneofWrappers = []any{
		(*ObjectResult_Object)(nil),
		(*ObjectResult_Error)(nil),
	}
	file_iota_grpc_v1_ledger_service_proto_msgTypes[9].OneofWrappers = []any{}
	file_iota_grpc_v1_ledger_service_proto_msgTypes[11].OneofWrappers = []any{}
	file_iota_grpc_v1_ledger_service_proto_msgTypes[12].OneofWrappers = []any{
		(*TransactionResult_ExecutedTransaction)(nil),
		(*TransactionResult_Error)(nil),
	}
	file_iota_grpc_v1_ledger_service_proto_msgTypes[14].OneofWrappers = []any{
		(*GetCheckpointRequest_Latest)(nil),
		(*GetCheckpointRequest_SequenceNumber)(nil),
		(*GetCheckpointRequest_Digest)(nil),
	}
	file_iota_grpc_v1_ledger_service_proto_msgTypes[15].OneofWrappers = []any{}
	file_iota_grpc_v1_ledger_service_proto_msgTypes[16].OneofWrappers = []any{
		(*CheckpointData_Checkpoint)(nil),
		(*CheckpointData_ExecutedTransactions)(nil),
		(*CheckpointData_Events)(nil),
		(*CheckpointData_Progress_)(nil),
		(*CheckpointData_EndMarker_)(nil),
	}
	file_iota_grpc_v1_ledger_service_proto_msgTypes[17].OneofWrappers = []any{}
	file_iota_grpc_v1_ledger_service_proto_msgTypes[18].OneofWrappers = []any{}
	file_iota_grpc_v1_ledger_service_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_ledger_service_proto_rawDesc), len(file_iota_grpc_v1_ledger_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iota_grpc_v1_ledger_service_proto_goTypes,
		DependencyIndexes: file_iota_grpc_v1_ledger_service_proto_depIdxs,
		MessageInfos:      file_iota_grpc_v1_ledger_service_proto_msgTypes,
	}.Build()
	File_iota_grpc_v1_ledger_service_proto = out.File
	file_iota_grpc_v1_ledger_service_proto_goTypes = nil
	file_iota_grpc_v1_ledger_service_proto_depIdxs = nil
}
