// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: iota/grpc/v1/object.proto

package object

import (
	_ "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/options"
	bcs "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/bcs"
	types "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An object on the IOTA blockchain.
type Object struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reference to this object.
	Reference *types.ObjectReference `protobuf:"bytes,1,opt,name=reference,proto3,oneof" json:"reference,omitempty"`
	// This Object serialized as BCS.
	Bcs           *bcs.BcsData `protobuf:"bytes,2,opt,name=bcs,proto3,oneof" json:"bcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Object) Reset() {
	*x = Object{}
	mi := &file_iota_grpc_v1_object_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_object_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_object_proto_rawDescGZIP(), []int{0}
}

func (x *Object) GetReference() *types.ObjectReference {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (x *Object) GetBcs() *bcs.BcsData {
	if x != nil {
		return x.Bcs
	}
	return nil
}

// A list of objects.
type Objects struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*Object              `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Objects) Reset() {
	*x = Objects{}
	mi := &file_iota_grpc_v1_object_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Objects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Objects) ProtoMessage() {}

func (x *Objects) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_object_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Objects.ProtoReflect.Descriptor instead.
func (*Objects) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_object_proto_rawDescGZIP(), []int{1}
}

func (x *Objects) GetObjects() []*Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

var File_iota_grpc_v1_object_proto protoreflect.FileDescriptor

const file_iota_grpc_v1_object_proto_rawDesc = "" +
	"\n" +
	"\x19iota/grpc/v1/object.proto\x12\x13iota.grpc.v1.object\x1a\x17iota/grpc/options.proto\x1a\x16iota/grpc/v1/bcs.proto\x1a\x18iota/grpc/v1/types.proto\"\x98\x01\n" +
	"\x06Object\x12F\n" +
	"\treference\x18\x01 \x01(\v2#.iota.grpc.v1.types.ObjectReferenceH\x00R\treference\x88\x01\x01\x120\n" +
	"\x03bcs\x18\x02 \x01(\v2\x19.iota.grpc.v1.bcs.BcsDataH\x01R\x03bcs\x88\x01\x01B\f\n" +
	"\n" +
	"_referenceB\x06\n" +
	"\x04_bcs\"F\n" +
	"\aObjects\x125\n" +
	"\aobjects\x18\x01 \x03(\v2\x1b.iota.grpc.v1.object.ObjectR\aobjects:\x04\x90\xb5\x18\x01b\x06proto3"

var (
	file_iota_grpc_v1_object_proto_rawDescOnce sync.Once
	file_iota_grpc_v1_object_proto_rawDescData []byte
)

func file_iota_grpc_v1_object_proto_rawDescGZIP() []byte {
	file_iota_grpc_v1_object_proto_rawDescOnce.Do(func() {
		file_iota_grpc_v1_object_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_object_proto_rawDesc), len(file_iota_grpc_v1_object_proto_rawDesc)))
	})
	return file_iota_grpc_v1_object_proto_rawDescData
}

var file_iota_grpc_v1_object_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_iota_grpc_v1_object_proto_goTypes = []any{
	(*Object)(nil),                // 0: iota.grpc.v1.object.Object
	(*Objects)(nil),               // 1: iota.grpc.v1.object.Objects
	(*types.ObjectReference)(nil), // 2: iota.grpc.v1.types.ObjectReference
	(*bcs.BcsData)(nil),           // 3: iota.grpc.v1.bcs.BcsData
}
var file_iota_grpc_v1_object_proto_depIdxs = []int32{
	2, // 0: iota.grpc.v1.object.Object.reference:type_name -> iota.grpc.v1.types.ObjectReference
	3, // 1: iota.grpc.v1.object.Object.bcs:type_name -> iota.grpc.v1.bcs.BcsData
	0, // 2: iota.grpc.v1.object.Objects.objects:type_name -> iota.grpc.v1.object.Object
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_iota_grpc_v1_object_proto_init() }
func file_iota_grpc_v1_object_proto_init() {
	if File_iota_grpc_v1_object_proto != nil {
		return
	}
	file_iota_grpc_v1_object_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_object_proto_rawDesc), len(file_iota_grpc_v1_object_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_iota_grpc_v1_object_proto_goTypes,
		DependencyIndexes: file_iota_grpc_v1_object_proto_depIdxs,
		MessageInfos:      file_iota_grpc_v1_object_proto_msgTypes,
	}.Build()
	File_iota_grpc_v1_object_proto = out.File
	file_iota_grpc_v1_object_proto_goTypes = nil
	file_iota_grpc_v1_object_proto_depIdxs = nil
}
