// Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: iota/grpc/v1/filter.proto

package filter

import (
	_ "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/options"
	_ "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/bcs"
	types "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionKind int32

const (
	// `SYSTEM_TRANSACTION` can be used to filter for all types of system transactions.
	TransactionKind_SYSTEM_TRANSACTION           TransactionKind = 0
	TransactionKind_PROGRAMMABLE_TRANSACTION     TransactionKind = 1
	TransactionKind_GENESIS                      TransactionKind = 2
	TransactionKind_CONSENSUS_COMMIT_PROLOGUE_V1 TransactionKind = 3
	TransactionKind_END_OF_EPOCH_TRANSACTION     TransactionKind = 5
	TransactionKind_RANDOMNESS_STATE_UPDATE      TransactionKind = 6
)

// Enum value maps for TransactionKind.
var (
	TransactionKind_name = map[int32]string{
		0: "SYSTEM_TRANSACTION",
		1: "PROGRAMMABLE_TRANSACTION",
		2: "GENESIS",
		3: "CONSENSUS_COMMIT_PROLOGUE_V1",
		5: "END_OF_EPOCH_TRANSACTION",
		6: "RANDOMNESS_STATE_UPDATE",
	}
	TransactionKind_value = map[string]int32{
		"SYSTEM_TRANSACTION":           0,
		"PROGRAMMABLE_TRANSACTION":     1,
		"GENESIS":                      2,
		"CONSENSUS_COMMIT_PROLOGUE_V1": 3,
		"END_OF_EPOCH_TRANSACTION":     5,
		"RANDOMNESS_STATE_UPDATE":      6,
	}
)

func (x TransactionKind) Enum() *TransactionKind {
	p := new(TransactionKind)
	*p = x
	return p
}

func (x TransactionKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionKind) Descriptor() protoreflect.EnumDescriptor {
	return file_iota_grpc_v1_filter_proto_enumTypes[0].Descriptor()
}

func (TransactionKind) Type() protoreflect.EnumType {
	return &file_iota_grpc_v1_filter_proto_enumTypes[0]
}

func (x TransactionKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionKind.Descriptor instead.
func (TransactionKind) EnumDescriptor() ([]byte, []int) {
	return file_iota_grpc_v1_filter_proto_rawDescGZIP(), []int{0}
}

// Logical AND of several filters.
type AllEventFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*EventFilter         `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllEventFilter) Reset() {
	*x = AllEventFilter{}
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllEventFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllEventFilter) ProtoMessage() {}

func (x *AllEventFilter) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllEventFilter.ProtoReflect.Descriptor instead.
func (*AllEventFilter) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_filter_proto_rawDescGZIP(), []int{0}
}

func (x *AllEventFilter) GetFilters() []*EventFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

// Logical OR of several filters.
type AnyEventFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*EventFilter         `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnyEventFilter) Reset() {
	*x = AnyEventFilter{}
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyEventFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyEventFilter) ProtoMessage() {}

func (x *AnyEventFilter) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyEventFilter.ProtoReflect.Descriptor instead.
func (*AnyEventFilter) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_filter_proto_rawDescGZIP(), []int{1}
}

func (x *AnyEventFilter) GetFilters() []*EventFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

// Logical NOT of a filter.
type NotEventFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *EventFilter           `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotEventFilter) Reset() {
	*x = NotEventFilter{}
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotEventFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotEventFilter) ProtoMessage() {}

func (x *NotEventFilter) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotEventFilter.ProtoReflect.Descriptor instead.
func (*NotEventFilter) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_filter_proto_rawDescGZIP(), []int{2}
}

func (x *NotEventFilter) GetFilter() *EventFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// Filter by address.
type AddressFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *types.Address         `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressFilter) Reset() {
	*x = AddressFilter{}
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressFilter) ProtoMessage() {}

func (x *AddressFilter) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressFilter.ProtoReflect.Descriptor instead.
func (*AddressFilter) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_filter_proto_rawDescGZIP(), []int{3}
}

func (x *AddressFilter) GetAddress() *types.Address {
	if x != nil {
		return x.Address
	}
	return nil
}

// Filter by Move package + module (optional).
type MovePackageAndModuleFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageId     *types.ObjectId        `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	Module        *string                `protobuf:"bytes,2,opt,name=module,proto3,oneof" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovePackageAndModuleFilter) Reset() {
	*x = MovePackageAndModuleFilter{}
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovePackageAndModuleFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovePackageAndModuleFilter) ProtoMessage() {}

func (x *MovePackageAndModuleFilter) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovePackageAndModuleFilter.ProtoReflect.Descriptor instead.
func (*MovePackageAndModuleFilter) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_filter_proto_rawDescGZIP(), []int{4}
}

func (x *MovePackageAndModuleFilter) GetPackageId() *types.ObjectId {
	if x != nil {
		return x.PackageId
	}
	return nil
}

func (x *MovePackageAndModuleFilter) GetModule() string {
	if x != nil && x.Module != nil {
		return *x.Module
	}
	return ""
}

// Filter by the given Move event struct name (struct tag).
// For example, if the event is defined in `0xabcd::MyModule`, and named
// `Foo`, then the struct tag is `0xabcd::MyModule::Foo`.
type MoveEventTypeFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StructTag     string                 `protobuf:"bytes,1,opt,name=struct_tag,json=structTag,proto3" json:"struct_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveEventTypeFilter) Reset() {
	*x = MoveEventTypeFilter{}
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveEventTypeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveEventTypeFilter) ProtoMessage() {}

func (x *MoveEventTypeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveEventTypeFilter.ProtoReflect.Descriptor instead.
func (*MoveEventTypeFilter) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_filter_proto_rawDescGZIP(), []int{5}
}

func (x *MoveEventTypeFilter) GetStructTag() string {
	if x != nil {
		return x.StructTag
	}
	return ""
}

// Filter for events.
type EventFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Filter:
	//
	//	*EventFilter_All
	//	*EventFilter_Any
	//	*EventFilter_Negation
	//	*EventFilter_Sender
	//	*EventFilter_MovePackageAndModule
	//	*EventFilter_MoveEventPackageAndModule
	//	*EventFilter_MoveEventType
	Filter        isEventFilter_Filter `protobuf_oneof:"filter"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventFilter) Reset() {
	*x = EventFilter{}
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFilter) ProtoMessage() {}

func (x *EventFilter) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFilter.ProtoReflect.Descriptor instead.
func (*EventFilter) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_filter_proto_rawDescGZIP(), []int{6}
}

func (x *EventFilter) GetFilter() isEventFilter_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *EventFilter) GetAll() *AllEventFilter {
	if x != nil {
		if x, ok := x.Filter.(*EventFilter_All); ok {
			return x.All
		}
	}
	return nil
}

func (x *EventFilter) GetAny() *AnyEventFilter {
	if x != nil {
		if x, ok := x.Filter.(*EventFilter_Any); ok {
			return x.Any
		}
	}
	return nil
}

func (x *EventFilter) GetNegation() *NotEventFilter {
	if x != nil {
		if x, ok := x.Filter.(*EventFilter_Negation); ok {
			return x.Negation
		}
	}
	return nil
}

func (x *EventFilter) GetSender() *AddressFilter {
	if x != nil {
		if x, ok := x.Filter.(*EventFilter_Sender); ok {
			return x.Sender
		}
	}
	return nil
}

func (x *EventFilter) GetMovePackageAndModule() *MovePackageAndModuleFilter {
	if x != nil {
		if x, ok := x.Filter.(*EventFilter_MovePackageAndModule); ok {
			return x.MovePackageAndModule
		}
	}
	return nil
}

func (x *EventFilter) GetMoveEventPackageAndModule() *MovePackageAndModuleFilter {
	if x != nil {
		if x, ok := x.Filter.(*EventFilter_MoveEventPackageAndModule); ok {
			return x.MoveEventPackageAndModule
		}
	}
	return nil
}

func (x *EventFilter) GetMoveEventType() *MoveEventTypeFilter {
	if x != nil {
		if x, ok := x.Filter.(*EventFilter_MoveEventType); ok {
			return x.MoveEventType
		}
	}
	return nil
}

type isEventFilter_Filter interface {
	isEventFilter_Filter()
}

type EventFilter_All struct {
	// Logical AND of several filters.
	All *AllEventFilter `protobuf:"bytes,1,opt,name=all,proto3,oneof"`
}

type EventFilter_Any struct {
	// Logical OR of several filters.
	Any *AnyEventFilter `protobuf:"bytes,2,opt,name=any,proto3,oneof"`
}

type EventFilter_Negation struct {
	// Logical NOT of a filter.
	Negation *NotEventFilter `protobuf:"bytes,3,opt,name=negation,proto3,oneof"`
}

type EventFilter_Sender struct {
	// Filter by sender address.
	Sender *AddressFilter `protobuf:"bytes,4,opt,name=sender,proto3,oneof"`
}

type EventFilter_MovePackageAndModule struct {
	// Return events emitted in a specified Move package + module (optional).
	// If the event is defined in PackageA::ModuleA but emitted in a tx with PackageB::ModuleB,
	// filtering `MovePackageAndModule` by PackageB::ModuleB returns the event.
	// Filtering `MoveEventPackageAndModule` by PackageA::ModuleA returns the event too.
	MovePackageAndModule *MovePackageAndModuleFilter `protobuf:"bytes,5,opt,name=move_package_and_module,json=movePackageAndModule,proto3,oneof"`
}

type EventFilter_MoveEventPackageAndModule struct {
	// Return events with the given Move package + module (optional) where the event struct is
	// defined. If the event is defined in PackageA::ModuleA but emitted in a tx
	// with PackageB::ModuleB, filtering `MoveEventPackageAndModule` by PackageA::ModuleA returns the
	// event. Filtering `MovePackageAndModule` by PackageB::ModuleB returns the event too.
	MoveEventPackageAndModule *MovePackageAndModuleFilter `protobuf:"bytes,6,opt,name=move_event_package_and_module,json=moveEventPackageAndModule,proto3,oneof"`
}

type EventFilter_MoveEventType struct {
	// Return events with the given Move event struct name (struct tag).
	// For example, if the event is defined in `0xabcd::MyModule`, and named
	// `Foo`, then the struct tag is `0xabcd::MyModule::Foo`.
	MoveEventType *MoveEventTypeFilter `protobuf:"bytes,7,opt,name=move_event_type,json=moveEventType,proto3,oneof"`
}

func (*EventFilter_All) isEventFilter_Filter() {}

func (*EventFilter_Any) isEventFilter_Filter() {}

func (*EventFilter_Negation) isEventFilter_Filter() {}

func (*EventFilter_Sender) isEventFilter_Filter() {}

func (*EventFilter_MovePackageAndModule) isEventFilter_Filter() {}

func (*EventFilter_MoveEventPackageAndModule) isEventFilter_Filter() {}

func (*EventFilter_MoveEventType) isEventFilter_Filter() {}

// Logical AND of several filters.
type AllTransactionFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*TransactionFilter   `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllTransactionFilter) Reset() {
	*x = AllTransactionFilter{}
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllTransactionFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllTransactionFilter) ProtoMessage() {}

func (x *AllTransactionFilter) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllTransactionFilter.ProtoReflect.Descriptor instead.
func (*AllTransactionFilter) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_filter_proto_rawDescGZIP(), []int{7}
}

func (x *AllTransactionFilter) GetFilters() []*TransactionFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

// Logical OR of several filters.
type AnyTransactionFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*TransactionFilter   `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnyTransactionFilter) Reset() {
	*x = AnyTransactionFilter{}
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyTransactionFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyTransactionFilter) ProtoMessage() {}

func (x *AnyTransactionFilter) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyTransactionFilter.ProtoReflect.Descriptor instead.
func (*AnyTransactionFilter) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_filter_proto_rawDescGZIP(), []int{8}
}

func (x *AnyTransactionFilter) GetFilters() []*TransactionFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

// Logical NOT of a filter.
type NotTransactionFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *TransactionFilter     `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotTransactionFilter) Reset() {
	*x = NotTransactionFilter{}
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotTransactionFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotTransactionFilter) ProtoMessage() {}

func (x *NotTransactionFilter) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotTransactionFilter.ProtoReflect.Descriptor instead.
func (*NotTransactionFilter) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_filter_proto_rawDescGZIP(), []int{9}
}

func (x *NotTransactionFilter) GetFilter() *TransactionFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// Filter by transaction kinds (any of the specified kinds).
type TransactionKindsFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kinds         []TransactionKind      `protobuf:"varint,1,rep,packed,name=kinds,proto3,enum=iota.grpc.v1.filter.TransactionKind" json:"kinds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionKindsFilter) Reset() {
	*x = TransactionKindsFilter{}
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionKindsFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionKindsFilter) ProtoMessage() {}

func (x *TransactionKindsFilter) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionKindsFilter.ProtoReflect.Descriptor instead.
func (*TransactionKindsFilter) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_filter_proto_rawDescGZIP(), []int{10}
}

func (x *TransactionKindsFilter) GetKinds() []TransactionKind {
	if x != nil {
		return x.Kinds
	}
	return nil
}

// Filter by input object ID.
type ObjectIdFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectRef     *types.ObjectReference `protobuf:"bytes,1,opt,name=object_ref,json=objectRef,proto3" json:"object_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectIdFilter) Reset() {
	*x = ObjectIdFilter{}
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectIdFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectIdFilter) ProtoMessage() {}

func (x *ObjectIdFilter) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectIdFilter.ProtoReflect.Descriptor instead.
func (*ObjectIdFilter) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_filter_proto_rawDescGZIP(), []int{11}
}

func (x *ObjectIdFilter) GetObjectRef() *types.ObjectReference {
	if x != nil {
		return x.ObjectRef
	}
	return nil
}

// Filter by move package, module (optional) and function (optional).
type MoveCallCommandFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageId     *types.ObjectId        `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	Module        *string                `protobuf:"bytes,2,opt,name=module,proto3,oneof" json:"module,omitempty"`
	Function      *string                `protobuf:"bytes,3,opt,name=function,proto3,oneof" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveCallCommandFilter) Reset() {
	*x = MoveCallCommandFilter{}
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveCallCommandFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveCallCommandFilter) ProtoMessage() {}

func (x *MoveCallCommandFilter) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveCallCommandFilter.ProtoReflect.Descriptor instead.
func (*MoveCallCommandFilter) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_filter_proto_rawDescGZIP(), []int{12}
}

func (x *MoveCallCommandFilter) GetPackageId() *types.ObjectId {
	if x != nil {
		return x.PackageId
	}
	return nil
}

func (x *MoveCallCommandFilter) GetModule() string {
	if x != nil && x.Module != nil {
		return *x.Module
	}
	return ""
}

func (x *MoveCallCommandFilter) GetFunction() string {
	if x != nil && x.Function != nil {
		return *x.Function
	}
	return ""
}

// Match a TransferObjects command.
type TransferObjectsCommandFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferObjectsCommandFilter) Reset() {
	*x = TransferObjectsCommandFilter{}
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferObjectsCommandFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferObjectsCommandFilter) ProtoMessage() {}

func (x *TransferObjectsCommandFilter) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferObjectsCommandFilter.ProtoReflect.Descriptor instead.
func (*TransferObjectsCommandFilter) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_filter_proto_rawDescGZIP(), []int{13}
}

// Match a SplitCoins command.
type SplitCoinsCommandFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitCoinsCommandFilter) Reset() {
	*x = SplitCoinsCommandFilter{}
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitCoinsCommandFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitCoinsCommandFilter) ProtoMessage() {}

func (x *SplitCoinsCommandFilter) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitCoinsCommandFilter.ProtoReflect.Descriptor instead.
func (*SplitCoinsCommandFilter) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_filter_proto_rawDescGZIP(), []int{14}
}

// Match a MergeCoins command.
type MergeCoinsCommandFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeCoinsCommandFilter) Reset() {
	*x = MergeCoinsCommandFilter{}
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeCoinsCommandFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeCoinsCommandFilter) ProtoMessage() {}

func (x *MergeCoinsCommandFilter) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeCoinsCommandFilter.ProtoReflect.Descriptor instead.
func (*MergeCoinsCommandFilter) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_filter_proto_rawDescGZIP(), []int{15}
}

// Match a Publish command.
type PublishCommandFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishCommandFilter) Reset() {
	*x = PublishCommandFilter{}
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishCommandFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishCommandFilter) ProtoMessage() {}

func (x *PublishCommandFilter) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishCommandFilter.ProtoReflect.Descriptor instead.
func (*PublishCommandFilter) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_filter_proto_rawDescGZIP(), []int{16}
}

// Match a MakeMoveVec command.
type MakeMoveVecCommandFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeMoveVecCommandFilter) Reset() {
	*x = MakeMoveVecCommandFilter{}
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeMoveVecCommandFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMoveVecCommandFilter) ProtoMessage() {}

func (x *MakeMoveVecCommandFilter) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMoveVecCommandFilter.ProtoReflect.Descriptor instead.
func (*MakeMoveVecCommandFilter) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_filter_proto_rawDescGZIP(), []int{17}
}

// Match an Upgrade command. Optionally filter by the specific package being upgraded.
type UpgradeCommandFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageId     *types.ObjectId        `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3,oneof" json:"package_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeCommandFilter) Reset() {
	*x = UpgradeCommandFilter{}
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeCommandFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeCommandFilter) ProtoMessage() {}

func (x *UpgradeCommandFilter) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeCommandFilter.ProtoReflect.Descriptor instead.
func (*UpgradeCommandFilter) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_filter_proto_rawDescGZIP(), []int{18}
}

func (x *UpgradeCommandFilter) GetPackageId() *types.ObjectId {
	if x != nil {
		return x.PackageId
	}
	return nil
}

// Filter by command type.
type CommandFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Filter:
	//
	//	*CommandFilter_MoveCall
	//	*CommandFilter_TransferObjects
	//	*CommandFilter_SplitCoins
	//	*CommandFilter_MergeCoins
	//	*CommandFilter_Publish
	//	*CommandFilter_MakeMoveVec
	//	*CommandFilter_Upgrade
	Filter        isCommandFilter_Filter `protobuf_oneof:"filter"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandFilter) Reset() {
	*x = CommandFilter{}
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandFilter) ProtoMessage() {}

func (x *CommandFilter) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandFilter.ProtoReflect.Descriptor instead.
func (*CommandFilter) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_filter_proto_rawDescGZIP(), []int{19}
}

func (x *CommandFilter) GetFilter() isCommandFilter_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *CommandFilter) GetMoveCall() *MoveCallCommandFilter {
	if x != nil {
		if x, ok := x.Filter.(*CommandFilter_MoveCall); ok {
			return x.MoveCall
		}
	}
	return nil
}

func (x *CommandFilter) GetTransferObjects() *TransferObjectsCommandFilter {
	if x != nil {
		if x, ok := x.Filter.(*CommandFilter_TransferObjects); ok {
			return x.TransferObjects
		}
	}
	return nil
}

func (x *CommandFilter) GetSplitCoins() *SplitCoinsCommandFilter {
	if x != nil {
		if x, ok := x.Filter.(*CommandFilter_SplitCoins); ok {
			return x.SplitCoins
		}
	}
	return nil
}

func (x *CommandFilter) GetMergeCoins() *MergeCoinsCommandFilter {
	if x != nil {
		if x, ok := x.Filter.(*CommandFilter_MergeCoins); ok {
			return x.MergeCoins
		}
	}
	return nil
}

func (x *CommandFilter) GetPublish() *PublishCommandFilter {
	if x != nil {
		if x, ok := x.Filter.(*CommandFilter_Publish); ok {
			return x.Publish
		}
	}
	return nil
}

func (x *CommandFilter) GetMakeMoveVec() *MakeMoveVecCommandFilter {
	if x != nil {
		if x, ok := x.Filter.(*CommandFilter_MakeMoveVec); ok {
			return x.MakeMoveVec
		}
	}
	return nil
}

func (x *CommandFilter) GetUpgrade() *UpgradeCommandFilter {
	if x != nil {
		if x, ok := x.Filter.(*CommandFilter_Upgrade); ok {
			return x.Upgrade
		}
	}
	return nil
}

type isCommandFilter_Filter interface {
	isCommandFilter_Filter()
}

type CommandFilter_MoveCall struct {
	MoveCall *MoveCallCommandFilter `protobuf:"bytes,1,opt,name=move_call,json=moveCall,proto3,oneof"`
}

type CommandFilter_TransferObjects struct {
	TransferObjects *TransferObjectsCommandFilter `protobuf:"bytes,2,opt,name=transfer_objects,json=transferObjects,proto3,oneof"`
}

type CommandFilter_SplitCoins struct {
	SplitCoins *SplitCoinsCommandFilter `protobuf:"bytes,3,opt,name=split_coins,json=splitCoins,proto3,oneof"`
}

type CommandFilter_MergeCoins struct {
	MergeCoins *MergeCoinsCommandFilter `protobuf:"bytes,4,opt,name=merge_coins,json=mergeCoins,proto3,oneof"`
}

type CommandFilter_Publish struct {
	Publish *PublishCommandFilter `protobuf:"bytes,5,opt,name=publish,proto3,oneof"`
}

type CommandFilter_MakeMoveVec struct {
	MakeMoveVec *MakeMoveVecCommandFilter `protobuf:"bytes,6,opt,name=make_move_vec,json=makeMoveVec,proto3,oneof"`
}

type CommandFilter_Upgrade struct {
	Upgrade *UpgradeCommandFilter `protobuf:"bytes,7,opt,name=upgrade,proto3,oneof"`
}

func (*CommandFilter_MoveCall) isCommandFilter_Filter() {}

func (*CommandFilter_TransferObjects) isCommandFilter_Filter() {}

func (*CommandFilter_SplitCoins) isCommandFilter_Filter() {}

func (*CommandFilter_MergeCoins) isCommandFilter_Filter() {}

func (*CommandFilter_Publish) isCommandFilter_Filter() {}

func (*CommandFilter_MakeMoveVec) isCommandFilter_Filter() {}

func (*CommandFilter_Upgrade) isCommandFilter_Filter() {}

// Filter by transaction execution status.
// Set `success` to `true` to match successful transactions,
// or `false` to match failed transactions (cancelled, execution error, etc.).
type ExecutionStatusFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionStatusFilter) Reset() {
	*x = ExecutionStatusFilter{}
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionStatusFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionStatusFilter) ProtoMessage() {}

func (x *ExecutionStatusFilter) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionStatusFilter.ProtoReflect.Descriptor instead.
func (*ExecutionStatusFilter) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_filter_proto_rawDescGZIP(), []int{20}
}

func (x *ExecutionStatusFilter) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Filter for transactions.
type TransactionFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Filter:
	//
	//	*TransactionFilter_All
	//	*TransactionFilter_Any
	//	*TransactionFilter_Negation
	//	*TransactionFilter_TransactionKinds
	//	*TransactionFilter_ExecutionStatus
	//	*TransactionFilter_Sender
	//	*TransactionFilter_Receiver
	//	*TransactionFilter_AffectedObject
	//	*TransactionFilter_Command
	//	*TransactionFilter_Event
	Filter        isTransactionFilter_Filter `protobuf_oneof:"filter"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionFilter) Reset() {
	*x = TransactionFilter{}
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionFilter) ProtoMessage() {}

func (x *TransactionFilter) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_filter_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionFilter.ProtoReflect.Descriptor instead.
func (*TransactionFilter) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_filter_proto_rawDescGZIP(), []int{21}
}

func (x *TransactionFilter) GetFilter() isTransactionFilter_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *TransactionFilter) GetAll() *AllTransactionFilter {
	if x != nil {
		if x, ok := x.Filter.(*TransactionFilter_All); ok {
			return x.All
		}
	}
	return nil
}

func (x *TransactionFilter) GetAny() *AnyTransactionFilter {
	if x != nil {
		if x, ok := x.Filter.(*TransactionFilter_Any); ok {
			return x.Any
		}
	}
	return nil
}

func (x *TransactionFilter) GetNegation() *NotTransactionFilter {
	if x != nil {
		if x, ok := x.Filter.(*TransactionFilter_Negation); ok {
			return x.Negation
		}
	}
	return nil
}

func (x *TransactionFilter) GetTransactionKinds() *TransactionKindsFilter {
	if x != nil {
		if x, ok := x.Filter.(*TransactionFilter_TransactionKinds); ok {
			return x.TransactionKinds
		}
	}
	return nil
}

func (x *TransactionFilter) GetExecutionStatus() *ExecutionStatusFilter {
	if x != nil {
		if x, ok := x.Filter.(*TransactionFilter_ExecutionStatus); ok {
			return x.ExecutionStatus
		}
	}
	return nil
}

func (x *TransactionFilter) GetSender() *AddressFilter {
	if x != nil {
		if x, ok := x.Filter.(*TransactionFilter_Sender); ok {
			return x.Sender
		}
	}
	return nil
}

func (x *TransactionFilter) GetReceiver() *AddressFilter {
	if x != nil {
		if x, ok := x.Filter.(*TransactionFilter_Receiver); ok {
			return x.Receiver
		}
	}
	return nil
}

func (x *TransactionFilter) GetAffectedObject() *ObjectIdFilter {
	if x != nil {
		if x, ok := x.Filter.(*TransactionFilter_AffectedObject); ok {
			return x.AffectedObject
		}
	}
	return nil
}

func (x *TransactionFilter) GetCommand() *CommandFilter {
	if x != nil {
		if x, ok := x.Filter.(*TransactionFilter_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *TransactionFilter) GetEvent() *EventFilter {
	if x != nil {
		if x, ok := x.Filter.(*TransactionFilter_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isTransactionFilter_Filter interface {
	isTransactionFilter_Filter()
}

type TransactionFilter_All struct {
	// Logical AND of several filters.
	All *AllTransactionFilter `protobuf:"bytes,1,opt,name=all,proto3,oneof"`
}

type TransactionFilter_Any struct {
	// Logical OR of several filters.
	Any *AnyTransactionFilter `protobuf:"bytes,2,opt,name=any,proto3,oneof"`
}

type TransactionFilter_Negation struct {
	// Logical NOT of a filter.
	Negation *NotTransactionFilter `protobuf:"bytes,3,opt,name=negation,proto3,oneof"`
}

type TransactionFilter_TransactionKinds struct {
	// Filter transactions of any given kind in the filter.
	TransactionKinds *TransactionKindsFilter `protobuf:"bytes,4,opt,name=transaction_kinds,json=transactionKinds,proto3,oneof"`
}

type TransactionFilter_ExecutionStatus struct {
	// Filter by transaction execution success/failure.
	ExecutionStatus *ExecutionStatusFilter `protobuf:"bytes,5,opt,name=execution_status,json=executionStatus,proto3,oneof"`
}

type TransactionFilter_Sender struct {
	// Filter by sender address.
	Sender *AddressFilter `protobuf:"bytes,6,opt,name=sender,proto3,oneof"`
}

type TransactionFilter_Receiver struct {
	// Filter by recipient address. The recipient is determined by
	// checking the owners of mutated and unwrapped objects.
	Receiver *AddressFilter `protobuf:"bytes,7,opt,name=receiver,proto3,oneof"`
}

type TransactionFilter_AffectedObject struct {
	// Filter for transactions that touch this object.
	AffectedObject *ObjectIdFilter `protobuf:"bytes,8,opt,name=affected_object,json=affectedObject,proto3,oneof"`
}

type TransactionFilter_Command struct {
	// Filter by command type.
	Command *CommandFilter `protobuf:"bytes,9,opt,name=command,proto3,oneof"`
}

type TransactionFilter_Event struct {
	// Filter transactions that contain events matching the given event filter.
	Event *EventFilter `protobuf:"bytes,10,opt,name=event,proto3,oneof"`
}

func (*TransactionFilter_All) isTransactionFilter_Filter() {}

func (*TransactionFilter_Any) isTransactionFilter_Filter() {}

func (*TransactionFilter_Negation) isTransactionFilter_Filter() {}

func (*TransactionFilter_TransactionKinds) isTransactionFilter_Filter() {}

func (*TransactionFilter_ExecutionStatus) isTransactionFilter_Filter() {}

func (*TransactionFilter_Sender) isTransactionFilter_Filter() {}

func (*TransactionFilter_Receiver) isTransactionFilter_Filter() {}

func (*TransactionFilter_AffectedObject) isTransactionFilter_Filter() {}

func (*TransactionFilter_Command) isTransactionFilter_Filter() {}

func (*TransactionFilter_Event) isTransactionFilter_Filter() {}

var File_iota_grpc_v1_filter_proto protoreflect.FileDescriptor

const file_iota_grpc_v1_filter_proto_rawDesc = "" +
	"\n" +
	"\x19iota/grpc/v1/filter.proto\x12\x13iota.grpc.v1.filter\x1a\x17iota/grpc/options.proto\x1a\x16iota/grpc/v1/bcs.proto\x1a\x18iota/grpc/v1/types.proto\"V\n" +
	"\x0eAllEventFilter\x12:\n" +
	"\afilters\x18\x01 \x03(\v2 .iota.grpc.v1.filter.EventFilterR\afilters:\b\x82\xb5\x18\x04with\"V\n" +
	"\x0eAnyEventFilter\x12:\n" +
	"\afilters\x18\x01 \x03(\v2 .iota.grpc.v1.filter.EventFilterR\afilters:\b\x82\xb5\x18\x04with\"T\n" +
	"\x0eNotEventFilter\x128\n" +
	"\x06filter\x18\x01 \x01(\v2 .iota.grpc.v1.filter.EventFilterR\x06filter:\b\x82\xb5\x18\x04with\"P\n" +
	"\rAddressFilter\x125\n" +
	"\aaddress\x18\x01 \x01(\v2\x1b.iota.grpc.v1.types.AddressR\aaddress:\b\x82\xb5\x18\x04with\"\x8b\x01\n" +
	"\x1aMovePackageAndModuleFilter\x12;\n" +
	"\n" +
	"package_id\x18\x01 \x01(\v2\x1c.iota.grpc.v1.types.ObjectIdR\tpackageId\x12\x1b\n" +
	"\x06module\x18\x02 \x01(\tH\x00R\x06module\x88\x01\x01:\b\x82\xb5\x18\x04withB\t\n" +
	"\a_module\">\n" +
	"\x13MoveEventTypeFilter\x12\x1d\n" +
	"\n" +
	"struct_tag\x18\x01 \x01(\tR\tstructTag:\b\x82\xb5\x18\x04with\"\xc7\x04\n" +
	"\vEventFilter\x127\n" +
	"\x03all\x18\x01 \x01(\v2#.iota.grpc.v1.filter.AllEventFilterH\x00R\x03all\x127\n" +
	"\x03any\x18\x02 \x01(\v2#.iota.grpc.v1.filter.AnyEventFilterH\x00R\x03any\x12A\n" +
	"\bnegation\x18\x03 \x01(\v2#.iota.grpc.v1.filter.NotEventFilterH\x00R\bnegation\x12<\n" +
	"\x06sender\x18\x04 \x01(\v2\".iota.grpc.v1.filter.AddressFilterH\x00R\x06sender\x12h\n" +
	"\x17move_package_and_module\x18\x05 \x01(\v2/.iota.grpc.v1.filter.MovePackageAndModuleFilterH\x00R\x14movePackageAndModule\x12s\n" +
	"\x1dmove_event_package_and_module\x18\x06 \x01(\v2/.iota.grpc.v1.filter.MovePackageAndModuleFilterH\x00R\x19moveEventPackageAndModule\x12R\n" +
	"\x0fmove_event_type\x18\a \x01(\v2(.iota.grpc.v1.filter.MoveEventTypeFilterH\x00R\rmoveEventType:\b\x82\xb5\x18\x04withB\b\n" +
	"\x06filter\"b\n" +
	"\x14AllTransactionFilter\x12@\n" +
	"\afilters\x18\x01 \x03(\v2&.iota.grpc.v1.filter.TransactionFilterR\afilters:\b\x82\xb5\x18\x04with\"b\n" +
	"\x14AnyTransactionFilter\x12@\n" +
	"\afilters\x18\x01 \x03(\v2&.iota.grpc.v1.filter.TransactionFilterR\afilters:\b\x82\xb5\x18\x04with\"`\n" +
	"\x14NotTransactionFilter\x12>\n" +
	"\x06filter\x18\x01 \x01(\v2&.iota.grpc.v1.filter.TransactionFilterR\x06filter:\b\x82\xb5\x18\x04with\"^\n" +
	"\x16TransactionKindsFilter\x12:\n" +
	"\x05kinds\x18\x01 \x03(\x0e2$.iota.grpc.v1.filter.TransactionKindR\x05kinds:\b\x82\xb5\x18\x04with\"^\n" +
	"\x0eObjectIdFilter\x12B\n" +
	"\n" +
	"object_ref\x18\x01 \x01(\v2#.iota.grpc.v1.types.ObjectReferenceR\tobjectRef:\b\x82\xb5\x18\x04with\"\xb4\x01\n" +
	"\x15MoveCallCommandFilter\x12;\n" +
	"\n" +
	"package_id\x18\x01 \x01(\v2\x1c.iota.grpc.v1.types.ObjectIdR\tpackageId\x12\x1b\n" +
	"\x06module\x18\x02 \x01(\tH\x00R\x06module\x88\x01\x01\x12\x1f\n" +
	"\bfunction\x18\x03 \x01(\tH\x01R\bfunction\x88\x01\x01:\b\x82\xb5\x18\x04withB\t\n" +
	"\a_moduleB\v\n" +
	"\t_function\"(\n" +
	"\x1cTransferObjectsCommandFilter:\b\x82\xb5\x18\x04with\"#\n" +
	"\x17SplitCoinsCommandFilter:\b\x82\xb5\x18\x04with\"#\n" +
	"\x17MergeCoinsCommandFilter:\b\x82\xb5\x18\x04with\" \n" +
	"\x14PublishCommandFilter:\b\x82\xb5\x18\x04with\"$\n" +
	"\x18MakeMoveVecCommandFilter:\b\x82\xb5\x18\x04with\"q\n" +
	"\x14UpgradeCommandFilter\x12@\n" +
	"\n" +
	"package_id\x18\x01 \x01(\v2\x1c.iota.grpc.v1.types.ObjectIdH\x00R\tpackageId\x88\x01\x01:\b\x82\xb5\x18\x04withB\r\n" +
	"\v_package_id\"\xd3\x04\n" +
	"\rCommandFilter\x12I\n" +
	"\tmove_call\x18\x01 \x01(\v2*.iota.grpc.v1.filter.MoveCallCommandFilterH\x00R\bmoveCall\x12^\n" +
	"\x10transfer_objects\x18\x02 \x01(\v21.iota.grpc.v1.filter.TransferObjectsCommandFilterH\x00R\x0ftransferObjects\x12O\n" +
	"\vsplit_coins\x18\x03 \x01(\v2,.iota.grpc.v1.filter.SplitCoinsCommandFilterH\x00R\n" +
	"splitCoins\x12O\n" +
	"\vmerge_coins\x18\x04 \x01(\v2,.iota.grpc.v1.filter.MergeCoinsCommandFilterH\x00R\n" +
	"mergeCoins\x12E\n" +
	"\apublish\x18\x05 \x01(\v2).iota.grpc.v1.filter.PublishCommandFilterH\x00R\apublish\x12S\n" +
	"\rmake_move_vec\x18\x06 \x01(\v2-.iota.grpc.v1.filter.MakeMoveVecCommandFilterH\x00R\vmakeMoveVec\x12E\n" +
	"\aupgrade\x18\a \x01(\v2).iota.grpc.v1.filter.UpgradeCommandFilterH\x00R\aupgrade:\b\x82\xb5\x18\x04withB\b\n" +
	"\x06filter\";\n" +
	"\x15ExecutionStatusFilter\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess:\b\x82\xb5\x18\x04with\"\xed\x05\n" +
	"\x11TransactionFilter\x12=\n" +
	"\x03all\x18\x01 \x01(\v2).iota.grpc.v1.filter.AllTransactionFilterH\x00R\x03all\x12=\n" +
	"\x03any\x18\x02 \x01(\v2).iota.grpc.v1.filter.AnyTransactionFilterH\x00R\x03any\x12G\n" +
	"\bnegation\x18\x03 \x01(\v2).iota.grpc.v1.filter.NotTransactionFilterH\x00R\bnegation\x12Z\n" +
	"\x11transaction_kinds\x18\x04 \x01(\v2+.iota.grpc.v1.filter.TransactionKindsFilterH\x00R\x10transactionKinds\x12W\n" +
	"\x10execution_status\x18\x05 \x01(\v2*.iota.grpc.v1.filter.ExecutionStatusFilterH\x00R\x0fexecutionStatus\x12<\n" +
	"\x06sender\x18\x06 \x01(\v2\".iota.grpc.v1.filter.AddressFilterH\x00R\x06sender\x12@\n" +
	"\breceiver\x18\a \x01(\v2\".iota.grpc.v1.filter.AddressFilterH\x00R\breceiver\x12N\n" +
	"\x0faffected_object\x18\b \x01(\v2#.iota.grpc.v1.filter.ObjectIdFilterH\x00R\x0eaffectedObject\x12>\n" +
	"\acommand\x18\t \x01(\v2\".iota.grpc.v1.filter.CommandFilterH\x00R\acommand\x128\n" +
	"\x05event\x18\n" +
	" \x01(\v2 .iota.grpc.v1.filter.EventFilterH\x00R\x05event:\b\x82\xb5\x18\x04withB\b\n" +
	"\x06filter*\xb1\x01\n" +
	"\x0fTransactionKind\x12\x16\n" +
	"\x12SYSTEM_TRANSACTION\x10\x00\x12\x1c\n" +
	"\x18PROGRAMMABLE_TRANSACTION\x10\x01\x12\v\n" +
	"\aGENESIS\x10\x02\x12 \n" +
	"\x1cCONSENSUS_COMMIT_PROLOGUE_V1\x10\x03\x12\x1c\n" +
	"\x18END_OF_EPOCH_TRANSACTION\x10\x05\x12\x1b\n" +
	"\x17RANDOMNESS_STATE_UPDATE\x10\x06b\x06proto3"

var (
	file_iota_grpc_v1_filter_proto_rawDescOnce sync.Once
	file_iota_grpc_v1_filter_proto_rawDescData []byte
)

func file_iota_grpc_v1_filter_proto_rawDescGZIP() []byte {
	file_iota_grpc_v1_filter_proto_rawDescOnce.Do(func() {
		file_iota_grpc_v1_filter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_filter_proto_rawDesc), len(file_iota_grpc_v1_filter_proto_rawDesc)))
	})
	return file_iota_grpc_v1_filter_proto_rawDescData
}

var file_iota_grpc_v1_filter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_iota_grpc_v1_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_iota_grpc_v1_filter_proto_goTypes = []any{
	(TransactionKind)(0),                 // 0: iota.grpc.v1.filter.TransactionKind
	(*AllEventFilter)(nil),               // 1: iota.grpc.v1.filter.AllEventFilter
	(*AnyEventFilter)(nil),               // 2: iota.grpc.v1.filter.AnyEventFilter
	(*NotEventFilter)(nil),               // 3: iota.grpc.v1.filter.NotEventFilter
	(*AddressFilter)(nil),                // 4: iota.grpc.v1.filter.AddressFilter
	(*MovePackageAndModuleFilter)(nil),   // 5: iota.grpc.v1.filter.MovePackageAndModuleFilter
	(*MoveEventTypeFilter)(nil),          // 6: iota.grpc.v1.filter.MoveEventTypeFilter
	(*EventFilter)(nil),                  // 7: iota.grpc.v1.filter.EventFilter
	(*AllTransactionFilter)(nil),         // 8: iota.grpc.v1.filter.AllTransactionFilter
	(*AnyTransactionFilter)(nil),         // 9: iota.grpc.v1.filter.AnyTransactionFilter
	(*NotTransactionFilter)(nil),         // 10: iota.grpc.v1.filter.NotTransactionFilter
	(*TransactionKindsFilter)(nil),       // 11: iota.grpc.v1.filter.TransactionKindsFilter
	(*ObjectIdFilter)(nil),               // 12: iota.grpc.v1.filter.ObjectIdFilter
	(*MoveCallCommandFilter)(nil),        // 13: iota.grpc.v1.filter.MoveCallCommandFilter
	(*TransferObjectsCommandFilter)(nil), // 14: iota.grpc.v1.filter.TransferObjectsCommandFilter
	(*SplitCoinsCommandFilter)(nil),      // 15: iota.grpc.v1.filter.SplitCoinsCommandFilter
	(*MergeCoinsCommandFilter)(nil),      // 16: iota.grpc.v1.filter.MergeCoinsCommandFilter
	(*PublishCommandFilter)(nil),         // 17: iota.grpc.v1.filter.PublishCommandFilter
	(*MakeMoveVecCommandFilter)(nil),     // 18: iota.grpc.v1.filter.MakeMoveVecCommandFilter
	(*UpgradeCommandFilter)(nil),         // 19: iota.grpc.v1.filter.UpgradeCommandFilter
	(*CommandFilter)(nil),                // 20: iota.grpc.v1.filter.CommandFilter
	(*ExecutionStatusFilter)(nil),        // 21: iota.grpc.v1.filter.ExecutionStatusFilter
	(*TransactionFilter)(nil),            // 22: iota.grpc.v1.filter.TransactionFilter
	(*types.Address)(nil),                // 23: iota.grpc.v1.types.Address
	(*types.ObjectId)(nil),               // 24: iota.grpc.v1.types.ObjectId
	(*types.ObjectReference)(nil),        // 25: iota.grpc.v1.types.ObjectReference
}
var file_iota_grpc_v1_filter_proto_depIdxs = []int32{
	7,  // 0: iota.grpc.v1.filter.AllEventFilter.filters:type_name -> iota.grpc.v1.filter.EventFilter
	7,  // 1: iota.grpc.v1.filter.AnyEventFilter.filters:type_name -> iota.grpc.v1.filter.EventFilter
	7,  // 2: iota.grpc.v1.filter.NotEventFilter.filter:type_name -> iota.grpc.v1.filter.EventFilter
	23, // 3: iota.grpc.v1.filter.AddressFilter.address:type_name -> iota.grpc.v1.types.Address
	24, // 4: iota.grpc.v1.filter.MovePackageAndModuleFilter.package_id:type_name -> iota.grpc.v1.types.ObjectId
	1,  // 5: iota.grpc.v1.filter.EventFilter.all:type_name -> iota.grpc.v1.filter.AllEventFilter
	2,  // 6: iota.grpc.v1.filter.EventFilter.any:type_name -> iota.grpc.v1.filter.AnyEventFilter
	3,  // 7: iota.grpc.v1.filter.EventFilter.negation:type_name -> iota.grpc.v1.filter.NotEventFilter
	4,  // 8: iota.grpc.v1.filter.EventFilter.sender:type_name -> iota.grpc.v1.filter.AddressFilter
	5,  // 9: iota.grpc.v1.filter.EventFilter.move_package_and_module:type_name -> iota.grpc.v1.filter.MovePackageAndModuleFilter
	5,  // 10: iota.grpc.v1.filter.EventFilter.move_event_package_and_module:type_name -> iota.grpc.v1.filter.MovePackageAndModuleFilter
	6,  // 11: iota.grpc.v1.filter.EventFilter.move_event_type:type_name -> iota.grpc.v1.filter.MoveEventTypeFilter
	22, // 12: iota.grpc.v1.filter.AllTransactionFilter.filters:type_name -> iota.grpc.v1.filter.TransactionFilter
	22, // 13: iota.grpc.v1.filter.AnyTransactionFilter.filters:type_name -> iota.grpc.v1.filter.TransactionFilter
	22, // 14: iota.grpc.v1.filter.NotTransactionFilter.filter:type_name -> iota.grpc.v1.filter.TransactionFilter
	0,  // 15: iota.grpc.v1.filter.TransactionKindsFilter.kinds:type_name -> iota.grpc.v1.filter.TransactionKind
	25, // 16: iota.grpc.v1.filter.ObjectIdFilter.object_ref:type_name -> iota.grpc.v1.types.ObjectReference
	24, // 17: iota.grpc.v1.filter.MoveCallCommandFilter.package_id:type_name -> iota.grpc.v1.types.ObjectId
	24, // 18: iota.grpc.v1.filter.UpgradeCommandFilter.package_id:type_name -> iota.grpc.v1.types.ObjectId
	13, // 19: iota.grpc.v1.filter.CommandFilter.move_call:type_name -> iota.grpc.v1.filter.MoveCallCommandFilter
	14, // 20: iota.grpc.v1.filter.CommandFilter.transfer_objects:type_name -> iota.grpc.v1.filter.TransferObjectsCommandFilter
	15, // 21: iota.grpc.v1.filter.CommandFilter.split_coins:type_name -> iota.grpc.v1.filter.SplitCoinsCommandFilter
	16, // 22: iota.grpc.v1.filter.CommandFilter.merge_coins:type_name -> iota.grpc.v1.filter.MergeCoinsCommandFilter
	17, // 23: iota.grpc.v1.filter.CommandFilter.publish:type_name -> iota.grpc.v1.filter.PublishCommandFilter
	18, // 24: iota.grpc.v1.filter.CommandFilter.make_move_vec:type_name -> iota.grpc.v1.filter.MakeMoveVecCommandFilter
	19, // 25: iota.grpc.v1.filter.CommandFilter.upgrade:type_name -> iota.grpc.v1.filter.UpgradeCommandFilter
	8,  // 26: iota.grpc.v1.filter.TransactionFilter.all:type_name -> iota.grpc.v1.filter.AllTransactionFilter
	9,  // 27: iota.grpc.v1.filter.TransactionFilter.any:type_name -> iota.grpc.v1.filter.AnyTransactionFilter
	10, // 28: iota.grpc.v1.filter.TransactionFilter.negation:type_name -> iota.grpc.v1.filter.NotTransactionFilter
	11, // 29: iota.grpc.v1.filter.TransactionFilter.transaction_kinds:type_name -> iota.grpc.v1.filter.TransactionKindsFilter
	21, // 30: iota.grpc.v1.filter.TransactionFilter.execution_status:type_name -> iota.grpc.v1.filter.ExecutionStatusFilter
	4,  // 31: iota.grpc.v1.filter.TransactionFilter.sender:type_name -> iota.grpc.v1.filter.AddressFilter
	4,  // 32: iota.grpc.v1.filter.TransactionFilter.receiver:type_name -> iota.grpc.v1.filter.AddressFilter
	12, // 33: iota.grpc.v1.filter.TransactionFilter.affected_object:type_name -> iota.grpc.v1.filter.ObjectIdFilter
	20, // 34: iota.grpc.v1.filter.TransactionFilter.command:type_name -> iota.grpc.v1.filter.CommandFilter
	7,  // 35: iota.grpc.v1.filter.TransactionFilter.event:type_name -> iota.grpc.v1.filter.EventFilter
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_iota_grpc_v1_filter_proto_init() }
func file_iota_grpc_v1_filter_proto_init() {
	if File_iota_grpc_v1_filter_proto != nil {
		return
	}
	file_iota_grpc_v1_filter_proto_msgTypes[4].OneofWrappers = []any{}
	file_iota_grpc_v1_filter_proto_msgTypes[6].OneofWrappers = []any{
		(*EventFilter_All)(nil),
		(*EventFilter_Any)(nil),
		(*EventFilter_Negation)(nil),
		(*EventFilter_Sender)(nil),
		(*EventFilter_MovePackageAndModule)(nil),
		(*EventFilter_MoveEventPackageAndModule)(nil),
		(*EventFilter_MoveEventType)(nil),
	}
	file_iota_grpc_v1_filter_proto_msgTypes[12].OneofWrappers = []any{}
	file_iota_grpc_v1_filter_proto_msgTypes[18].OneofWrappers = []any{}
	file_iota_grpc_v1_filter_proto_msgTypes[19].OneofWrappers = []any{
		(*CommandFilter_MoveCall)(nil),
		(*CommandFilter_TransferObjects)(nil),
		(*CommandFilter_SplitCoins)(nil),
		(*CommandFilter_MergeCoins)(nil),
		(*CommandFilter_Publish)(nil),
		(*CommandFilter_MakeMoveVec)(nil),
		(*CommandFilter_Upgrade)(nil),
	}
	file_iota_grpc_v1_filter_proto_msgTypes[21].OneofWrappers = []any{
		(*TransactionFilter_All)(nil),
		(*TransactionFilter_Any)(nil),
		(*TransactionFilter_Negation)(nil),
		(*TransactionFilter_TransactionKinds)(nil),
		(*TransactionFilter_ExecutionStatus)(nil),
		(*TransactionFilter_Sender)(nil),
		(*TransactionFilter_Receiver)(nil),
		(*TransactionFilter_AffectedObject)(nil),
		(*TransactionFilter_Command)(nil),
		(*TransactionFilter_Event)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_filter_proto_rawDesc), len(file_iota_grpc_v1_filter_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_iota_grpc_v1_filter_proto_goTypes,
		DependencyIndexes: file_iota_grpc_v1_filter_proto_depIdxs,
		EnumInfos:         file_iota_grpc_v1_filter_proto_enumTypes,
		MessageInfos:      file_iota_grpc_v1_filter_proto_msgTypes,
	}.Build()
	File_iota_grpc_v1_filter_proto = out.File
	file_iota_grpc_v1_filter_proto_goTypes = nil
	file_iota_grpc_v1_filter_proto_depIdxs = nil
}
