// Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: iota/grpc/v1/bcs.proto

package bcs

import (
	_ "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BCS-serialized data container
type BcsData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BcsData) Reset() {
	*x = BcsData{}
	mi := &file_iota_grpc_v1_bcs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BcsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BcsData) ProtoMessage() {}

func (x *BcsData) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_bcs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BcsData.ProtoReflect.Descriptor instead.
func (*BcsData) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_bcs_proto_rawDescGZIP(), []int{0}
}

func (x *BcsData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_iota_grpc_v1_bcs_proto protoreflect.FileDescriptor

const file_iota_grpc_v1_bcs_proto_rawDesc = "" +
	"\n" +
	"\x16iota/grpc/v1/bcs.proto\x12\x10iota.grpc.v1.bcs\x1a\x17iota/grpc/options.proto\"'\n" +
	"\aBcsData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data:\b\x82\xb5\x18\x04withb\x06proto3"

var (
	file_iota_grpc_v1_bcs_proto_rawDescOnce sync.Once
	file_iota_grpc_v1_bcs_proto_rawDescData []byte
)

func file_iota_grpc_v1_bcs_proto_rawDescGZIP() []byte {
	file_iota_grpc_v1_bcs_proto_rawDescOnce.Do(func() {
		file_iota_grpc_v1_bcs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_bcs_proto_rawDesc), len(file_iota_grpc_v1_bcs_proto_rawDesc)))
	})
	return file_iota_grpc_v1_bcs_proto_rawDescData
}

var file_iota_grpc_v1_bcs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_iota_grpc_v1_bcs_proto_goTypes = []any{
	(*BcsData)(nil), // 0: iota.grpc.v1.bcs.BcsData
}
var file_iota_grpc_v1_bcs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_iota_grpc_v1_bcs_proto_init() }
func file_iota_grpc_v1_bcs_proto_init() {
	if File_iota_grpc_v1_bcs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_bcs_proto_rawDesc), len(file_iota_grpc_v1_bcs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_iota_grpc_v1_bcs_proto_goTypes,
		DependencyIndexes: file_iota_grpc_v1_bcs_proto_depIdxs,
		MessageInfos:      file_iota_grpc_v1_bcs_proto_msgTypes,
	}.Build()
	File_iota_grpc_v1_bcs_proto = out.File
	file_iota_grpc_v1_bcs_proto_goTypes = nil
	file_iota_grpc_v1_bcs_proto_depIdxs = nil
}
