// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2026 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: iota/grpc/v1/state_service.proto

package state_service

import (
	_ "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/options"
	coin "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/coin"
	dynamic_field "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/dynamic_field"
	object "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/object"
	types "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for `StateService.ListDynamicFields`
type ListDynamicFieldsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The `UID` of the parent, which owns the collections of dynamic fields.
	Parent *types.ObjectId `protobuf:"bytes,1,opt,name=parent,proto3,oneof" json:"parent,omitempty"`
	// The maximum number of dynamic fields to return. The service may return fewer than this value.
	// If unspecified, at most `50` entries will be returned.
	// The maximum value is `1000`; values above `1000` will be coerced to `1000`.
	PageSize *uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	// A page token, received from a previous `ListDynamicFields` call.
	// Provide this to retrieve the subsequent page.
	//
	// When paginating, all other parameters provided to `ListDynamicFields` must
	// match the call that provided the page token.
	PageToken []byte `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	// Mask specifying which fields to read.
	// If no mask is specified, defaults to `parent,field_id`.
	ReadMask *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=read_mask,json=readMask,proto3,oneof" json:"read_mask,omitempty"`
	// Optional maximum message size the client can receive (1MB - 128MB).
	// If not specified, server uses default chunking threshold (4MB).
	MaxMessageSizeBytes *uint32 `protobuf:"varint,5,opt,name=max_message_size_bytes,json=maxMessageSizeBytes,proto3,oneof" json:"max_message_size_bytes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListDynamicFieldsRequest) Reset() {
	*x = ListDynamicFieldsRequest{}
	mi := &file_iota_grpc_v1_state_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDynamicFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDynamicFieldsRequest) ProtoMessage() {}

func (x *ListDynamicFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_state_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDynamicFieldsRequest.ProtoReflect.Descriptor instead.
func (*ListDynamicFieldsRequest) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_state_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListDynamicFieldsRequest) GetParent() *types.ObjectId {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *ListDynamicFieldsRequest) GetPageSize() uint32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListDynamicFieldsRequest) GetPageToken() []byte {
	if x != nil {
		return x.PageToken
	}
	return nil
}

func (x *ListDynamicFieldsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

func (x *ListDynamicFieldsRequest) GetMaxMessageSizeBytes() uint32 {
	if x != nil && x.MaxMessageSizeBytes != nil {
		return *x.MaxMessageSizeBytes
	}
	return 0
}

// Response message for `StateService.ListDynamicFields`
type ListDynamicFieldsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Batch of dynamic fields owned by the specified parent.
	DynamicFields []*dynamic_field.DynamicField `protobuf:"bytes,1,rep,name=dynamic_fields,json=dynamicFields,proto3" json:"dynamic_fields,omitempty"`
	// A token, which can be sent as `page_token` to retrieve the next page.
	// If this field is omitted, there are no subsequent pages.
	NextPageToken []byte `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3,oneof" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDynamicFieldsResponse) Reset() {
	*x = ListDynamicFieldsResponse{}
	mi := &file_iota_grpc_v1_state_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDynamicFieldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDynamicFieldsResponse) ProtoMessage() {}

func (x *ListDynamicFieldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_state_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDynamicFieldsResponse.ProtoReflect.Descriptor instead.
func (*ListDynamicFieldsResponse) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_state_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListDynamicFieldsResponse) GetDynamicFields() []*dynamic_field.DynamicField {
	if x != nil {
		return x.DynamicFields
	}
	return nil
}

func (x *ListDynamicFieldsResponse) GetNextPageToken() []byte {
	if x != nil {
		return x.NextPageToken
	}
	return nil
}

type ListOwnedObjectsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The address of the account that owns the objects.
	Owner *types.Address `protobuf:"bytes,1,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	// The maximum number of entries return. The service may return fewer than this value.
	// If unspecified, at most `50` entries will be returned.
	// The maximum value is `1000`; values above `1000` will be coerced to `1000`.
	PageSize *uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	// A page token, received from a previous `ListOwnedObjects` call.
	// Provide this to retrieve the subsequent page.
	//
	// When paginating, all other parameters provided to `ListOwnedObjects` must
	// match the call that provided the page token.
	PageToken []byte `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	// Mask specifying which fields to read.
	// If no mask is specified, defaults to `reference,bcs`.
	ReadMask *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=read_mask,json=readMask,proto3,oneof" json:"read_mask,omitempty"`
	// Optional type filter to limit the types of objects listed.
	//
	// Providing an object type with no type params will return objects of that
	// type with any type parameter, e.g. `0x2::coin::Coin` will return all
	// `Coin<T>` objects regardless of the type parameter `T`. Providing a type
	// with a type param will restrict the returned objects to only those objects
	// that match the provided type parameters, e.g.
	// `0x2::coin::Coin<0x2::iota::IOTA>` will only return `Coin<IOTA>` objects.
	ObjectType *string `protobuf:"bytes,5,opt,name=object_type,json=objectType,proto3,oneof" json:"object_type,omitempty"`
	// Optional maximum message size the client can receive (1MB - 128MB).
	// If not specified, server uses default chunking threshold (4MB).
	MaxMessageSizeBytes *uint32 `protobuf:"varint,6,opt,name=max_message_size_bytes,json=maxMessageSizeBytes,proto3,oneof" json:"max_message_size_bytes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListOwnedObjectsRequest) Reset() {
	*x = ListOwnedObjectsRequest{}
	mi := &file_iota_grpc_v1_state_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOwnedObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOwnedObjectsRequest) ProtoMessage() {}

func (x *ListOwnedObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_state_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOwnedObjectsRequest.ProtoReflect.Descriptor instead.
func (*ListOwnedObjectsRequest) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_state_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListOwnedObjectsRequest) GetOwner() *types.Address {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *ListOwnedObjectsRequest) GetPageSize() uint32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListOwnedObjectsRequest) GetPageToken() []byte {
	if x != nil {
		return x.PageToken
	}
	return nil
}

func (x *ListOwnedObjectsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

func (x *ListOwnedObjectsRequest) GetObjectType() string {
	if x != nil && x.ObjectType != nil {
		return *x.ObjectType
	}
	return ""
}

func (x *ListOwnedObjectsRequest) GetMaxMessageSizeBytes() uint32 {
	if x != nil && x.MaxMessageSizeBytes != nil {
		return *x.MaxMessageSizeBytes
	}
	return 0
}

type ListOwnedObjectsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Batch of objects owned by the specified owner.
	Objects []*object.Object `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	// A token, which can be sent as `page_token` to retrieve the next page.
	// If this field is omitted, there are no subsequent pages.
	NextPageToken []byte `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3,oneof" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOwnedObjectsResponse) Reset() {
	*x = ListOwnedObjectsResponse{}
	mi := &file_iota_grpc_v1_state_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOwnedObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOwnedObjectsResponse) ProtoMessage() {}

func (x *ListOwnedObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_state_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOwnedObjectsResponse.ProtoReflect.Descriptor instead.
func (*ListOwnedObjectsResponse) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_state_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListOwnedObjectsResponse) GetObjects() []*object.Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *ListOwnedObjectsResponse) GetNextPageToken() []byte {
	if x != nil {
		return x.NextPageToken
	}
	return nil
}

// Request message for `StateService.GetCoinInfo`.
type GetCoinInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The coin type to request information about
	CoinType      *string `protobuf:"bytes,1,opt,name=coin_type,json=coinType,proto3,oneof" json:"coin_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoinInfoRequest) Reset() {
	*x = GetCoinInfoRequest{}
	mi := &file_iota_grpc_v1_state_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoinInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoinInfoRequest) ProtoMessage() {}

func (x *GetCoinInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_state_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoinInfoRequest.ProtoReflect.Descriptor instead.
func (*GetCoinInfoRequest) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_state_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetCoinInfoRequest) GetCoinType() string {
	if x != nil && x.CoinType != nil {
		return *x.CoinType
	}
	return ""
}

// Response message for `StateService.GetCoinInfo`.
type GetCoinInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The coin type.
	CoinType *string `protobuf:"bytes,1,opt,name=coin_type,json=coinType,proto3,oneof" json:"coin_type,omitempty"`
	// This field will be populated with information about this coin
	// type's `0x2::coin::CoinMetadata` if it exists and has not been wrapped.
	Metadata *coin.CoinMetadata `protobuf:"bytes,2,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	// This field will be populated with information about this coin
	// type's `0x2::coin::TreasuryCap` if it exists and has not been wrapped.
	Treasury *coin.CoinTreasury `protobuf:"bytes,3,opt,name=treasury,proto3,oneof" json:"treasury,omitempty"`
	// If this coin type is a regulated coin, this field will be
	// populated with information either from its Currency object
	// in the CoinRegistry, or from its `0x2::coin::RegulatedCoinMetadata`
	// object for coins that have not been migrated to the CoinRegistry
	//
	// If this coin is not known to be regulated, only the
	// coin_regulated_state field will be populated.
	RegulatedMetadata *coin.RegulatedCoinMetadata `protobuf:"bytes,4,opt,name=regulated_metadata,json=regulatedMetadata,proto3,oneof" json:"regulated_metadata,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetCoinInfoResponse) Reset() {
	*x = GetCoinInfoResponse{}
	mi := &file_iota_grpc_v1_state_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoinInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoinInfoResponse) ProtoMessage() {}

func (x *GetCoinInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_state_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoinInfoResponse.ProtoReflect.Descriptor instead.
func (*GetCoinInfoResponse) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_state_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetCoinInfoResponse) GetCoinType() string {
	if x != nil && x.CoinType != nil {
		return *x.CoinType
	}
	return ""
}

func (x *GetCoinInfoResponse) GetMetadata() *coin.CoinMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetCoinInfoResponse) GetTreasury() *coin.CoinTreasury {
	if x != nil {
		return x.Treasury
	}
	return nil
}

func (x *GetCoinInfoResponse) GetRegulatedMetadata() *coin.RegulatedCoinMetadata {
	if x != nil {
		return x.RegulatedMetadata
	}
	return nil
}

var File_iota_grpc_v1_state_service_proto protoreflect.FileDescriptor

const file_iota_grpc_v1_state_service_proto_rawDesc = "" +
	"\n" +
	" iota/grpc/v1/state_service.proto\x12\x1aiota.grpc.v1.state_service\x1a google/protobuf/field_mask.proto\x1a\x17iota/grpc/options.proto\x1a\x17iota/grpc/v1/coin.proto\x1a iota/grpc/v1/dynamic_field.proto\x1a\x19iota/grpc/v1/object.proto\x1a\x18iota/grpc/v1/types.proto\"\xee\x02\n" +
	"\x18ListDynamicFieldsRequest\x129\n" +
	"\x06parent\x18\x01 \x01(\v2\x1c.iota.grpc.v1.types.ObjectIdH\x00R\x06parent\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x02 \x01(\rH\x01R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\fH\x02R\tpageToken\x88\x01\x01\x12<\n" +
	"\tread_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskH\x03R\breadMask\x88\x01\x01\x128\n" +
	"\x16max_message_size_bytes\x18\x05 \x01(\rH\x04R\x13maxMessageSizeBytes\x88\x01\x01:\b\x82\xb5\x18\x04withB\t\n" +
	"\a_parentB\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_tokenB\f\n" +
	"\n" +
	"_read_maskB\x19\n" +
	"\x17_max_message_size_bytes\"\xb7\x01\n" +
	"\x19ListDynamicFieldsResponse\x12O\n" +
	"\x0edynamic_fields\x18\x01 \x03(\v2(.iota.grpc.v1.dynamic_field.DynamicFieldR\rdynamicFields\x12+\n" +
	"\x0fnext_page_token\x18\x02 \x01(\fH\x00R\rnextPageToken\x88\x01\x01:\b\x82\xb5\x18\x04withB\x12\n" +
	"\x10_next_page_token\"\x9f\x03\n" +
	"\x17ListOwnedObjectsRequest\x126\n" +
	"\x05owner\x18\x01 \x01(\v2\x1b.iota.grpc.v1.types.AddressH\x00R\x05owner\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x02 \x01(\rH\x01R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\fH\x02R\tpageToken\x88\x01\x01\x12<\n" +
	"\tread_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskH\x03R\breadMask\x88\x01\x01\x12$\n" +
	"\vobject_type\x18\x05 \x01(\tH\x04R\n" +
	"objectType\x88\x01\x01\x128\n" +
	"\x16max_message_size_bytes\x18\x06 \x01(\rH\x05R\x13maxMessageSizeBytes\x88\x01\x01:\b\x82\xb5\x18\x04withB\b\n" +
	"\x06_ownerB\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_tokenB\f\n" +
	"\n" +
	"_read_maskB\x0e\n" +
	"\f_object_typeB\x19\n" +
	"\x17_max_message_size_bytes\"\x9c\x01\n" +
	"\x18ListOwnedObjectsResponse\x125\n" +
	"\aobjects\x18\x01 \x03(\v2\x1b.iota.grpc.v1.object.ObjectR\aobjects\x12+\n" +
	"\x0fnext_page_token\x18\x02 \x01(\fH\x00R\rnextPageToken\x88\x01\x01:\b\x82\xb5\x18\x04withB\x12\n" +
	"\x10_next_page_token\"N\n" +
	"\x12GetCoinInfoRequest\x12 \n" +
	"\tcoin_type\x18\x01 \x01(\tH\x00R\bcoinType\x88\x01\x01:\b\x82\xb5\x18\x04withB\f\n" +
	"\n" +
	"_coin_type\"\xe2\x02\n" +
	"\x13GetCoinInfoResponse\x12 \n" +
	"\tcoin_type\x18\x01 \x01(\tH\x00R\bcoinType\x88\x01\x01\x12@\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1f.iota.grpc.v1.coin.CoinMetadataH\x01R\bmetadata\x88\x01\x01\x12@\n" +
	"\btreasury\x18\x03 \x01(\v2\x1f.iota.grpc.v1.coin.CoinTreasuryH\x02R\btreasury\x88\x01\x01\x12\\\n" +
	"\x12regulated_metadata\x18\x04 \x01(\v2(.iota.grpc.v1.coin.RegulatedCoinMetadataH\x03R\x11regulatedMetadata\x88\x01\x01:\b\x82\xb5\x18\x04withB\f\n" +
	"\n" +
	"_coin_typeB\v\n" +
	"\t_metadataB\v\n" +
	"\t_treasuryB\x15\n" +
	"\x13_regulated_metadata2\x80\x03\n" +
	"\fStateService\x12\x80\x01\n" +
	"\x11ListDynamicFields\x124.iota.grpc.v1.state_service.ListDynamicFieldsRequest\x1a5.iota.grpc.v1.state_service.ListDynamicFieldsResponse\x12}\n" +
	"\x10ListOwnedObjects\x123.iota.grpc.v1.state_service.ListOwnedObjectsRequest\x1a4.iota.grpc.v1.state_service.ListOwnedObjectsResponse\x12n\n" +
	"\vGetCoinInfo\x12..iota.grpc.v1.state_service.GetCoinInfoRequest\x1a/.iota.grpc.v1.state_service.GetCoinInfoResponseb\x06proto3"

var (
	file_iota_grpc_v1_state_service_proto_rawDescOnce sync.Once
	file_iota_grpc_v1_state_service_proto_rawDescData []byte
)

func file_iota_grpc_v1_state_service_proto_rawDescGZIP() []byte {
	file_iota_grpc_v1_state_service_proto_rawDescOnce.Do(func() {
		file_iota_grpc_v1_state_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_state_service_proto_rawDesc), len(file_iota_grpc_v1_state_service_proto_rawDesc)))
	})
	return file_iota_grpc_v1_state_service_proto_rawDescData
}

var file_iota_grpc_v1_state_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_iota_grpc_v1_state_service_proto_goTypes = []any{
	(*ListDynamicFieldsRequest)(nil),   // 0: iota.grpc.v1.state_service.ListDynamicFieldsRequest
	(*ListDynamicFieldsResponse)(nil),  // 1: iota.grpc.v1.state_service.ListDynamicFieldsResponse
	(*ListOwnedObjectsRequest)(nil),    // 2: iota.grpc.v1.state_service.ListOwnedObjectsRequest
	(*ListOwnedObjectsResponse)(nil),   // 3: iota.grpc.v1.state_service.ListOwnedObjectsResponse
	(*GetCoinInfoRequest)(nil),         // 4: iota.grpc.v1.state_service.GetCoinInfoRequest
	(*GetCoinInfoResponse)(nil),        // 5: iota.grpc.v1.state_service.GetCoinInfoResponse
	(*types.ObjectId)(nil),             // 6: iota.grpc.v1.types.ObjectId
	(*fieldmaskpb.FieldMask)(nil),      // 7: google.protobuf.FieldMask
	(*dynamic_field.DynamicField)(nil), // 8: iota.grpc.v1.dynamic_field.DynamicField
	(*types.Address)(nil),              // 9: iota.grpc.v1.types.Address
	(*object.Object)(nil),              // 10: iota.grpc.v1.object.Object
	(*coin.CoinMetadata)(nil),          // 11: iota.grpc.v1.coin.CoinMetadata
	(*coin.CoinTreasury)(nil),          // 12: iota.grpc.v1.coin.CoinTreasury
	(*coin.RegulatedCoinMetadata)(nil), // 13: iota.grpc.v1.coin.RegulatedCoinMetadata
}
var file_iota_grpc_v1_state_service_proto_depIdxs = []int32{
	6,  // 0: iota.grpc.v1.state_service.ListDynamicFieldsRequest.parent:type_name -> iota.grpc.v1.types.ObjectId
	7,  // 1: iota.grpc.v1.state_service.ListDynamicFieldsRequest.read_mask:type_name -> google.protobuf.FieldMask
	8,  // 2: iota.grpc.v1.state_service.ListDynamicFieldsResponse.dynamic_fields:type_name -> iota.grpc.v1.dynamic_field.DynamicField
	9,  // 3: iota.grpc.v1.state_service.ListOwnedObjectsRequest.owner:type_name -> iota.grpc.v1.types.Address
	7,  // 4: iota.grpc.v1.state_service.ListOwnedObjectsRequest.read_mask:type_name -> google.protobuf.FieldMask
	10, // 5: iota.grpc.v1.state_service.ListOwnedObjectsResponse.objects:type_name -> iota.grpc.v1.object.Object
	11, // 6: iota.grpc.v1.state_service.GetCoinInfoResponse.metadata:type_name -> iota.grpc.v1.coin.CoinMetadata
	12, // 7: iota.grpc.v1.state_service.GetCoinInfoResponse.treasury:type_name -> iota.grpc.v1.coin.CoinTreasury
	13, // 8: iota.grpc.v1.state_service.GetCoinInfoResponse.regulated_metadata:type_name -> iota.grpc.v1.coin.RegulatedCoinMetadata
	0,  // 9: iota.grpc.v1.state_service.StateService.ListDynamicFields:input_type -> iota.grpc.v1.state_service.ListDynamicFieldsRequest
	2,  // 10: iota.grpc.v1.state_service.StateService.ListOwnedObjects:input_type -> iota.grpc.v1.state_service.ListOwnedObjectsRequest
	4,  // 11: iota.grpc.v1.state_service.StateService.GetCoinInfo:input_type -> iota.grpc.v1.state_service.GetCoinInfoRequest
	1,  // 12: iota.grpc.v1.state_service.StateService.ListDynamicFields:output_type -> iota.grpc.v1.state_service.ListDynamicFieldsResponse
	3,  // 13: iota.grpc.v1.state_service.StateService.ListOwnedObjects:output_type -> iota.grpc.v1.state_service.ListOwnedObjectsResponse
	5,  // 14: iota.grpc.v1.state_service.StateService.GetCoinInfo:output_type -> iota.grpc.v1.state_service.GetCoinInfoResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_iota_grpc_v1_state_service_proto_init() }
func file_iota_grpc_v1_state_service_proto_init() {
	if File_iota_grpc_v1_state_service_proto != nil {
		return
	}
	file_iota_grpc_v1_state_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_iota_grpc_v1_state_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_iota_grpc_v1_state_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_iota_grpc_v1_state_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_iota_grpc_v1_state_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_iota_grpc_v1_state_service_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_state_service_proto_rawDesc), len(file_iota_grpc_v1_state_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iota_grpc_v1_state_service_proto_goTypes,
		DependencyIndexes: file_iota_grpc_v1_state_service_proto_depIdxs,
		MessageInfos:      file_iota_grpc_v1_state_service_proto_msgTypes,
	}.Build()
	File_iota_grpc_v1_state_service_proto = out.File
	file_iota_grpc_v1_state_service_proto_goTypes = nil
	file_iota_grpc_v1_state_service_proto_depIdxs = nil
}
