// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2026 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: iota/grpc/v1/dynamic_field.proto

package dynamic_field

import (
	_ "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/options"
	bcs "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/bcs"
	object "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/object"
	types "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DynamicField_DynamicFieldKind int32

const (
	DynamicField_DYNAMIC_FIELD_KIND_UNKNOWN DynamicField_DynamicFieldKind = 0
	DynamicField_FIELD                      DynamicField_DynamicFieldKind = 1
	DynamicField_OBJECT                     DynamicField_DynamicFieldKind = 2
)

// Enum value maps for DynamicField_DynamicFieldKind.
var (
	DynamicField_DynamicFieldKind_name = map[int32]string{
		0: "DYNAMIC_FIELD_KIND_UNKNOWN",
		1: "FIELD",
		2: "OBJECT",
	}
	DynamicField_DynamicFieldKind_value = map[string]int32{
		"DYNAMIC_FIELD_KIND_UNKNOWN": 0,
		"FIELD":                      1,
		"OBJECT":                     2,
	}
)

func (x DynamicField_DynamicFieldKind) Enum() *DynamicField_DynamicFieldKind {
	p := new(DynamicField_DynamicFieldKind)
	*p = x
	return p
}

func (x DynamicField_DynamicFieldKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DynamicField_DynamicFieldKind) Descriptor() protoreflect.EnumDescriptor {
	return file_iota_grpc_v1_dynamic_field_proto_enumTypes[0].Descriptor()
}

func (DynamicField_DynamicFieldKind) Type() protoreflect.EnumType {
	return &file_iota_grpc_v1_dynamic_field_proto_enumTypes[0]
}

func (x DynamicField_DynamicFieldKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DynamicField_DynamicFieldKind.Descriptor instead.
func (DynamicField_DynamicFieldKind) EnumDescriptor() ([]byte, []int) {
	return file_iota_grpc_v1_dynamic_field_proto_rawDescGZIP(), []int{0, 0}
}

type DynamicField struct {
	state protoimpl.MessageState         `protogen:"open.v1"`
	Kind  *DynamicField_DynamicFieldKind `protobuf:"varint,1,opt,name=kind,proto3,enum=iota.grpc.v1.dynamic_field.DynamicField_DynamicFieldKind,oneof" json:"kind,omitempty"`
	// ObjectId of this dynamic field's parent.
	Parent *types.ObjectId `protobuf:"bytes,2,opt,name=parent,proto3,oneof" json:"parent,omitempty"`
	// ObjectId of this dynamic field.
	FieldId *types.ObjectId `protobuf:"bytes,3,opt,name=field_id,json=fieldId,proto3,oneof" json:"field_id,omitempty"`
	// The field object itself
	FieldObject *object.Object `protobuf:"bytes,4,opt,name=field_object,json=fieldObject,proto3,oneof" json:"field_object,omitempty"`
	// The dynamic field's "name"
	Name *bcs.BcsData `protobuf:"bytes,5,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// The dynamic field's "value".
	//
	// For regular dynamic fields this contains the BCS-encoded value whose type
	// is given by `value_type`. For dynamic *object* fields this contains the
	// BCS-encoded ObjectID of the child object; use `child_object` to access the
	// full object.
	Value *bcs.BcsData `protobuf:"bytes,6,opt,name=value,proto3,oneof" json:"value,omitempty"`
	// The type of the dynamic field "value".
	//
	// For regular dynamic fields this is the Move type of the value stored
	// in the `value` field. For dynamic *object* fields this is the Move type
	// of the child object itself (e.g. `0x2::coin::Coin<0x2::iota::IOTA>`),
	// not `0x2::object::ID` — clients should use `child_object` rather than
	// BCS-decoding `value` with this type.
	ValueType *string `protobuf:"bytes,7,opt,name=value_type,json=valueType,proto3,oneof" json:"value_type,omitempty"`
	// The ObjectId of the child object when a child is a dynamic
	// object field.
	//
	// The presence or absence of this field can be used to determine if a child
	// is a dynamic field or a dynamic child object
	ChildId *types.ObjectId `protobuf:"bytes,8,opt,name=child_id,json=childId,proto3,oneof" json:"child_id,omitempty"`
	// The object itself when a child is a dynamic object field.
	ChildObject   *object.Object `protobuf:"bytes,9,opt,name=child_object,json=childObject,proto3,oneof" json:"child_object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamicField) Reset() {
	*x = DynamicField{}
	mi := &file_iota_grpc_v1_dynamic_field_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicField) ProtoMessage() {}

func (x *DynamicField) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_dynamic_field_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicField.ProtoReflect.Descriptor instead.
func (*DynamicField) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_dynamic_field_proto_rawDescGZIP(), []int{0}
}

func (x *DynamicField) GetKind() DynamicField_DynamicFieldKind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return DynamicField_DYNAMIC_FIELD_KIND_UNKNOWN
}

func (x *DynamicField) GetParent() *types.ObjectId {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *DynamicField) GetFieldId() *types.ObjectId {
	if x != nil {
		return x.FieldId
	}
	return nil
}

func (x *DynamicField) GetFieldObject() *object.Object {
	if x != nil {
		return x.FieldObject
	}
	return nil
}

func (x *DynamicField) GetName() *bcs.BcsData {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *DynamicField) GetValue() *bcs.BcsData {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *DynamicField) GetValueType() string {
	if x != nil && x.ValueType != nil {
		return *x.ValueType
	}
	return ""
}

func (x *DynamicField) GetChildId() *types.ObjectId {
	if x != nil {
		return x.ChildId
	}
	return nil
}

func (x *DynamicField) GetChildObject() *object.Object {
	if x != nil {
		return x.ChildObject
	}
	return nil
}

var File_iota_grpc_v1_dynamic_field_proto protoreflect.FileDescriptor

const file_iota_grpc_v1_dynamic_field_proto_rawDesc = "" +
	"\n" +
	" iota/grpc/v1/dynamic_field.proto\x12\x1aiota.grpc.v1.dynamic_field\x1a\x17iota/grpc/options.proto\x1a\x16iota/grpc/v1/bcs.proto\x1a\x19iota/grpc/v1/object.proto\x1a\x18iota/grpc/v1/types.proto\"\xf8\x05\n" +
	"\fDynamicField\x12R\n" +
	"\x04kind\x18\x01 \x01(\x0e29.iota.grpc.v1.dynamic_field.DynamicField.DynamicFieldKindH\x00R\x04kind\x88\x01\x01\x129\n" +
	"\x06parent\x18\x02 \x01(\v2\x1c.iota.grpc.v1.types.ObjectIdH\x01R\x06parent\x88\x01\x01\x12<\n" +
	"\bfield_id\x18\x03 \x01(\v2\x1c.iota.grpc.v1.types.ObjectIdH\x02R\afieldId\x88\x01\x01\x12C\n" +
	"\ffield_object\x18\x04 \x01(\v2\x1b.iota.grpc.v1.object.ObjectH\x03R\vfieldObject\x88\x01\x01\x122\n" +
	"\x04name\x18\x05 \x01(\v2\x19.iota.grpc.v1.bcs.BcsDataH\x04R\x04name\x88\x01\x01\x124\n" +
	"\x05value\x18\x06 \x01(\v2\x19.iota.grpc.v1.bcs.BcsDataH\x05R\x05value\x88\x01\x01\x12\"\n" +
	"\n" +
	"value_type\x18\a \x01(\tH\x06R\tvalueType\x88\x01\x01\x12<\n" +
	"\bchild_id\x18\b \x01(\v2\x1c.iota.grpc.v1.types.ObjectIdH\aR\achildId\x88\x01\x01\x12C\n" +
	"\fchild_object\x18\t \x01(\v2\x1b.iota.grpc.v1.object.ObjectH\bR\vchildObject\x88\x01\x01\"I\n" +
	"\x10DynamicFieldKind\x12\x1e\n" +
	"\x1aDYNAMIC_FIELD_KIND_UNKNOWN\x10\x00\x12\t\n" +
	"\x05FIELD\x10\x01\x12\n" +
	"\n" +
	"\x06OBJECT\x10\x02:\b\x82\xb5\x18\x04withB\a\n" +
	"\x05_kindB\t\n" +
	"\a_parentB\v\n" +
	"\t_field_idB\x0f\n" +
	"\r_field_objectB\a\n" +
	"\x05_nameB\b\n" +
	"\x06_valueB\r\n" +
	"\v_value_typeB\v\n" +
	"\t_child_idB\x0f\n" +
	"\r_child_objectb\x06proto3"

var (
	file_iota_grpc_v1_dynamic_field_proto_rawDescOnce sync.Once
	file_iota_grpc_v1_dynamic_field_proto_rawDescData []byte
)

func file_iota_grpc_v1_dynamic_field_proto_rawDescGZIP() []byte {
	file_iota_grpc_v1_dynamic_field_proto_rawDescOnce.Do(func() {
		file_iota_grpc_v1_dynamic_field_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_dynamic_field_proto_rawDesc), len(file_iota_grpc_v1_dynamic_field_proto_rawDesc)))
	})
	return file_iota_grpc_v1_dynamic_field_proto_rawDescData
}

var file_iota_grpc_v1_dynamic_field_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_iota_grpc_v1_dynamic_field_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_iota_grpc_v1_dynamic_field_proto_goTypes = []any{
	(DynamicField_DynamicFieldKind)(0), // 0: iota.grpc.v1.dynamic_field.DynamicField.DynamicFieldKind
	(*DynamicField)(nil),               // 1: iota.grpc.v1.dynamic_field.DynamicField
	(*types.ObjectId)(nil),             // 2: iota.grpc.v1.types.ObjectId
	(*object.Object)(nil),              // 3: iota.grpc.v1.object.Object
	(*bcs.BcsData)(nil),                // 4: iota.grpc.v1.bcs.BcsData
}
var file_iota_grpc_v1_dynamic_field_proto_depIdxs = []int32{
	0, // 0: iota.grpc.v1.dynamic_field.DynamicField.kind:type_name -> iota.grpc.v1.dynamic_field.DynamicField.DynamicFieldKind
	2, // 1: iota.grpc.v1.dynamic_field.DynamicField.parent:type_name -> iota.grpc.v1.types.ObjectId
	2, // 2: iota.grpc.v1.dynamic_field.DynamicField.field_id:type_name -> iota.grpc.v1.types.ObjectId
	3, // 3: iota.grpc.v1.dynamic_field.DynamicField.field_object:type_name -> iota.grpc.v1.object.Object
	4, // 4: iota.grpc.v1.dynamic_field.DynamicField.name:type_name -> iota.grpc.v1.bcs.BcsData
	4, // 5: iota.grpc.v1.dynamic_field.DynamicField.value:type_name -> iota.grpc.v1.bcs.BcsData
	2, // 6: iota.grpc.v1.dynamic_field.DynamicField.child_id:type_name -> iota.grpc.v1.types.ObjectId
	3, // 7: iota.grpc.v1.dynamic_field.DynamicField.child_object:type_name -> iota.grpc.v1.object.Object
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_iota_grpc_v1_dynamic_field_proto_init() }
func file_iota_grpc_v1_dynamic_field_proto_init() {
	if File_iota_grpc_v1_dynamic_field_proto != nil {
		return
	}
	file_iota_grpc_v1_dynamic_field_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_dynamic_field_proto_rawDesc), len(file_iota_grpc_v1_dynamic_field_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_iota_grpc_v1_dynamic_field_proto_goTypes,
		DependencyIndexes: file_iota_grpc_v1_dynamic_field_proto_depIdxs,
		EnumInfos:         file_iota_grpc_v1_dynamic_field_proto_enumTypes,
		MessageInfos:      file_iota_grpc_v1_dynamic_field_proto_msgTypes,
	}.Build()
	File_iota_grpc_v1_dynamic_field_proto = out.File
	file_iota_grpc_v1_dynamic_field_proto_goTypes = nil
	file_iota_grpc_v1_dynamic_field_proto_depIdxs = nil
}
