// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: iota/grpc/v1/command.proto

package command

import (
	_ "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/options"
	bcs "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/bcs"
	types "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An argument to a programmable transaction command.
type Argument struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Argument_Unknown_
	//	*Argument_GasCoin_
	//	*Argument_Input_
	//	*Argument_Result_
	Kind          isArgument_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Argument) Reset() {
	*x = Argument{}
	mi := &file_iota_grpc_v1_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Argument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Argument) ProtoMessage() {}

func (x *Argument) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Argument.ProtoReflect.Descriptor instead.
func (*Argument) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_command_proto_rawDescGZIP(), []int{0}
}

func (x *Argument) GetKind() isArgument_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Argument) GetUnknown() *Argument_Unknown {
	if x != nil {
		if x, ok := x.Kind.(*Argument_Unknown_); ok {
			return x.Unknown
		}
	}
	return nil
}

func (x *Argument) GetGasCoin() *Argument_GasCoin {
	if x != nil {
		if x, ok := x.Kind.(*Argument_GasCoin_); ok {
			return x.GasCoin
		}
	}
	return nil
}

func (x *Argument) GetInput() *Argument_Input {
	if x != nil {
		if x, ok := x.Kind.(*Argument_Input_); ok {
			return x.Input
		}
	}
	return nil
}

func (x *Argument) GetResult() *Argument_Result {
	if x != nil {
		if x, ok := x.Kind.(*Argument_Result_); ok {
			return x.Result
		}
	}
	return nil
}

type isArgument_Kind interface {
	isArgument_Kind()
}

type Argument_Unknown_ struct {
	Unknown *Argument_Unknown `protobuf:"bytes,1,opt,name=unknown,proto3,oneof"`
}

type Argument_GasCoin_ struct {
	GasCoin *Argument_GasCoin `protobuf:"bytes,2,opt,name=gas_coin,json=gasCoin,proto3,oneof"`
}

type Argument_Input_ struct {
	Input *Argument_Input `protobuf:"bytes,3,opt,name=input,proto3,oneof"`
}

type Argument_Result_ struct {
	Result *Argument_Result `protobuf:"bytes,4,opt,name=result,proto3,oneof"`
}

func (*Argument_Unknown_) isArgument_Kind() {}

func (*Argument_GasCoin_) isArgument_Kind() {}

func (*Argument_Input_) isArgument_Kind() {}

func (*Argument_Result_) isArgument_Kind() {}

type CommandOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Argument      *Argument              `protobuf:"bytes,1,opt,name=argument,proto3,oneof" json:"argument,omitempty"`
	TypeTag       *types.TypeTag         `protobuf:"bytes,2,opt,name=type_tag,json=typeTag,proto3,oneof" json:"type_tag,omitempty"`
	Bcs           *bcs.BcsData           `protobuf:"bytes,3,opt,name=bcs,proto3,oneof" json:"bcs,omitempty"`
	Json          *structpb.Value        `protobuf:"bytes,4,opt,name=json,proto3,oneof" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandOutput) Reset() {
	*x = CommandOutput{}
	mi := &file_iota_grpc_v1_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandOutput) ProtoMessage() {}

func (x *CommandOutput) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandOutput.ProtoReflect.Descriptor instead.
func (*CommandOutput) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_command_proto_rawDescGZIP(), []int{1}
}

func (x *CommandOutput) GetArgument() *Argument {
	if x != nil {
		return x.Argument
	}
	return nil
}

func (x *CommandOutput) GetTypeTag() *types.TypeTag {
	if x != nil {
		return x.TypeTag
	}
	return nil
}

func (x *CommandOutput) GetBcs() *bcs.BcsData {
	if x != nil {
		return x.Bcs
	}
	return nil
}

func (x *CommandOutput) GetJson() *structpb.Value {
	if x != nil {
		return x.Json
	}
	return nil
}

type CommandOutputs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outputs       []*CommandOutput       `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandOutputs) Reset() {
	*x = CommandOutputs{}
	mi := &file_iota_grpc_v1_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandOutputs) ProtoMessage() {}

func (x *CommandOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandOutputs.ProtoReflect.Descriptor instead.
func (*CommandOutputs) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_command_proto_rawDescGZIP(), []int{2}
}

func (x *CommandOutputs) GetOutputs() []*CommandOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

// An intermediate result/output from the execution of a single command
type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MutatedByRef  *CommandOutputs        `protobuf:"bytes,1,opt,name=mutated_by_ref,json=mutatedByRef,proto3,oneof" json:"mutated_by_ref,omitempty"`
	ReturnValues  *CommandOutputs        `protobuf:"bytes,2,opt,name=return_values,json=returnValues,proto3,oneof" json:"return_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_iota_grpc_v1_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_command_proto_rawDescGZIP(), []int{3}
}

func (x *CommandResult) GetMutatedByRef() *CommandOutputs {
	if x != nil {
		return x.MutatedByRef
	}
	return nil
}

func (x *CommandResult) GetReturnValues() *CommandOutputs {
	if x != nil {
		return x.ReturnValues
	}
	return nil
}

type CommandResults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*CommandResult       `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResults) Reset() {
	*x = CommandResults{}
	mi := &file_iota_grpc_v1_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResults) ProtoMessage() {}

func (x *CommandResults) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResults.ProtoReflect.Descriptor instead.
func (*CommandResults) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_command_proto_rawDescGZIP(), []int{4}
}

func (x *CommandResults) GetResults() []*CommandResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// Unknown Argument kind.
type Argument_Unknown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Argument_Unknown) Reset() {
	*x = Argument_Unknown{}
	mi := &file_iota_grpc_v1_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Argument_Unknown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Argument_Unknown) ProtoMessage() {}

func (x *Argument_Unknown) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Argument_Unknown.ProtoReflect.Descriptor instead.
func (*Argument_Unknown) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_command_proto_rawDescGZIP(), []int{0, 0}
}

// The gas coin.
type Argument_GasCoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Argument_GasCoin) Reset() {
	*x = Argument_GasCoin{}
	mi := &file_iota_grpc_v1_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Argument_GasCoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Argument_GasCoin) ProtoMessage() {}

func (x *Argument_GasCoin) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Argument_GasCoin.ProtoReflect.Descriptor instead.
func (*Argument_GasCoin) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_command_proto_rawDescGZIP(), []int{0, 1}
}

// One of the input objects or primitive values
// (from `ProgrammableTransaction` inputs).
type Argument_Input struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index of an input when `kind` is `Input`.
	Index         *uint32 `protobuf:"varint,1,opt,name=index,proto3,oneof" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Argument_Input) Reset() {
	*x = Argument_Input{}
	mi := &file_iota_grpc_v1_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Argument_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Argument_Input) ProtoMessage() {}

func (x *Argument_Input) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Argument_Input.ProtoReflect.Descriptor instead.
func (*Argument_Input) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_command_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Argument_Input) GetIndex() uint32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

// The result of another command (from `ProgrammableTransaction` commands).
type Argument_Result struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index of a result when `kind` is `Result`.
	Index *uint32 `protobuf:"varint,1,opt,name=index,proto3,oneof" json:"index,omitempty"`
	// Used to access a nested result when `kind` is `Result`.
	NestedResultIndex *uint32 `protobuf:"varint,2,opt,name=nested_result_index,json=nestedResultIndex,proto3,oneof" json:"nested_result_index,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Argument_Result) Reset() {
	*x = Argument_Result{}
	mi := &file_iota_grpc_v1_command_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Argument_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Argument_Result) ProtoMessage() {}

func (x *Argument_Result) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_command_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Argument_Result.ProtoReflect.Descriptor instead.
func (*Argument_Result) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_command_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Argument_Result) GetIndex() uint32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *Argument_Result) GetNestedResultIndex() uint32 {
	if x != nil && x.NestedResultIndex != nil {
		return *x.NestedResultIndex
	}
	return 0
}

var File_iota_grpc_v1_command_proto protoreflect.FileDescriptor

const file_iota_grpc_v1_command_proto_rawDesc = "" +
	"\n" +
	"\x1aiota/grpc/v1/command.proto\x12\x14iota.grpc.v1.command\x1a\x1cgoogle/protobuf/struct.proto\x1a\x17iota/grpc/options.proto\x1a\x16iota/grpc/v1/bcs.proto\x1a\x18iota/grpc/v1/types.proto\"\xda\x03\n" +
	"\bArgument\x12B\n" +
	"\aunknown\x18\x01 \x01(\v2&.iota.grpc.v1.command.Argument.UnknownH\x00R\aunknown\x12C\n" +
	"\bgas_coin\x18\x02 \x01(\v2&.iota.grpc.v1.command.Argument.GasCoinH\x00R\agasCoin\x12<\n" +
	"\x05input\x18\x03 \x01(\v2$.iota.grpc.v1.command.Argument.InputH\x00R\x05input\x12?\n" +
	"\x06result\x18\x04 \x01(\v2%.iota.grpc.v1.command.Argument.ResultH\x00R\x06result\x1a\t\n" +
	"\aUnknown\x1a\t\n" +
	"\aGasCoin\x1a,\n" +
	"\x05Input\x12\x19\n" +
	"\x05index\x18\x01 \x01(\rH\x00R\x05index\x88\x01\x01B\b\n" +
	"\x06_index\x1az\n" +
	"\x06Result\x12\x19\n" +
	"\x05index\x18\x01 \x01(\rH\x00R\x05index\x88\x01\x01\x123\n" +
	"\x13nested_result_index\x18\x02 \x01(\rH\x01R\x11nestedResultIndex\x88\x01\x01B\b\n" +
	"\x06_indexB\x16\n" +
	"\x14_nested_result_indexB\x06\n" +
	"\x04kind\"\x9b\x02\n" +
	"\rCommandOutput\x12?\n" +
	"\bargument\x18\x01 \x01(\v2\x1e.iota.grpc.v1.command.ArgumentH\x00R\bargument\x88\x01\x01\x12;\n" +
	"\btype_tag\x18\x02 \x01(\v2\x1b.iota.grpc.v1.types.TypeTagH\x01R\atypeTag\x88\x01\x01\x120\n" +
	"\x03bcs\x18\x03 \x01(\v2\x19.iota.grpc.v1.bcs.BcsDataH\x02R\x03bcs\x88\x01\x01\x12/\n" +
	"\x04json\x18\x04 \x01(\v2\x16.google.protobuf.ValueH\x03R\x04json\x88\x01\x01B\v\n" +
	"\t_argumentB\v\n" +
	"\t_type_tagB\x06\n" +
	"\x04_bcsB\a\n" +
	"\x05_json\"U\n" +
	"\x0eCommandOutputs\x12=\n" +
	"\aoutputs\x18\x01 \x03(\v2#.iota.grpc.v1.command.CommandOutputR\aoutputs:\x04\x90\xb5\x18\x01\"\xd5\x01\n" +
	"\rCommandResult\x12O\n" +
	"\x0emutated_by_ref\x18\x01 \x01(\v2$.iota.grpc.v1.command.CommandOutputsH\x00R\fmutatedByRef\x88\x01\x01\x12N\n" +
	"\rreturn_values\x18\x02 \x01(\v2$.iota.grpc.v1.command.CommandOutputsH\x01R\freturnValues\x88\x01\x01B\x11\n" +
	"\x0f_mutated_by_refB\x10\n" +
	"\x0e_return_values\"U\n" +
	"\x0eCommandResults\x12=\n" +
	"\aresults\x18\x01 \x03(\v2#.iota.grpc.v1.command.CommandResultR\aresults:\x04\x90\xb5\x18\x01b\x06proto3"

var (
	file_iota_grpc_v1_command_proto_rawDescOnce sync.Once
	file_iota_grpc_v1_command_proto_rawDescData []byte
)

func file_iota_grpc_v1_command_proto_rawDescGZIP() []byte {
	file_iota_grpc_v1_command_proto_rawDescOnce.Do(func() {
		file_iota_grpc_v1_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_command_proto_rawDesc), len(file_iota_grpc_v1_command_proto_rawDesc)))
	})
	return file_iota_grpc_v1_command_proto_rawDescData
}

var file_iota_grpc_v1_command_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_iota_grpc_v1_command_proto_goTypes = []any{
	(*Argument)(nil),         // 0: iota.grpc.v1.command.Argument
	(*CommandOutput)(nil),    // 1: iota.grpc.v1.command.CommandOutput
	(*CommandOutputs)(nil),   // 2: iota.grpc.v1.command.CommandOutputs
	(*CommandResult)(nil),    // 3: iota.grpc.v1.command.CommandResult
	(*CommandResults)(nil),   // 4: iota.grpc.v1.command.CommandResults
	(*Argument_Unknown)(nil), // 5: iota.grpc.v1.command.Argument.Unknown
	(*Argument_GasCoin)(nil), // 6: iota.grpc.v1.command.Argument.GasCoin
	(*Argument_Input)(nil),   // 7: iota.grpc.v1.command.Argument.Input
	(*Argument_Result)(nil),  // 8: iota.grpc.v1.command.Argument.Result
	(*types.TypeTag)(nil),    // 9: iota.grpc.v1.types.TypeTag
	(*bcs.BcsData)(nil),      // 10: iota.grpc.v1.bcs.BcsData
	(*structpb.Value)(nil),   // 11: google.protobuf.Value
}
var file_iota_grpc_v1_command_proto_depIdxs = []int32{
	5,  // 0: iota.grpc.v1.command.Argument.unknown:type_name -> iota.grpc.v1.command.Argument.Unknown
	6,  // 1: iota.grpc.v1.command.Argument.gas_coin:type_name -> iota.grpc.v1.command.Argument.GasCoin
	7,  // 2: iota.grpc.v1.command.Argument.input:type_name -> iota.grpc.v1.command.Argument.Input
	8,  // 3: iota.grpc.v1.command.Argument.result:type_name -> iota.grpc.v1.command.Argument.Result
	0,  // 4: iota.grpc.v1.command.CommandOutput.argument:type_name -> iota.grpc.v1.command.Argument
	9,  // 5: iota.grpc.v1.command.CommandOutput.type_tag:type_name -> iota.grpc.v1.types.TypeTag
	10, // 6: iota.grpc.v1.command.CommandOutput.bcs:type_name -> iota.grpc.v1.bcs.BcsData
	11, // 7: iota.grpc.v1.command.CommandOutput.json:type_name -> google.protobuf.Value
	1,  // 8: iota.grpc.v1.command.CommandOutputs.outputs:type_name -> iota.grpc.v1.command.CommandOutput
	2,  // 9: iota.grpc.v1.command.CommandResult.mutated_by_ref:type_name -> iota.grpc.v1.command.CommandOutputs
	2,  // 10: iota.grpc.v1.command.CommandResult.return_values:type_name -> iota.grpc.v1.command.CommandOutputs
	3,  // 11: iota.grpc.v1.command.CommandResults.results:type_name -> iota.grpc.v1.command.CommandResult
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_iota_grpc_v1_command_proto_init() }
func file_iota_grpc_v1_command_proto_init() {
	if File_iota_grpc_v1_command_proto != nil {
		return
	}
	file_iota_grpc_v1_command_proto_msgTypes[0].OneofWrappers = []any{
		(*Argument_Unknown_)(nil),
		(*Argument_GasCoin_)(nil),
		(*Argument_Input_)(nil),
		(*Argument_Result_)(nil),
	}
	file_iota_grpc_v1_command_proto_msgTypes[1].OneofWrappers = []any{}
	file_iota_grpc_v1_command_proto_msgTypes[3].OneofWrappers = []any{}
	file_iota_grpc_v1_command_proto_msgTypes[7].OneofWrappers = []any{}
	file_iota_grpc_v1_command_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_command_proto_rawDesc), len(file_iota_grpc_v1_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_iota_grpc_v1_command_proto_goTypes,
		DependencyIndexes: file_iota_grpc_v1_command_proto_depIdxs,
		MessageInfos:      file_iota_grpc_v1_command_proto_msgTypes,
	}.Build()
	File_iota_grpc_v1_command_proto = out.File
	file_iota_grpc_v1_command_proto_goTypes = nil
	file_iota_grpc_v1_command_proto_depIdxs = nil
}
