// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: iota/grpc/v1/checkpoint.proto

package checkpoint

import (
	_ "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/options"
	bcs "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/bcs"
	signatures "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/signatures"
	types "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A header for a checkpoint on the IOTA blockchain.
//
// On the IOTA network, checkpoints define the history of the blockchain. They are quite similar to
// the concept of blocks used by other blockchains like Bitcoin or Ethereum. The IOTA blockchain,
// however, forms checkpoints after transaction execution has already happened to provide a
// certified history of the chain, instead of being formed before execution.
//
// Checkpoints commit to a variety of state, including but not limited to:
//   - The hash of the previous checkpoint.
//   - The set of transaction digests, their corresponding effects digests, as well as the set of
//     user signatures that authorized its execution.
//   - The objects produced by a transaction.
//   - The set of live objects that make up the current state of the chain.
//   - On epoch transitions, the next validator committee.
//
// `CheckpointSummary`s themselves don't directly include all of the previous information but they
// are the top-level type by which all the information is committed to transitively via cryptographic
// hashes included in the summary. `CheckpointSummary`s are signed and certified by a quorum of
// the validator committee in a given epoch to allow verification of the chain's state.
type CheckpointSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The digest of this CheckpointSummary.
	Digest *types.Digest `protobuf:"bytes,1,opt,name=digest,proto3,oneof" json:"digest,omitempty"`
	// This CheckpointSummary serialized as BCS.
	Bcs           *bcs.BcsData `protobuf:"bytes,2,opt,name=bcs,proto3,oneof" json:"bcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointSummary) Reset() {
	*x = CheckpointSummary{}
	mi := &file_iota_grpc_v1_checkpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointSummary) ProtoMessage() {}

func (x *CheckpointSummary) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_checkpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointSummary.ProtoReflect.Descriptor instead.
func (*CheckpointSummary) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_checkpoint_proto_rawDescGZIP(), []int{0}
}

func (x *CheckpointSummary) GetDigest() *types.Digest {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *CheckpointSummary) GetBcs() *bcs.BcsData {
	if x != nil {
		return x.Bcs
	}
	return nil
}

// The committed to contents of a checkpoint.
type CheckpointContents struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The digest of this CheckpointContents.
	Digest *types.Digest `protobuf:"bytes,1,opt,name=digest,proto3,oneof" json:"digest,omitempty"`
	// This CheckpointContents serialized as BCS.
	Bcs           *bcs.BcsData `protobuf:"bytes,2,opt,name=bcs,proto3,oneof" json:"bcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointContents) Reset() {
	*x = CheckpointContents{}
	mi := &file_iota_grpc_v1_checkpoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointContents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointContents) ProtoMessage() {}

func (x *CheckpointContents) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_checkpoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointContents.ProtoReflect.Descriptor instead.
func (*CheckpointContents) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_checkpoint_proto_rawDescGZIP(), []int{1}
}

func (x *CheckpointContents) GetDigest() *types.Digest {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *CheckpointContents) GetBcs() *bcs.BcsData {
	if x != nil {
		return x.Bcs
	}
	return nil
}

type Checkpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The height of this checkpoint.
	SequenceNumber *uint64 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3,oneof" json:"sequence_number,omitempty"`
	// The `CheckpointSummary` for this checkpoint.
	Summary *CheckpointSummary `protobuf:"bytes,2,opt,name=summary,proto3,oneof" json:"summary,omitempty"`
	// The `CheckpointContents` for this checkpoint.
	Contents *CheckpointContents `protobuf:"bytes,3,opt,name=contents,proto3,oneof" json:"contents,omitempty"`
	// An aggregated quorum signature from the validator committee that
	// certified this checkpoint.
	Signature     *signatures.ValidatorAggregatedSignature `protobuf:"bytes,4,opt,name=signature,proto3,oneof" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	mi := &file_iota_grpc_v1_checkpoint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_checkpoint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_checkpoint_proto_rawDescGZIP(), []int{2}
}

func (x *Checkpoint) GetSequenceNumber() uint64 {
	if x != nil && x.SequenceNumber != nil {
		return *x.SequenceNumber
	}
	return 0
}

func (x *Checkpoint) GetSummary() *CheckpointSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *Checkpoint) GetContents() *CheckpointContents {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *Checkpoint) GetSignature() *signatures.ValidatorAggregatedSignature {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_iota_grpc_v1_checkpoint_proto protoreflect.FileDescriptor

const file_iota_grpc_v1_checkpoint_proto_rawDesc = "" +
	"\n" +
	"\x1diota/grpc/v1/checkpoint.proto\x12\x17iota.grpc.v1.checkpoint\x1a\x17iota/grpc/options.proto\x1a\x16iota/grpc/v1/bcs.proto\x1a\x1diota/grpc/v1/signatures.proto\x1a\x18iota/grpc/v1/types.proto\"\x9b\x01\n" +
	"\x11CheckpointSummary\x127\n" +
	"\x06digest\x18\x01 \x01(\v2\x1a.iota.grpc.v1.types.DigestH\x00R\x06digest\x88\x01\x01\x120\n" +
	"\x03bcs\x18\x02 \x01(\v2\x19.iota.grpc.v1.bcs.BcsDataH\x01R\x03bcs\x88\x01\x01:\b\x82\xb5\x18\x04withB\t\n" +
	"\a_digestB\x06\n" +
	"\x04_bcs\"\x9c\x01\n" +
	"\x12CheckpointContents\x127\n" +
	"\x06digest\x18\x01 \x01(\v2\x1a.iota.grpc.v1.types.DigestH\x00R\x06digest\x88\x01\x01\x120\n" +
	"\x03bcs\x18\x02 \x01(\v2\x19.iota.grpc.v1.bcs.BcsDataH\x01R\x03bcs\x88\x01\x01:\b\x82\xb5\x18\x04withB\t\n" +
	"\a_digestB\x06\n" +
	"\x04_bcs\"\xf2\x02\n" +
	"\n" +
	"Checkpoint\x12,\n" +
	"\x0fsequence_number\x18\x01 \x01(\x04H\x00R\x0esequenceNumber\x88\x01\x01\x12I\n" +
	"\asummary\x18\x02 \x01(\v2*.iota.grpc.v1.checkpoint.CheckpointSummaryH\x01R\asummary\x88\x01\x01\x12L\n" +
	"\bcontents\x18\x03 \x01(\v2+.iota.grpc.v1.checkpoint.CheckpointContentsH\x02R\bcontents\x88\x01\x01\x12X\n" +
	"\tsignature\x18\x04 \x01(\v25.iota.grpc.v1.signatures.ValidatorAggregatedSignatureH\x03R\tsignature\x88\x01\x01:\b\x82\xb5\x18\x04withB\x12\n" +
	"\x10_sequence_numberB\n" +
	"\n" +
	"\b_summaryB\v\n" +
	"\t_contentsB\f\n" +
	"\n" +
	"_signatureb\x06proto3"

var (
	file_iota_grpc_v1_checkpoint_proto_rawDescOnce sync.Once
	file_iota_grpc_v1_checkpoint_proto_rawDescData []byte
)

func file_iota_grpc_v1_checkpoint_proto_rawDescGZIP() []byte {
	file_iota_grpc_v1_checkpoint_proto_rawDescOnce.Do(func() {
		file_iota_grpc_v1_checkpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_checkpoint_proto_rawDesc), len(file_iota_grpc_v1_checkpoint_proto_rawDesc)))
	})
	return file_iota_grpc_v1_checkpoint_proto_rawDescData
}

var file_iota_grpc_v1_checkpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_iota_grpc_v1_checkpoint_proto_goTypes = []any{
	(*CheckpointSummary)(nil),                       // 0: iota.grpc.v1.checkpoint.CheckpointSummary
	(*CheckpointContents)(nil),                      // 1: iota.grpc.v1.checkpoint.CheckpointContents
	(*Checkpoint)(nil),                              // 2: iota.grpc.v1.checkpoint.Checkpoint
	(*types.Digest)(nil),                            // 3: iota.grpc.v1.types.Digest
	(*bcs.BcsData)(nil),                             // 4: iota.grpc.v1.bcs.BcsData
	(*signatures.ValidatorAggregatedSignature)(nil), // 5: iota.grpc.v1.signatures.ValidatorAggregatedSignature
}
var file_iota_grpc_v1_checkpoint_proto_depIdxs = []int32{
	3, // 0: iota.grpc.v1.checkpoint.CheckpointSummary.digest:type_name -> iota.grpc.v1.types.Digest
	4, // 1: iota.grpc.v1.checkpoint.CheckpointSummary.bcs:type_name -> iota.grpc.v1.bcs.BcsData
	3, // 2: iota.grpc.v1.checkpoint.CheckpointContents.digest:type_name -> iota.grpc.v1.types.Digest
	4, // 3: iota.grpc.v1.checkpoint.CheckpointContents.bcs:type_name -> iota.grpc.v1.bcs.BcsData
	0, // 4: iota.grpc.v1.checkpoint.Checkpoint.summary:type_name -> iota.grpc.v1.checkpoint.CheckpointSummary
	1, // 5: iota.grpc.v1.checkpoint.Checkpoint.contents:type_name -> iota.grpc.v1.checkpoint.CheckpointContents
	5, // 6: iota.grpc.v1.checkpoint.Checkpoint.signature:type_name -> iota.grpc.v1.signatures.ValidatorAggregatedSignature
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_iota_grpc_v1_checkpoint_proto_init() }
func file_iota_grpc_v1_checkpoint_proto_init() {
	if File_iota_grpc_v1_checkpoint_proto != nil {
		return
	}
	file_iota_grpc_v1_checkpoint_proto_msgTypes[0].OneofWrappers = []any{}
	file_iota_grpc_v1_checkpoint_proto_msgTypes[1].OneofWrappers = []any{}
	file_iota_grpc_v1_checkpoint_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_checkpoint_proto_rawDesc), len(file_iota_grpc_v1_checkpoint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_iota_grpc_v1_checkpoint_proto_goTypes,
		DependencyIndexes: file_iota_grpc_v1_checkpoint_proto_depIdxs,
		MessageInfos:      file_iota_grpc_v1_checkpoint_proto_msgTypes,
	}.Build()
	File_iota_grpc_v1_checkpoint_proto = out.File
	file_iota_grpc_v1_checkpoint_proto_goTypes = nil
	file_iota_grpc_v1_checkpoint_proto_depIdxs = nil
}
