// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: iota/grpc/v1/event.proto

package event

import (
	_ "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/options"
	bcs "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/bcs"
	types "github.com/iotaledger/wasp/clients/iota-go/iotagrpc/iota/grpc/v1/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An event.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This Event serialized as BCS.
	Bcs *bcs.BcsData `protobuf:"bytes,1,opt,name=bcs,proto3,oneof" json:"bcs,omitempty"`
	// Package ID of the top-level function invoked by a `MoveCall` command that triggered this
	// event to be emitted.
	PackageId *types.ObjectId `protobuf:"bytes,2,opt,name=package_id,json=packageId,proto3,oneof" json:"package_id,omitempty"`
	// Module name of the top-level function invoked by a `MoveCall` command that triggered this
	// event to be emitted.
	Module *string `protobuf:"bytes,3,opt,name=module,proto3,oneof" json:"module,omitempty"`
	// Address of the account that sent the transaction where this event was emitted.
	Sender *types.Address `protobuf:"bytes,4,opt,name=sender,proto3,oneof" json:"sender,omitempty"`
	// The type of the event emitted.
	EventType *string `protobuf:"bytes,5,opt,name=event_type,json=eventType,proto3,oneof" json:"event_type,omitempty"`
	// BCS serialized bytes of the event.
	BcsContents *bcs.BcsData `protobuf:"bytes,6,opt,name=bcs_contents,json=bcsContents,proto3,oneof" json:"bcs_contents,omitempty"`
	// JSON rendering of the event.
	JsonContents  *structpb.Value `protobuf:"bytes,7,opt,name=json_contents,json=jsonContents,proto3,oneof" json:"json_contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_iota_grpc_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetBcs() *bcs.BcsData {
	if x != nil {
		return x.Bcs
	}
	return nil
}

func (x *Event) GetPackageId() *types.ObjectId {
	if x != nil {
		return x.PackageId
	}
	return nil
}

func (x *Event) GetModule() string {
	if x != nil && x.Module != nil {
		return *x.Module
	}
	return ""
}

func (x *Event) GetSender() *types.Address {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *Event) GetEventType() string {
	if x != nil && x.EventType != nil {
		return *x.EventType
	}
	return ""
}

func (x *Event) GetBcsContents() *bcs.BcsData {
	if x != nil {
		return x.BcsContents
	}
	return nil
}

func (x *Event) GetJsonContents() *structpb.Value {
	if x != nil {
		return x.JsonContents
	}
	return nil
}

// A list of events.
type Events struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Events) Reset() {
	*x = Events{}
	mi := &file_iota_grpc_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Events) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Events) ProtoMessage() {}

func (x *Events) ProtoReflect() protoreflect.Message {
	mi := &file_iota_grpc_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Events.ProtoReflect.Descriptor instead.
func (*Events) Descriptor() ([]byte, []int) {
	return file_iota_grpc_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *Events) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_iota_grpc_v1_event_proto protoreflect.FileDescriptor

const file_iota_grpc_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x18iota/grpc/v1/event.proto\x12\x12iota.grpc.v1.event\x1a\x1cgoogle/protobuf/struct.proto\x1a\x17iota/grpc/options.proto\x1a\x16iota/grpc/v1/bcs.proto\x1a\x18iota/grpc/v1/types.proto\"\xe4\x03\n" +
	"\x05Event\x120\n" +
	"\x03bcs\x18\x01 \x01(\v2\x19.iota.grpc.v1.bcs.BcsDataH\x00R\x03bcs\x88\x01\x01\x12@\n" +
	"\n" +
	"package_id\x18\x02 \x01(\v2\x1c.iota.grpc.v1.types.ObjectIdH\x01R\tpackageId\x88\x01\x01\x12\x1b\n" +
	"\x06module\x18\x03 \x01(\tH\x02R\x06module\x88\x01\x01\x128\n" +
	"\x06sender\x18\x04 \x01(\v2\x1b.iota.grpc.v1.types.AddressH\x03R\x06sender\x88\x01\x01\x12\"\n" +
	"\n" +
	"event_type\x18\x05 \x01(\tH\x04R\teventType\x88\x01\x01\x12A\n" +
	"\fbcs_contents\x18\x06 \x01(\v2\x19.iota.grpc.v1.bcs.BcsDataH\x05R\vbcsContents\x88\x01\x01\x12@\n" +
	"\rjson_contents\x18\a \x01(\v2\x16.google.protobuf.ValueH\x06R\fjsonContents\x88\x01\x01:\b\x82\xb5\x18\x04withB\x06\n" +
	"\x04_bcsB\r\n" +
	"\v_package_idB\t\n" +
	"\a_moduleB\t\n" +
	"\a_senderB\r\n" +
	"\v_event_typeB\x0f\n" +
	"\r_bcs_contentsB\x10\n" +
	"\x0e_json_contents\"I\n" +
	"\x06Events\x121\n" +
	"\x06events\x18\x01 \x03(\v2\x19.iota.grpc.v1.event.EventR\x06events:\f\x82\xb5\x18\x04with\x90\xb5\x18\x01b\x06proto3"

var (
	file_iota_grpc_v1_event_proto_rawDescOnce sync.Once
	file_iota_grpc_v1_event_proto_rawDescData []byte
)

func file_iota_grpc_v1_event_proto_rawDescGZIP() []byte {
	file_iota_grpc_v1_event_proto_rawDescOnce.Do(func() {
		file_iota_grpc_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_event_proto_rawDesc), len(file_iota_grpc_v1_event_proto_rawDesc)))
	})
	return file_iota_grpc_v1_event_proto_rawDescData
}

var file_iota_grpc_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_iota_grpc_v1_event_proto_goTypes = []any{
	(*Event)(nil),          // 0: iota.grpc.v1.event.Event
	(*Events)(nil),         // 1: iota.grpc.v1.event.Events
	(*bcs.BcsData)(nil),    // 2: iota.grpc.v1.bcs.BcsData
	(*types.ObjectId)(nil), // 3: iota.grpc.v1.types.ObjectId
	(*types.Address)(nil),  // 4: iota.grpc.v1.types.Address
	(*structpb.Value)(nil), // 5: google.protobuf.Value
}
var file_iota_grpc_v1_event_proto_depIdxs = []int32{
	2, // 0: iota.grpc.v1.event.Event.bcs:type_name -> iota.grpc.v1.bcs.BcsData
	3, // 1: iota.grpc.v1.event.Event.package_id:type_name -> iota.grpc.v1.types.ObjectId
	4, // 2: iota.grpc.v1.event.Event.sender:type_name -> iota.grpc.v1.types.Address
	2, // 3: iota.grpc.v1.event.Event.bcs_contents:type_name -> iota.grpc.v1.bcs.BcsData
	5, // 4: iota.grpc.v1.event.Event.json_contents:type_name -> google.protobuf.Value
	0, // 5: iota.grpc.v1.event.Events.events:type_name -> iota.grpc.v1.event.Event
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_iota_grpc_v1_event_proto_init() }
func file_iota_grpc_v1_event_proto_init() {
	if File_iota_grpc_v1_event_proto != nil {
		return
	}
	file_iota_grpc_v1_event_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iota_grpc_v1_event_proto_rawDesc), len(file_iota_grpc_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_iota_grpc_v1_event_proto_goTypes,
		DependencyIndexes: file_iota_grpc_v1_event_proto_depIdxs,
		MessageInfos:      file_iota_grpc_v1_event_proto_msgTypes,
	}.Build()
	File_iota_grpc_v1_event_proto = out.File
	file_iota_grpc_v1_event_proto_goTypes = nil
	file_iota_grpc_v1_event_proto_depIdxs = nil
}
